Backend: SymbolicExpression
ClockPeriod: 5
Compiler: vivado
HLSConfig:
  Model:
    Precision: ap_fixed<7,5>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
NSymbols: 16
OutputDir: my-hls-test-nov7-7-5
OutputPredictions: null
Part: xcvu9p-flga2577-2-e
ProjectName: myproject
Stamp: 2c1dAd4B
