// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module generic_sincos_11_6_s (
        ap_clk,
        ap_rst,
        in_V,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [10:0] in_V;
output  [6:0] ap_return_0;
output  [6:0] ap_return_1;
input   ap_ce;

reg[6:0] ap_return_0;
reg[6:0] ap_return_1;

wire   [0:0] sign0_V_fu_73_p2;
reg   [0:0] sign0_V_reg_377;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] sign0_V_reg_377_pp0_iter1_reg;
reg   [0:0] sign0_V_reg_377_pp0_iter2_reg;
reg   [0:0] sign0_V_reg_377_pp0_iter3_reg;
reg   [0:0] sign0_V_reg_377_pp0_iter4_reg;
reg   [0:0] sign0_V_reg_377_pp0_iter5_reg;
reg   [0:0] sign0_V_reg_377_pp0_iter6_reg;
wire   [10:0] p_Val2_s_fu_85_p3;
reg   [10:0] p_Val2_s_reg_382;
reg   [5:0] ret_V_reg_387;
reg   [1:0] k_V_reg_392;
reg   [1:0] k_V_reg_392_pp0_iter1_reg;
reg   [1:0] k_V_reg_392_pp0_iter2_reg;
reg   [1:0] k_V_reg_392_pp0_iter3_reg;
reg   [1:0] k_V_reg_392_pp0_iter4_reg;
reg   [1:0] k_V_reg_392_pp0_iter5_reg;
reg   [1:0] k_V_reg_392_pp0_iter6_reg;
wire   [0:0] icmp_ln879_fu_138_p2;
reg   [0:0] icmp_ln879_reg_400;
reg   [0:0] icmp_ln879_reg_400_pp0_iter2_reg;
reg   [0:0] icmp_ln879_reg_400_pp0_iter3_reg;
reg   [0:0] icmp_ln879_reg_400_pp0_iter4_reg;
reg   [0:0] icmp_ln879_reg_400_pp0_iter5_reg;
reg   [0:0] icmp_ln879_reg_400_pp0_iter6_reg;
wire   [11:0] z_V_1_fu_187_p3;
reg   [11:0] z_V_1_reg_406;
reg   [12:0] x_V_reg_411;
reg   [6:0] trunc_ln1_reg_416;
reg   [6:0] trunc_ln708_13_reg_422;
reg   [6:0] trunc_ln708_14_reg_428;
wire   [12:0] grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_0;
wire   [12:0] grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_1;
reg    grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call24;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call24;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call24;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call24;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call24;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call24;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call24;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call24;
wire    ap_block_pp0_stage0_11001_ignoreCallOp33;
wire    ap_block_pp0_stage0;
wire   [10:0] inabs_V_fu_79_p2;
wire   [28:0] r_V_63_fu_359_p2;
wire   [17:0] lhs_V_fu_118_p3;
wire   [19:0] grp_fu_367_p3;
wire   [11:0] p_Val2_47_fu_129_p4;
wire   [10:0] trunc_ln708_s_fu_147_p4;
wire   [12:0] rhs_V_9_fu_143_p1;
wire   [12:0] ret_V_49_fu_160_p2;
wire   [0:0] icmp_ln251_fu_176_p2;
wire   [0:0] or_ln251_fu_181_p2;
wire   [11:0] trunc_ln708_12_fu_166_p4;
wire   [11:0] z_V_fu_156_p1;
wire   [11:0] trunc_ln1253_fu_217_p1;
wire   [11:0] r_V_65_fu_221_p2;
wire   [11:0] trunc_ln266_fu_203_p1;
wire   [11:0] r_V_66_fu_237_p2;
wire   [0:0] icmp_ln879_1_fu_253_p2;
wire   [0:0] xor_ln879_fu_269_p2;
wire   [0:0] and_ln879_fu_275_p2;
wire   [6:0] select_ln879_fu_263_p3;
wire   [0:0] or_ln879_fu_287_p2;
wire   [0:0] icmp_ln879_2_fu_258_p2;
wire   [0:0] xor_ln879_1_fu_292_p2;
wire   [0:0] and_ln879_1_fu_298_p2;
wire   [6:0] select_ln879_1_fu_280_p3;
wire   [6:0] trunc_ln3_fu_311_p4;
wire   [6:0] select_ln879_3_fu_320_p3;
wire   [6:0] p_Val2_53_fu_304_p3;
wire   [6:0] sub_ln703_fu_334_p2;
wire   [6:0] p_Val2_54_fu_340_p3;
wire   [6:0] select_ln879_4_fu_327_p3;
wire   [18:0] r_V_63_fu_359_p0;
wire   [10:0] r_V_63_fu_359_p1;
wire   [13:0] grp_fu_367_p0;
wire   [5:0] grp_fu_367_p1;
wire   [17:0] grp_fu_367_p2;
reg    ap_ce_reg;
reg   [10:0] in_V_int_reg;
reg   [6:0] ap_return_0_int_reg;
reg   [6:0] ap_return_1_int_reg;
wire   [18:0] grp_fu_367_p10;
wire   [19:0] grp_fu_367_p20;
wire   [28:0] r_V_63_fu_359_p10;

cordic_circ_apfixed_13_3_0_s grp_cordic_circ_apfixed_13_3_0_s_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .z_V_read(z_V_1_reg_406),
    .ap_return_0(grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_0),
    .ap_return_1(grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_1),
    .ap_ce(grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_ce)
);

myproject_mul_mul_19ns_11ns_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_19ns_11ns_29_1_0_U2(
    .din0(r_V_63_fu_359_p0),
    .din1(r_V_63_fu_359_p1),
    .dout(r_V_63_fu_359_p2)
);

myproject_mac_mulsub_14ns_6ns_18ns_20_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 20 ))
myproject_mac_mulsub_14ns_6ns_18ns_20_1_0_U3(
    .din0(grp_fu_367_p0),
    .din1(grp_fu_367_p1),
    .din2(grp_fu_367_p2),
    .dout(grp_fu_367_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= p_Val2_54_fu_340_p3;
        ap_return_1_int_reg <= select_ln879_4_fu_327_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln879_reg_400 <= icmp_ln879_fu_138_p2;
        icmp_ln879_reg_400_pp0_iter2_reg <= icmp_ln879_reg_400;
        icmp_ln879_reg_400_pp0_iter3_reg <= icmp_ln879_reg_400_pp0_iter2_reg;
        icmp_ln879_reg_400_pp0_iter4_reg <= icmp_ln879_reg_400_pp0_iter3_reg;
        icmp_ln879_reg_400_pp0_iter5_reg <= icmp_ln879_reg_400_pp0_iter4_reg;
        icmp_ln879_reg_400_pp0_iter6_reg <= icmp_ln879_reg_400_pp0_iter5_reg;
        k_V_reg_392 <= {{r_V_63_fu_359_p2[24:23]}};
        k_V_reg_392_pp0_iter1_reg <= k_V_reg_392;
        k_V_reg_392_pp0_iter2_reg <= k_V_reg_392_pp0_iter1_reg;
        k_V_reg_392_pp0_iter3_reg <= k_V_reg_392_pp0_iter2_reg;
        k_V_reg_392_pp0_iter4_reg <= k_V_reg_392_pp0_iter3_reg;
        k_V_reg_392_pp0_iter5_reg <= k_V_reg_392_pp0_iter4_reg;
        k_V_reg_392_pp0_iter6_reg <= k_V_reg_392_pp0_iter5_reg;
        p_Val2_s_reg_382 <= p_Val2_s_fu_85_p3;
        ret_V_reg_387 <= {{r_V_63_fu_359_p2[28:23]}};
        sign0_V_reg_377 <= sign0_V_fu_73_p2;
        sign0_V_reg_377_pp0_iter1_reg <= sign0_V_reg_377;
        sign0_V_reg_377_pp0_iter2_reg <= sign0_V_reg_377_pp0_iter1_reg;
        sign0_V_reg_377_pp0_iter3_reg <= sign0_V_reg_377_pp0_iter2_reg;
        sign0_V_reg_377_pp0_iter4_reg <= sign0_V_reg_377_pp0_iter3_reg;
        sign0_V_reg_377_pp0_iter5_reg <= sign0_V_reg_377_pp0_iter4_reg;
        sign0_V_reg_377_pp0_iter6_reg <= sign0_V_reg_377_pp0_iter5_reg;
        trunc_ln1_reg_416 <= {{grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_1[11:5]}};
        trunc_ln708_13_reg_422 <= {{r_V_65_fu_221_p2[11:5]}};
        trunc_ln708_14_reg_428 <= {{r_V_66_fu_237_p2[11:5]}};
        x_V_reg_411 <= grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_0;
        z_V_1_reg_406 <= z_V_1_fu_187_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        in_V_int_reg <= in_V;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = p_Val2_54_fu_340_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = select_ln879_4_fu_327_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp33) & (1'b1 == ap_ce_reg))) begin
        grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_ce = 1'b1;
    end else begin
        grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_ce = 1'b0;
    end
end

assign and_ln879_1_fu_298_p2 = (xor_ln879_1_fu_292_p2 & icmp_ln879_2_fu_258_p2);

assign and_ln879_fu_275_p2 = (xor_ln879_fu_269_p2 & icmp_ln879_reg_400_pp0_iter6_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp33 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call24 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call24 = ~(1'b1 == 1'b1);

assign grp_fu_367_p0 = 19'd6433;

assign grp_fu_367_p1 = grp_fu_367_p10;

assign grp_fu_367_p10 = ret_V_reg_387;

assign grp_fu_367_p2 = grp_fu_367_p20;

assign grp_fu_367_p20 = lhs_V_fu_118_p3;

assign icmp_ln251_fu_176_p2 = ((k_V_reg_392 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln879_1_fu_253_p2 = ((k_V_reg_392_pp0_iter6_reg == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_258_p2 = ((k_V_reg_392_pp0_iter6_reg == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_138_p2 = ((k_V_reg_392 == 2'd1) ? 1'b1 : 1'b0);

assign inabs_V_fu_79_p2 = (11'd0 - in_V_int_reg);

assign lhs_V_fu_118_p3 = {{p_Val2_s_reg_382}, {7'd0}};

assign or_ln251_fu_181_p2 = (icmp_ln879_fu_138_p2 | icmp_ln251_fu_176_p2);

assign or_ln879_fu_287_p2 = (icmp_ln879_reg_400_pp0_iter6_reg | icmp_ln879_1_fu_253_p2);

assign p_Val2_47_fu_129_p4 = {{grp_fu_367_p3[12:1]}};

assign p_Val2_53_fu_304_p3 = ((and_ln879_1_fu_298_p2[0:0] === 1'b1) ? trunc_ln708_14_reg_428 : select_ln879_1_fu_280_p3);

assign p_Val2_54_fu_340_p3 = ((sign0_V_reg_377_pp0_iter6_reg[0:0] === 1'b1) ? p_Val2_53_fu_304_p3 : sub_ln703_fu_334_p2);

assign p_Val2_s_fu_85_p3 = ((sign0_V_fu_73_p2[0:0] === 1'b1) ? in_V_int_reg : inabs_V_fu_79_p2);

assign r_V_63_fu_359_p0 = 29'd166886;

assign r_V_63_fu_359_p1 = r_V_63_fu_359_p10;

assign r_V_63_fu_359_p10 = p_Val2_s_fu_85_p3;

assign r_V_65_fu_221_p2 = (12'd0 - trunc_ln1253_fu_217_p1);

assign r_V_66_fu_237_p2 = (12'd0 - trunc_ln266_fu_203_p1);

assign ret_V_49_fu_160_p2 = (13'd3216 - rhs_V_9_fu_143_p1);

assign rhs_V_9_fu_143_p1 = p_Val2_47_fu_129_p4;

assign select_ln879_1_fu_280_p3 = ((and_ln879_fu_275_p2[0:0] === 1'b1) ? trunc_ln1_reg_416 : select_ln879_fu_263_p3);

assign select_ln879_3_fu_320_p3 = ((and_ln879_fu_275_p2[0:0] === 1'b1) ? trunc_ln708_13_reg_422 : trunc_ln3_fu_311_p4);

assign select_ln879_4_fu_327_p3 = ((and_ln879_1_fu_298_p2[0:0] === 1'b1) ? trunc_ln708_13_reg_422 : select_ln879_3_fu_320_p3);

assign select_ln879_fu_263_p3 = ((icmp_ln879_1_fu_253_p2[0:0] === 1'b1) ? trunc_ln1_reg_416 : trunc_ln708_14_reg_428);

assign sign0_V_fu_73_p2 = (($signed(in_V_int_reg) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign sub_ln703_fu_334_p2 = (7'd0 - p_Val2_53_fu_304_p3);

assign trunc_ln1253_fu_217_p1 = grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_0[11:0];

assign trunc_ln266_fu_203_p1 = grp_cordic_circ_apfixed_13_3_0_s_fu_68_ap_return_1[11:0];

assign trunc_ln3_fu_311_p4 = {{x_V_reg_411[11:5]}};

assign trunc_ln708_12_fu_166_p4 = {{ret_V_49_fu_160_p2[12:1]}};

assign trunc_ln708_s_fu_147_p4 = {{grp_fu_367_p3[12:2]}};

assign xor_ln879_1_fu_292_p2 = (or_ln879_fu_287_p2 ^ 1'd1);

assign xor_ln879_fu_269_p2 = (icmp_ln879_1_fu_253_p2 ^ 1'd1);

assign z_V_1_fu_187_p3 = ((or_ln251_fu_181_p2[0:0] === 1'b1) ? trunc_ln708_12_fu_166_p4 : z_V_fu_156_p1);

assign z_V_fu_156_p1 = trunc_ln708_s_fu_147_p4;

endmodule //generic_sincos_11_6_s
