-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cordic_circ_apfixed_12_3_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    z_V_read : IN STD_LOGIC_VECTOR (10 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of cordic_circ_apfixed_12_3_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv12_192 : STD_LOGIC_VECTOR (11 downto 0) := "000110010010";
    constant ap_const_lv12_E6E : STD_LOGIC_VECTOR (11 downto 0) := "111001101110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_9B : STD_LOGIC_VECTOR (8 downto 0) := "010011011";
    constant ap_const_lv9_1D1 : STD_LOGIC_VECTOR (8 downto 0) := "111010001";
    constant ap_const_lv10_22F : STD_LOGIC_VECTOR (9 downto 0) := "1000101111";
    constant ap_const_lv10_9B : STD_LOGIC_VECTOR (9 downto 0) := "0010011011";
    constant ap_const_lv10_365 : STD_LOGIC_VECTOR (9 downto 0) := "1101100101";
    constant ap_const_lv10_1D1 : STD_LOGIC_VECTOR (9 downto 0) := "0111010001";
    constant ap_const_lv12_1DA : STD_LOGIC_VECTOR (11 downto 0) := "000111011010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_F13 : STD_LOGIC_VECTOR (11 downto 0) := "111100010011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv12_FA : STD_LOGIC_VECTOR (11 downto 0) := "000011111010";
    constant ap_const_lv12_F83 : STD_LOGIC_VECTOR (11 downto 0) := "111110000011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv12_7E : STD_LOGIC_VECTOR (11 downto 0) := "000001111110";
    constant ap_const_lv12_FC1 : STD_LOGIC_VECTOR (11 downto 0) := "111111000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv12_3E : STD_LOGIC_VECTOR (11 downto 0) := "000000111110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv12_FE1 : STD_LOGIC_VECTOR (11 downto 0) := "111111100001";
    constant ap_const_lv12_1E : STD_LOGIC_VECTOR (11 downto 0) := "000000011110";
    constant ap_const_lv12_FF1 : STD_LOGIC_VECTOR (11 downto 0) := "111111110001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv12_E : STD_LOGIC_VECTOR (11 downto 0) := "000000001110";
    constant ap_const_lv12_FF9 : STD_LOGIC_VECTOR (11 downto 0) := "111111111001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv12_6 : STD_LOGIC_VECTOR (11 downto 0) := "000000000110";
    constant ap_const_lv12_FFD : STD_LOGIC_VECTOR (11 downto 0) := "111111111101";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal add_ln101_6_fu_428_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_6_reg_1193 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln101_10_fu_518_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln101_10_reg_1198 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln101_11_fu_526_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_11_reg_1203 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_12_fu_534_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_12_reg_1208 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_14_reg_1214 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_reg_1219 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln101_14_fu_841_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_14_reg_1224 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_29_reg_1229 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_23_fu_931_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln101_23_reg_1234 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln101_24_fu_939_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_24_reg_1240 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_30_reg_1246 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_reg_1251 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_V_read_cast_fu_120_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_124_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal z_V_read_cast_fu_120_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln101_fu_132_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_fu_140_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_186_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_1_fu_194_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_1_fu_202_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_146_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln203_1_fu_162_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln203_3_fu_178_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln101_2_fu_214_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln203_fu_154_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln203_2_fu_170_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln101_3_fu_226_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln_fu_238_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_252_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln101_2_fu_208_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln101_1_fu_262_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1333_2_fu_234_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln101_fu_222_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1333_fu_248_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_4_fu_306_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_3_fu_314_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_fu_266_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_fu_280_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_1_fu_292_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_fu_274_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln203_1_fu_286_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln101_6_fu_334_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_346_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln101_5_fu_326_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_360_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln101_4_fu_320_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln101_3_fu_370_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln101_fu_342_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1333_1_fu_356_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_9_fu_406_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_7_fu_414_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_5_fu_422_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_8_fu_374_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_2_fu_388_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_3_fu_400_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_2_fu_382_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_3_fu_394_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_9_fu_442_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_450_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln101_8_fu_434_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_11_fu_464_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln101_4_fu_474_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1333_fu_460_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_13_fu_510_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_478_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_4_fu_492_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_12_fu_504_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_4_fu_486_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_12_fu_498_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln101_7_fu_562_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_8_fu_567_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln101_5_fu_578_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln101_2_fu_572_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1371_fu_575_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_17_fu_611_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_13_fu_619_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_9_fu_627_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_16_fu_581_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_5_fu_594_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_13_fu_605_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_5_fu_589_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_13_fu_600_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_15_fu_647_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_18_fu_655_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln101_14_fu_639_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_19_fu_669_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln101_10_fu_633_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln101_6_fu_679_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1371_1_fu_665_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_21_fu_715_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_16_fu_723_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_11_fu_731_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_20_fu_683_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_6_fu_697_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_14_fu_709_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_6_fu_691_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_14_fu_703_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_18_fu_751_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_22_fu_759_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln101_17_fu_743_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_23_fu_773_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln101_12_fu_737_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln101_7_fu_783_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1371_2_fu_769_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_25_fu_819_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_19_fu_827_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_13_fu_835_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_24_fu_787_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_7_fu_801_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_15_fu_813_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_7_fu_795_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_15_fu_807_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_21_fu_855_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_26_fu_863_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln101_20_fu_847_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_27_fu_877_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln101_8_fu_887_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1371_3_fu_873_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_28_fu_891_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_8_fu_905_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_16_fu_917_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_8_fu_899_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_16_fu_911_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_22_fu_967_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_15_fu_974_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln101_16_fu_979_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln101_9_fu_988_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1371_4_fu_985_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_32_fu_991_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_9_fu_1004_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_17_fu_1014_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_9_fu_999_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_17_fu_1009_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_26_fu_1027_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_33_fu_1035_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_25_fu_1019_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_34_fu_1051_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln203_fu_1061_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln1371_fu_1043_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln203_10_fu_1071_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_18_fu_1083_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_10_fu_1065_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_18_fu_1077_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_28_fu_1097_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_35_fu_1105_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln101_27_fu_1089_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_36_fu_1121_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1371_2_fu_1129_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln1371_1_fu_1113_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln203_11_fu_1143_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_19_fu_1155_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln203_11_fu_1137_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln203_19_fu_1149_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln101_30_fu_1169_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln101_10_fu_1177_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln101_29_fu_1161_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal z_V_read_int_reg : STD_LOGIC_VECTOR (10 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                add_ln101_14_reg_1224 <= add_ln101_14_fu_841_p2;
                add_ln101_6_reg_1193 <= add_ln101_6_fu_428_p2;
                    select_ln101_10_reg_1198(5 downto 1) <= select_ln101_10_fu_518_p3(5 downto 1);
                select_ln101_11_reg_1203 <= select_ln101_11_fu_526_p3;
                select_ln101_12_reg_1208 <= select_ln101_12_fu_534_p3;
                select_ln101_23_reg_1234 <= select_ln101_23_fu_931_p3;
                select_ln101_24_reg_1240 <= select_ln101_24_fu_939_p3;
                tmp_14_reg_1214 <= select_ln101_12_fu_534_p3(10 downto 5);
                tmp_15_reg_1219 <= select_ln101_11_fu_526_p3(10 downto 5);
                tmp_29_reg_1229 <= add_ln101_14_fu_841_p2(11 downto 11);
                tmp_30_reg_1246 <= select_ln101_24_fu_939_p3(10 downto 9);
                tmp_31_reg_1251 <= select_ln101_23_fu_931_p3(11 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                z_V_read_int_reg <= z_V_read;
            end if;
        end if;
    end process;
    select_ln101_10_reg_1198(0) <= '0';
    select_ln101_10_reg_1198(11 downto 6) <= "000000";
    add_ln101_10_fu_633_p2 <= std_logic_vector(unsigned(select_ln101_13_fu_619_p3) + unsigned(add_ln101_9_fu_627_p2));
    add_ln101_11_fu_731_p2 <= std_logic_vector(signed(ap_const_lv12_FF9) + signed(add_ln101_10_fu_633_p2));
    add_ln101_12_fu_737_p2 <= std_logic_vector(unsigned(select_ln101_16_fu_723_p3) + unsigned(add_ln101_11_fu_731_p2));
    add_ln101_13_fu_835_p2 <= std_logic_vector(signed(ap_const_lv12_FFD) + signed(add_ln101_12_fu_737_p2));
    add_ln101_14_fu_841_p2 <= std_logic_vector(unsigned(select_ln101_19_fu_827_p3) + unsigned(add_ln101_13_fu_835_p2));
    add_ln101_15_fu_974_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(add_ln101_14_reg_1224));
    add_ln101_16_fu_979_p2 <= std_logic_vector(unsigned(select_ln101_22_fu_967_p3) + unsigned(add_ln101_15_fu_974_p2));
    add_ln101_1_fu_202_p2 <= std_logic_vector(signed(ap_const_lv12_F13) + signed(add_ln101_fu_140_p2));
    add_ln101_2_fu_208_p2 <= std_logic_vector(unsigned(select_ln101_1_fu_194_p3) + unsigned(add_ln101_1_fu_202_p2));
    add_ln101_3_fu_314_p2 <= std_logic_vector(signed(ap_const_lv12_F83) + signed(add_ln101_2_fu_208_p2));
    add_ln101_4_fu_320_p2 <= std_logic_vector(unsigned(select_ln101_4_fu_306_p3) + unsigned(add_ln101_3_fu_314_p2));
    add_ln101_5_fu_422_p2 <= std_logic_vector(signed(ap_const_lv12_FC1) + signed(add_ln101_4_fu_320_p2));
    add_ln101_6_fu_428_p2 <= std_logic_vector(unsigned(select_ln101_7_fu_414_p3) + unsigned(add_ln101_5_fu_422_p2));
    add_ln101_7_fu_562_p2 <= std_logic_vector(signed(ap_const_lv12_FE1) + signed(add_ln101_6_reg_1193));
    add_ln101_8_fu_567_p2 <= std_logic_vector(unsigned(select_ln101_10_reg_1198) + unsigned(add_ln101_7_fu_562_p2));
    add_ln101_9_fu_627_p2 <= std_logic_vector(signed(ap_const_lv12_FF1) + signed(add_ln101_8_fu_567_p2));
    add_ln101_fu_140_p2 <= std_logic_vector(signed(z_V_read_cast_fu_120_p1) + signed(select_ln101_fu_132_p3));
    add_ln203_10_fu_1065_p2 <= std_logic_vector(signed(sext_ln203_fu_1061_p1) + signed(select_ln101_26_fu_1027_p3));
    add_ln203_11_fu_1137_p2 <= std_logic_vector(unsigned(select_ln1371_2_fu_1129_p3) + unsigned(select_ln101_28_fu_1097_p3));
    add_ln203_12_fu_504_p2 <= std_logic_vector(signed(sext_ln1333_fu_460_p1) + signed(select_ln101_8_fu_434_p3));
    add_ln203_13_fu_605_p2 <= std_logic_vector(signed(sext_ln1371_fu_575_p1) + signed(sext_ln101_2_fu_572_p1));
    add_ln203_14_fu_709_p2 <= std_logic_vector(signed(sext_ln1371_1_fu_665_p1) + signed(select_ln101_14_fu_639_p3));
    add_ln203_15_fu_813_p2 <= std_logic_vector(signed(sext_ln1371_2_fu_769_p1) + signed(select_ln101_17_fu_743_p3));
    add_ln203_16_fu_917_p2 <= std_logic_vector(signed(sext_ln1371_3_fu_873_p1) + signed(select_ln101_20_fu_847_p3));
    add_ln203_17_fu_1014_p2 <= std_logic_vector(signed(sext_ln1371_4_fu_985_p1) + signed(select_ln101_23_reg_1234));
    add_ln203_18_fu_1083_p2 <= std_logic_vector(unsigned(select_ln1371_fu_1043_p3) + unsigned(select_ln101_25_fu_1019_p3));
    add_ln203_19_fu_1155_p2 <= std_logic_vector(unsigned(select_ln1371_1_fu_1113_p3) + unsigned(select_ln101_27_fu_1089_p3));
    add_ln203_1_fu_292_p2 <= std_logic_vector(unsigned(zext_ln1333_fu_248_p1) + unsigned(sext_ln101_fu_222_p1));
    add_ln203_2_fu_382_p2 <= std_logic_vector(signed(sext_ln101_3_fu_370_p1) + signed(zext_ln101_fu_342_p1));
    add_ln203_3_fu_400_p2 <= std_logic_vector(unsigned(zext_ln1333_1_fu_356_p1) + unsigned(select_ln101_5_fu_326_p3));
    add_ln203_4_fu_486_p2 <= std_logic_vector(signed(sext_ln101_4_fu_474_p1) + signed(select_ln101_9_fu_442_p3));
    add_ln203_5_fu_589_p2 <= std_logic_vector(signed(sext_ln101_5_fu_578_p1) + signed(select_ln101_12_reg_1208));
    add_ln203_6_fu_691_p2 <= std_logic_vector(signed(sext_ln101_6_fu_679_p1) + signed(select_ln101_15_fu_647_p3));
    add_ln203_7_fu_795_p2 <= std_logic_vector(signed(sext_ln101_7_fu_783_p1) + signed(select_ln101_18_fu_751_p3));
    add_ln203_8_fu_899_p2 <= std_logic_vector(signed(sext_ln101_8_fu_887_p1) + signed(select_ln101_21_fu_855_p3));
    add_ln203_9_fu_999_p2 <= std_logic_vector(signed(sext_ln101_9_fu_988_p1) + signed(select_ln101_24_reg_1240));
    add_ln203_fu_274_p2 <= std_logic_vector(signed(sext_ln101_1_fu_262_p1) + signed(zext_ln1333_2_fu_234_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= sext_ln101_10_fu_1177_p1;
    ap_return_1 <= select_ln101_29_fu_1161_p3;
    lshr_ln_fu_238_p4 <= select_ln101_3_fu_226_p3(8 downto 2);
    select_ln101_10_fu_518_p3 <= 
        ap_const_lv12_3E when (tmp_13_fu_510_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_11_fu_526_p3 <= 
        sub_ln203_4_fu_492_p2 when (tmp_12_fu_478_p3(0) = '1') else 
        add_ln203_12_fu_504_p2;
    select_ln101_12_fu_534_p3 <= 
        add_ln203_4_fu_486_p2 when (tmp_12_fu_478_p3(0) = '1') else 
        sub_ln203_12_fu_498_p2;
    select_ln101_13_fu_619_p3 <= 
        ap_const_lv12_1E when (tmp_17_fu_611_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_14_fu_639_p3 <= 
        sub_ln203_5_fu_594_p2 when (tmp_16_fu_581_p3(0) = '1') else 
        add_ln203_13_fu_605_p2;
    select_ln101_15_fu_647_p3 <= 
        add_ln203_5_fu_589_p2 when (tmp_16_fu_581_p3(0) = '1') else 
        sub_ln203_13_fu_600_p2;
    select_ln101_16_fu_723_p3 <= 
        ap_const_lv12_E when (tmp_21_fu_715_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_17_fu_743_p3 <= 
        sub_ln203_6_fu_697_p2 when (tmp_20_fu_683_p3(0) = '1') else 
        add_ln203_14_fu_709_p2;
    select_ln101_18_fu_751_p3 <= 
        add_ln203_6_fu_691_p2 when (tmp_20_fu_683_p3(0) = '1') else 
        sub_ln203_14_fu_703_p2;
    select_ln101_19_fu_827_p3 <= 
        ap_const_lv12_6 when (tmp_25_fu_819_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_1_fu_194_p3 <= 
        ap_const_lv12_1DA when (tmp_2_fu_186_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_20_fu_847_p3 <= 
        sub_ln203_7_fu_801_p2 when (tmp_24_fu_787_p3(0) = '1') else 
        add_ln203_15_fu_813_p2;
    select_ln101_21_fu_855_p3 <= 
        add_ln203_7_fu_795_p2 when (tmp_24_fu_787_p3(0) = '1') else 
        sub_ln203_15_fu_807_p2;
    select_ln101_22_fu_967_p3 <= 
        ap_const_lv12_2 when (tmp_29_reg_1229(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_23_fu_931_p3 <= 
        sub_ln203_8_fu_905_p2 when (tmp_28_fu_891_p3(0) = '1') else 
        add_ln203_16_fu_917_p2;
    select_ln101_24_fu_939_p3 <= 
        add_ln203_8_fu_899_p2 when (tmp_28_fu_891_p3(0) = '1') else 
        sub_ln203_16_fu_911_p2;
    select_ln101_25_fu_1019_p3 <= 
        sub_ln203_9_fu_1004_p2 when (tmp_32_fu_991_p3(0) = '1') else 
        add_ln203_17_fu_1014_p2;
    select_ln101_26_fu_1027_p3 <= 
        add_ln203_9_fu_999_p2 when (tmp_32_fu_991_p3(0) = '1') else 
        sub_ln203_17_fu_1009_p2;
    select_ln101_27_fu_1089_p3 <= 
        sub_ln203_10_fu_1071_p2 when (tmp_32_fu_991_p3(0) = '1') else 
        add_ln203_18_fu_1083_p2;
    select_ln101_28_fu_1097_p3 <= 
        add_ln203_10_fu_1065_p2 when (tmp_32_fu_991_p3(0) = '1') else 
        sub_ln203_18_fu_1077_p2;
    select_ln101_29_fu_1161_p3 <= 
        sub_ln203_11_fu_1143_p2 when (tmp_32_fu_991_p3(0) = '1') else 
        add_ln203_19_fu_1155_p2;
    select_ln101_2_fu_214_p3 <= 
        select_ln203_1_fu_162_p3 when (tmp_1_fu_146_p3(0) = '1') else 
        select_ln203_3_fu_178_p3;
    select_ln101_30_fu_1169_p3 <= 
        add_ln203_11_fu_1137_p2 when (tmp_32_fu_991_p3(0) = '1') else 
        sub_ln203_19_fu_1149_p2;
    select_ln101_3_fu_226_p3 <= 
        select_ln203_fu_154_p3 when (tmp_1_fu_146_p3(0) = '1') else 
        select_ln203_2_fu_170_p3;
    select_ln101_4_fu_306_p3 <= 
        ap_const_lv12_FA when (tmp_5_fu_298_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_5_fu_326_p3 <= 
        sub_ln203_fu_280_p2 when (tmp_4_fu_266_p3(0) = '1') else 
        add_ln203_1_fu_292_p2;
    select_ln101_6_fu_334_p3 <= 
        add_ln203_fu_274_p2 when (tmp_4_fu_266_p3(0) = '1') else 
        sub_ln203_1_fu_286_p2;
    select_ln101_7_fu_414_p3 <= 
        ap_const_lv12_7E when (tmp_9_fu_406_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln101_8_fu_434_p3 <= 
        sub_ln203_2_fu_388_p2 when (tmp_8_fu_374_p3(0) = '1') else 
        add_ln203_3_fu_400_p2;
    select_ln101_9_fu_442_p3 <= 
        add_ln203_2_fu_382_p2 when (tmp_8_fu_374_p3(0) = '1') else 
        sub_ln203_3_fu_394_p2;
    select_ln101_fu_132_p3 <= 
        ap_const_lv12_192 when (tmp_fu_124_p3(0) = '1') else 
        ap_const_lv12_E6E;
    select_ln1371_1_fu_1113_p3 <= 
        ap_const_lv12_FFF when (tmp_35_fu_1105_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln1371_2_fu_1129_p3 <= 
        ap_const_lv11_7FF when (tmp_36_fu_1121_p3(0) = '1') else 
        ap_const_lv11_0;
    select_ln1371_fu_1043_p3 <= 
        ap_const_lv12_FFF when (tmp_33_fu_1035_p3(0) = '1') else 
        ap_const_lv12_0;
    select_ln203_1_fu_162_p3 <= 
        ap_const_lv10_22F when (tmp_fu_124_p3(0) = '1') else 
        ap_const_lv10_9B;
    select_ln203_2_fu_170_p3 <= 
        ap_const_lv9_1D1 when (tmp_fu_124_p3(0) = '1') else 
        ap_const_lv9_9B;
    select_ln203_3_fu_178_p3 <= 
        ap_const_lv10_365 when (tmp_fu_124_p3(0) = '1') else 
        ap_const_lv10_1D1;
    select_ln203_fu_154_p3 <= 
        ap_const_lv9_9B when (tmp_fu_124_p3(0) = '1') else 
        ap_const_lv9_1D1;
        sext_ln101_10_fu_1177_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln101_30_fu_1169_p3),12));

        sext_ln101_1_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_252_p4),10));

        sext_ln101_2_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln101_11_reg_1203),12));

        sext_ln101_3_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_360_p4),11));

        sext_ln101_4_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_11_fu_464_p4),11));

        sext_ln101_5_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_reg_1219),11));

        sext_ln101_6_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_669_p4),11));

        sext_ln101_7_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_23_fu_773_p4),11));

        sext_ln101_8_fu_887_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_877_p4),11));

        sext_ln101_9_fu_988_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_31_reg_1251),11));

        sext_ln101_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln101_2_fu_214_p3),11));

        sext_ln1333_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_450_p4),11));

        sext_ln1371_1_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_655_p4),12));

        sext_ln1371_2_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_fu_759_p4),12));

        sext_ln1371_3_fu_873_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_26_fu_863_p4),12));

        sext_ln1371_4_fu_985_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_30_reg_1246),12));

        sext_ln1371_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_reg_1214),12));

        sext_ln203_fu_1061_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_34_fu_1051_p4),11));

    sub_ln203_10_fu_1071_p2 <= std_logic_vector(unsigned(select_ln101_25_fu_1019_p3) - unsigned(select_ln1371_fu_1043_p3));
    sub_ln203_11_fu_1143_p2 <= std_logic_vector(unsigned(select_ln101_27_fu_1089_p3) - unsigned(select_ln1371_1_fu_1113_p3));
    sub_ln203_12_fu_498_p2 <= std_logic_vector(unsigned(select_ln101_9_fu_442_p3) - unsigned(sext_ln101_4_fu_474_p1));
    sub_ln203_13_fu_600_p2 <= std_logic_vector(unsigned(select_ln101_12_reg_1208) - unsigned(sext_ln101_5_fu_578_p1));
    sub_ln203_14_fu_703_p2 <= std_logic_vector(unsigned(select_ln101_15_fu_647_p3) - unsigned(sext_ln101_6_fu_679_p1));
    sub_ln203_15_fu_807_p2 <= std_logic_vector(unsigned(select_ln101_18_fu_751_p3) - unsigned(sext_ln101_7_fu_783_p1));
    sub_ln203_16_fu_911_p2 <= std_logic_vector(unsigned(select_ln101_21_fu_855_p3) - unsigned(sext_ln101_8_fu_887_p1));
    sub_ln203_17_fu_1009_p2 <= std_logic_vector(unsigned(select_ln101_24_reg_1240) - unsigned(sext_ln101_9_fu_988_p1));
    sub_ln203_18_fu_1077_p2 <= std_logic_vector(unsigned(select_ln101_26_fu_1027_p3) - unsigned(sext_ln203_fu_1061_p1));
    sub_ln203_19_fu_1149_p2 <= std_logic_vector(unsigned(select_ln101_28_fu_1097_p3) - unsigned(select_ln1371_2_fu_1129_p3));
    sub_ln203_1_fu_286_p2 <= std_logic_vector(unsigned(zext_ln1333_2_fu_234_p1) - unsigned(sext_ln101_1_fu_262_p1));
    sub_ln203_2_fu_388_p2 <= std_logic_vector(unsigned(select_ln101_5_fu_326_p3) - unsigned(zext_ln1333_1_fu_356_p1));
    sub_ln203_3_fu_394_p2 <= std_logic_vector(unsigned(zext_ln101_fu_342_p1) - unsigned(sext_ln101_3_fu_370_p1));
    sub_ln203_4_fu_492_p2 <= std_logic_vector(unsigned(select_ln101_8_fu_434_p3) - unsigned(sext_ln1333_fu_460_p1));
    sub_ln203_5_fu_594_p2 <= std_logic_vector(signed(sext_ln101_2_fu_572_p1) - signed(sext_ln1371_fu_575_p1));
    sub_ln203_6_fu_697_p2 <= std_logic_vector(unsigned(select_ln101_14_fu_639_p3) - unsigned(sext_ln1371_1_fu_665_p1));
    sub_ln203_7_fu_801_p2 <= std_logic_vector(unsigned(select_ln101_17_fu_743_p3) - unsigned(sext_ln1371_2_fu_769_p1));
    sub_ln203_8_fu_905_p2 <= std_logic_vector(unsigned(select_ln101_20_fu_847_p3) - unsigned(sext_ln1371_3_fu_873_p1));
    sub_ln203_9_fu_1004_p2 <= std_logic_vector(unsigned(select_ln101_23_reg_1234) - unsigned(sext_ln1371_4_fu_985_p1));
    sub_ln203_fu_280_p2 <= std_logic_vector(signed(sext_ln101_fu_222_p1) - signed(zext_ln1333_fu_248_p1));
    tmp_10_fu_450_p4 <= select_ln101_9_fu_442_p3(10 downto 4);
    tmp_11_fu_464_p4 <= select_ln101_8_fu_434_p3(10 downto 4);
    tmp_12_fu_478_p3 <= add_ln101_6_fu_428_p2(11 downto 11);
    tmp_13_fu_510_p3 <= add_ln101_6_fu_428_p2(11 downto 11);
    tmp_16_fu_581_p3 <= add_ln101_8_fu_567_p2(11 downto 11);
    tmp_17_fu_611_p3 <= add_ln101_8_fu_567_p2(11 downto 11);
    tmp_18_fu_655_p4 <= select_ln101_15_fu_647_p3(10 downto 6);
    tmp_19_fu_669_p4 <= select_ln101_14_fu_639_p3(11 downto 6);
    tmp_1_fu_146_p3 <= add_ln101_fu_140_p2(11 downto 11);
    tmp_20_fu_683_p3 <= add_ln101_10_fu_633_p2(11 downto 11);
    tmp_21_fu_715_p3 <= add_ln101_10_fu_633_p2(11 downto 11);
    tmp_22_fu_759_p4 <= select_ln101_18_fu_751_p3(10 downto 7);
    tmp_23_fu_773_p4 <= select_ln101_17_fu_743_p3(11 downto 7);
    tmp_24_fu_787_p3 <= add_ln101_12_fu_737_p2(11 downto 11);
    tmp_25_fu_819_p3 <= add_ln101_12_fu_737_p2(11 downto 11);
    tmp_26_fu_863_p4 <= select_ln101_21_fu_855_p3(10 downto 8);
    tmp_27_fu_877_p4 <= select_ln101_20_fu_847_p3(11 downto 8);
    tmp_28_fu_891_p3 <= add_ln101_14_fu_841_p2(11 downto 11);
    tmp_2_fu_186_p3 <= add_ln101_fu_140_p2(11 downto 11);
    tmp_32_fu_991_p3 <= add_ln101_16_fu_979_p2(11 downto 11);
    tmp_33_fu_1035_p3 <= select_ln101_26_fu_1027_p3(10 downto 10);
    tmp_34_fu_1051_p4 <= select_ln101_25_fu_1019_p3(11 downto 10);
    tmp_35_fu_1105_p3 <= select_ln101_28_fu_1097_p3(10 downto 10);
    tmp_36_fu_1121_p3 <= select_ln101_27_fu_1089_p3(11 downto 11);
    tmp_3_fu_252_p4 <= select_ln101_2_fu_214_p3(9 downto 2);
    tmp_4_fu_266_p3 <= add_ln101_2_fu_208_p2(11 downto 11);
    tmp_5_fu_298_p3 <= add_ln101_2_fu_208_p2(11 downto 11);
    tmp_6_fu_346_p4 <= select_ln101_6_fu_334_p3(9 downto 3);
    tmp_7_fu_360_p4 <= select_ln101_5_fu_326_p3(10 downto 3);
    tmp_8_fu_374_p3 <= add_ln101_4_fu_320_p2(11 downto 11);
    tmp_9_fu_406_p3 <= add_ln101_4_fu_320_p2(11 downto 11);
    tmp_fu_124_p1 <= z_V_read_int_reg;
    tmp_fu_124_p3 <= tmp_fu_124_p1(10 downto 10);
    z_V_read_cast_fu_120_p0 <= z_V_read_int_reg;
        z_V_read_cast_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(z_V_read_cast_fu_120_p0),12));

    zext_ln101_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln101_6_fu_334_p3),11));
    zext_ln1333_1_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_346_p4),11));
    zext_ln1333_2_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln101_3_fu_226_p3),10));
    zext_ln1333_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_238_p4),11));
end behav;
