// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _generic_sincos_11_6_s_HH_
#define _generic_sincos_11_6_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cordic_circ_apfixed_13_3_0_s.h"
#include "myproject_mul_mul_11ns_19ns_29_1_0.h"
#include "myproject_mac_mulsub_6ns_14ns_18ns_20_1_0.h"

namespace ap_rtl {

struct generic_sincos_11_6_s : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<11> > in_V;
    sc_out< sc_lv<7> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    generic_sincos_11_6_s(sc_module_name name);
    SC_HAS_PROCESS(generic_sincos_11_6_s);

    ~generic_sincos_11_6_s();

    sc_trace_file* mVcdFile;

    cordic_circ_apfixed_13_3_0_s* grp_cordic_circ_apfixed_13_3_0_s_fu_64;
    myproject_mul_mul_11ns_19ns_29_1_0<1,1,11,19,29>* myproject_mul_mul_11ns_19ns_29_1_0_U2;
    myproject_mac_mulsub_6ns_14ns_18ns_20_1_0<1,1,6,14,18,20>* myproject_mac_mulsub_6ns_14ns_18ns_20_1_0_U3;
    sc_signal< sc_lv<1> > sign0_V_fu_69_p2;
    sc_signal< sc_lv<1> > sign0_V_reg_280;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > sign0_V_reg_280_pp0_iter1_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_280_pp0_iter2_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_280_pp0_iter3_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_280_pp0_iter4_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_280_pp0_iter5_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_280_pp0_iter6_reg;
    sc_signal< sc_lv<11> > p_Val2_s_fu_81_p3;
    sc_signal< sc_lv<11> > p_Val2_s_reg_285;
    sc_signal< sc_lv<6> > ret_V_reg_290;
    sc_signal< sc_lv<2> > k_V_reg_295;
    sc_signal< sc_lv<1> > icmp_ln879_fu_134_p2;
    sc_signal< sc_lv<1> > icmp_ln879_reg_302;
    sc_signal< sc_lv<1> > icmp_ln879_reg_302_pp0_iter2_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_302_pp0_iter3_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_302_pp0_iter4_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_302_pp0_iter5_reg;
    sc_signal< sc_lv<12> > z_V_1_fu_183_p3;
    sc_signal< sc_lv<12> > z_V_1_reg_307;
    sc_signal< sc_lv<1> > icmp_ln879_1_fu_191_p2;
    sc_signal< sc_lv<1> > icmp_ln879_1_reg_312;
    sc_signal< sc_lv<1> > icmp_ln879_1_reg_312_pp0_iter2_reg;
    sc_signal< sc_lv<1> > icmp_ln879_1_reg_312_pp0_iter3_reg;
    sc_signal< sc_lv<1> > icmp_ln879_1_reg_312_pp0_iter4_reg;
    sc_signal< sc_lv<1> > icmp_ln879_1_reg_312_pp0_iter5_reg;
    sc_signal< sc_lv<7> > p_Val2_54_fu_243_p3;
    sc_signal< sc_lv<7> > p_Val2_54_reg_318;
    sc_signal< sc_lv<13> > grp_cordic_circ_apfixed_13_3_0_s_fu_64_ap_return;
    sc_signal< sc_logic > grp_cordic_circ_apfixed_13_3_0_s_fu_64_ap_ce;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call24;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call24;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call24;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call24;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call24;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call24;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6_ignore_call24;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7_ignore_call24;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp34;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<11> > inabs_V_fu_75_p2;
    sc_signal< sc_lv<29> > r_V_46_fu_262_p2;
    sc_signal< sc_lv<18> > lhs_V_fu_114_p3;
    sc_signal< sc_lv<20> > grp_fu_270_p3;
    sc_signal< sc_lv<12> > p_Val2_51_fu_125_p4;
    sc_signal< sc_lv<11> > trunc_ln708_s_fu_143_p4;
    sc_signal< sc_lv<13> > rhs_V_10_fu_139_p1;
    sc_signal< sc_lv<13> > ret_V_47_fu_156_p2;
    sc_signal< sc_lv<1> > icmp_ln251_fu_172_p2;
    sc_signal< sc_lv<1> > or_ln251_fu_177_p2;
    sc_signal< sc_lv<12> > trunc_ln708_16_fu_162_p4;
    sc_signal< sc_lv<12> > z_V_fu_152_p1;
    sc_signal< sc_lv<14> > zext_ln703_fu_206_p1;
    sc_signal< sc_lv<14> > sub_ln1253_fu_210_p2;
    sc_signal< sc_lv<7> > trunc_ln_fu_196_p4;
    sc_signal< sc_lv<7> > trunc_ln708_17_fu_216_p4;
    sc_signal< sc_lv<1> > xor_ln879_fu_233_p2;
    sc_signal< sc_lv<1> > and_ln879_fu_238_p2;
    sc_signal< sc_lv<7> > select_ln879_fu_226_p3;
    sc_signal< sc_lv<7> > sub_ln703_fu_251_p2;
    sc_signal< sc_lv<11> > r_V_46_fu_262_p0;
    sc_signal< sc_lv<19> > r_V_46_fu_262_p1;
    sc_signal< sc_lv<6> > grp_fu_270_p0;
    sc_signal< sc_lv<14> > grp_fu_270_p1;
    sc_signal< sc_lv<18> > grp_fu_270_p2;
    sc_signal< sc_lv<7> > p_Val2_55_fu_256_p3;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<11> > in_V_int_reg;
    sc_signal< sc_lv<7> > ap_return_int_reg;
    sc_signal< sc_lv<19> > grp_fu_270_p00;
    sc_signal< sc_lv<20> > grp_fu_270_p20;
    sc_signal< sc_lv<29> > r_V_46_fu_262_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<13> ap_const_lv13_C90;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<29> ap_const_lv29_28BE6;
    static const sc_lv<19> ap_const_lv19_1921;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_and_ln879_fu_238_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp34();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call24();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call24();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call24();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call24();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call24();
    void thread_ap_block_state6_pp0_stage0_iter5();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call24();
    void thread_ap_block_state7_pp0_stage0_iter6();
    void thread_ap_block_state7_pp0_stage0_iter6_ignore_call24();
    void thread_ap_block_state8_pp0_stage0_iter7();
    void thread_ap_block_state8_pp0_stage0_iter7_ignore_call24();
    void thread_ap_return();
    void thread_grp_cordic_circ_apfixed_13_3_0_s_fu_64_ap_ce();
    void thread_grp_fu_270_p0();
    void thread_grp_fu_270_p00();
    void thread_grp_fu_270_p1();
    void thread_grp_fu_270_p2();
    void thread_grp_fu_270_p20();
    void thread_icmp_ln251_fu_172_p2();
    void thread_icmp_ln879_1_fu_191_p2();
    void thread_icmp_ln879_fu_134_p2();
    void thread_inabs_V_fu_75_p2();
    void thread_lhs_V_fu_114_p3();
    void thread_or_ln251_fu_177_p2();
    void thread_p_Val2_51_fu_125_p4();
    void thread_p_Val2_54_fu_243_p3();
    void thread_p_Val2_55_fu_256_p3();
    void thread_p_Val2_s_fu_81_p3();
    void thread_r_V_46_fu_262_p0();
    void thread_r_V_46_fu_262_p00();
    void thread_r_V_46_fu_262_p1();
    void thread_ret_V_47_fu_156_p2();
    void thread_rhs_V_10_fu_139_p1();
    void thread_select_ln879_fu_226_p3();
    void thread_sign0_V_fu_69_p2();
    void thread_sub_ln1253_fu_210_p2();
    void thread_sub_ln703_fu_251_p2();
    void thread_trunc_ln708_16_fu_162_p4();
    void thread_trunc_ln708_17_fu_216_p4();
    void thread_trunc_ln708_s_fu_143_p4();
    void thread_trunc_ln_fu_196_p4();
    void thread_xor_ln879_fu_233_p2();
    void thread_z_V_1_fu_183_p3();
    void thread_z_V_fu_152_p1();
    void thread_zext_ln703_fu_206_p1();
};

}

using namespace ap_rtl;

#endif
