// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.083000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=18,HLS_SYN_FF=825,HLS_SYN_LUT=2154,HLS_VERSION=2020_1}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V_ap_vld,
        x_V,
        y_0_V,
        y_0_V_ap_vld,
        y_1_V,
        y_1_V_ap_vld,
        y_2_V,
        y_2_V_ap_vld,
        y_3_V,
        y_3_V_ap_vld,
        y_4_V,
        y_4_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   x_V_ap_vld;
input  [111:0] x_V;
output  [6:0] y_0_V;
output   y_0_V_ap_vld;
output  [6:0] y_1_V;
output   y_1_V_ap_vld;
output  [6:0] y_2_V;
output   y_2_V_ap_vld;
output  [6:0] y_3_V;
output   y_3_V_ap_vld;
output  [6:0] y_4_V;
output   y_4_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_0_V_ap_vld;
reg y_1_V_ap_vld;
reg y_2_V_ap_vld;
reg y_3_V_ap_vld;
reg y_4_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    x_V_ap_vld_in_sig;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [111:0] x_V_preg;
reg   [111:0] x_V_in_sig;
reg    x_V_ap_vld_preg;
reg    x_V_blk_n;
wire    ap_block_pp0_stage0;
wire  signed [6:0] tmp_1_fu_189_p4;
reg  signed [6:0] tmp_1_reg_1509;
reg  signed [6:0] tmp_1_reg_1509_pp0_iter1_reg;
reg  signed [6:0] tmp_1_reg_1509_pp0_iter2_reg;
wire  signed [14:0] sext_ln1117_1_fu_199_p1;
reg  signed [14:0] sext_ln1117_1_reg_1524;
wire  signed [6:0] tmp_2_fu_203_p4;
reg  signed [6:0] tmp_2_reg_1529;
reg  signed [6:0] tmp_2_reg_1529_pp0_iter1_reg;
reg  signed [6:0] tmp_2_reg_1529_pp0_iter2_reg;
wire  signed [13:0] sext_ln1118_4_fu_243_p1;
reg  signed [13:0] sext_ln1118_4_reg_1542;
wire   [19:0] ret_V_fu_265_p2;
reg   [19:0] ret_V_reg_1547;
wire  signed [6:0] p_Val2_18_fu_271_p4;
reg  signed [6:0] p_Val2_18_reg_1552;
reg  signed [6:0] p_Val2_18_reg_1552_pp0_iter1_reg;
wire  signed [13:0] sext_ln1118_16_fu_281_p1;
reg  signed [13:0] sext_ln1118_16_reg_1567;
reg  signed [6:0] tmp_4_reg_1573;
reg  signed [6:0] tmp_4_reg_1573_pp0_iter1_reg;
reg  signed [6:0] tmp_5_reg_1584;
reg  signed [6:0] tmp_5_reg_1584_pp0_iter1_reg;
wire   [13:0] mul_ln1118_fu_305_p2;
reg  signed [13:0] mul_ln1118_reg_1597;
wire  signed [19:0] mul_ln1192_2_fu_1375_p2;
reg  signed [19:0] mul_ln1192_2_reg_1602;
wire  signed [8:0] r_V_20_fu_343_p3;
reg  signed [8:0] r_V_20_reg_1607;
wire  signed [9:0] r_V_57_fu_354_p2;
reg  signed [9:0] r_V_57_reg_1612;
wire  signed [7:0] r_V_4_fu_381_p3;
reg  signed [7:0] r_V_4_reg_1617;
wire  signed [14:0] r_V_58_fu_392_p2;
reg  signed [14:0] r_V_58_reg_1622;
wire  signed [21:0] grp_fu_1381_p3;
reg  signed [21:0] ret_V_2_reg_1627;
wire   [13:0] r_V_10_fu_405_p2;
reg  signed [13:0] r_V_10_reg_1632;
wire  signed [20:0] mul_ln728_1_fu_1389_p2;
reg  signed [20:0] mul_ln728_1_reg_1637;
wire  signed [19:0] mul_ln728_2_fu_1395_p2;
reg  signed [19:0] mul_ln728_2_reg_1642;
wire  signed [9:0] r_V_63_fu_464_p2;
reg  signed [9:0] r_V_63_reg_1647;
wire   [15:0] mul_ln728_3_fu_474_p2;
reg   [15:0] mul_ln728_3_reg_1652;
wire  signed [18:0] mul_ln728_4_fu_1401_p2;
reg  signed [18:0] mul_ln728_4_reg_1657;
wire  signed [18:0] mul_ln728_5_fu_1407_p2;
reg  signed [18:0] mul_ln728_5_reg_1662;
wire  signed [16:0] grp_fu_1413_p3;
reg  signed [16:0] mul_ln728_6_reg_1667;
wire  signed [16:0] grp_fu_1421_p3;
reg  signed [16:0] mul_ln728_7_reg_1672;
wire  signed [13:0] sext_ln1118_31_fu_509_p1;
reg  signed [13:0] sext_ln1118_31_reg_1677;
wire   [14:0] r_V_38_fu_515_p2;
reg  signed [14:0] r_V_38_reg_1682;
wire   [21:0] ret_V_13_fu_613_p2;
reg   [21:0] ret_V_13_reg_1687;
wire   [20:0] ret_V_17_fu_649_p2;
reg   [20:0] ret_V_17_reg_1692;
wire  signed [18:0] mul_ln728_12_fu_1437_p2;
reg  signed [18:0] mul_ln728_12_reg_1697;
wire  signed [18:0] mul_ln728_13_fu_1443_p2;
reg  signed [18:0] mul_ln728_13_reg_1702;
(* use_dsp48 = "no" *) wire   [21:0] sub_ln1192_fu_733_p2;
reg   [21:0] sub_ln1192_reg_1707;
wire  signed [8:0] r_V_2_fu_741_p3;
reg  signed [8:0] r_V_2_reg_1712;
reg   [6:0] trunc_ln708_1_reg_1717;
wire   [21:0] add_ln1192_7_fu_967_p2;
reg   [21:0] add_ln1192_7_reg_1722;
wire  signed [11:0] sext_ln1192_7_fu_973_p1;
reg  signed [11:0] sext_ln1192_7_reg_1727;
wire  signed [16:0] mul_ln728_10_fu_1494_p2;
reg  signed [16:0] mul_ln728_10_reg_1732;
wire   [13:0] r_V_67_fu_989_p2;
reg   [13:0] r_V_67_reg_1737;
reg   [6:0] trunc_ln708_3_reg_1742;
reg   [6:0] trunc_ln708_4_reg_1747;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire  signed [6:0] trunc_ln1117_fu_185_p1;
wire   [7:0] r_V_fu_213_p3;
wire  signed [6:0] r_V_55_fu_225_p0;
wire  signed [7:0] r_V_55_fu_225_p1;
wire   [14:0] r_V_55_fu_225_p2;
wire  signed [6:0] r_V_56_fu_247_p0;
wire  signed [13:0] sext_ln1116_1_fu_239_p1;
wire  signed [6:0] r_V_56_fu_247_p1;
wire   [13:0] r_V_56_fu_247_p2;
wire   [18:0] rhs_V_1_fu_253_p3;
wire  signed [19:0] sext_ln728_2_fu_261_p1;
wire   [19:0] rhs_V_fu_231_p3;
wire  signed [6:0] mul_ln1118_fu_305_p0;
wire  signed [6:0] mul_ln1118_fu_305_p1;
wire  signed [6:0] r_V_44_fu_311_p0;
wire  signed [6:0] r_V_44_fu_311_p1;
wire  signed [13:0] r_V_44_fu_311_p2;
wire  signed [9:0] sext_ln1118_8_fu_350_p1;
wire  signed [9:0] sext_ln1118_6_fu_340_p1;
wire   [19:0] rhs_V_2_fu_363_p3;
wire  signed [20:0] sext_ln703_fu_360_p1;
wire  signed [20:0] sext_ln728_3_fu_371_p1;
wire  signed [6:0] r_V_58_fu_392_p0;
wire  signed [7:0] r_V_58_fu_392_p1;
wire  signed [20:0] ret_V_1_fu_375_p2;
wire  signed [6:0] r_V_10_fu_405_p0;
wire  signed [13:0] sext_ln1117_fu_328_p1;
wire  signed [6:0] r_V_10_fu_405_p1;
wire  signed [6:0] r_V_22_fu_426_p0;
wire  signed [15:0] sext_ln1118_19_fu_416_p1;
wire  signed [8:0] r_V_22_fu_426_p1;
wire  signed [15:0] r_V_22_fu_426_p2;
wire  signed [7:0] r_V_26_fu_436_p3;
wire  signed [6:0] r_V_29_fu_451_p0;
wire  signed [7:0] r_V_29_fu_451_p1;
wire  signed [14:0] sext_ln1116_6_fu_447_p1;
wire  signed [14:0] r_V_29_fu_451_p2;
wire  signed [6:0] mul_ln728_3_fu_474_p0;
wire  signed [9:0] mul_ln728_3_fu_474_p1;
wire  signed [6:0] r_V_64_fu_480_p0;
wire  signed [6:0] r_V_64_fu_480_p1;
wire  signed [13:0] r_V_64_fu_480_p2;
wire  signed [9:0] r_V_45_fu_495_p3;
wire  signed [6:0] r_V_38_fu_515_p0;
wire  signed [7:0] r_V_38_fu_515_p1;
wire  signed [6:0] r_V_68_fu_531_p0;
wire  signed [9:0] r_V_68_fu_531_p1;
wire  signed [19:0] grp_fu_1429_p3;
wire   [16:0] r_V_68_fu_531_p2;
wire  signed [21:0] sext_ln703_3_fu_537_p1;
wire   [21:0] rhs_V_21_fu_540_p3;
wire  signed [18:0] rhs_V_22_fu_554_p3;
wire   [21:0] ret_V_10_fu_548_p2;
wire  signed [21:0] sext_ln728_16_fu_562_p1;
wire  signed [6:0] r_V_69_fu_572_p0;
wire  signed [7:0] r_V_69_fu_572_p1;
wire   [14:0] r_V_69_fu_572_p2;
wire   [19:0] rhs_V_23_fu_578_p3;
wire   [21:0] ret_V_11_fu_566_p2;
wire  signed [21:0] sext_ln728_17_fu_586_p1;
wire  signed [6:0] r_V_70_fu_596_p0;
wire  signed [6:0] r_V_70_fu_596_p1;
wire   [13:0] r_V_70_fu_596_p2;
wire  signed [18:0] rhs_V_24_fu_601_p3;
wire   [21:0] ret_V_12_fu_590_p2;
wire  signed [21:0] sext_ln728_18_fu_609_p1;
wire   [18:0] ret_V_15_fu_619_p2;
wire  signed [10:0] sext_ln1118_28_fu_502_p1;
wire  signed [10:0] sext_ln1118_5_fu_337_p1;
wire   [18:0] ret_V_16_fu_625_p2;
wire   [10:0] r_V_73_fu_631_p2;
wire  signed [20:0] sext_ln703_4_fu_637_p1;
wire   [20:0] rhs_V_30_fu_641_p3;
wire  signed [6:0] r_V_51_fu_655_p0;
wire  signed [6:0] r_V_51_fu_655_p1;
wire  signed [13:0] r_V_51_fu_655_p2;
wire  signed [6:0] r_V_53_fu_668_p0;
wire  signed [6:0] r_V_53_fu_668_p1;
wire  signed [13:0] r_V_53_fu_668_p2;
wire   [19:0] rhs_V_3_fu_696_p3;
wire  signed [21:0] sext_ln728_4_fu_703_p1;
wire   [9:0] r_V_71_fu_715_p3;
wire  signed [16:0] grp_fu_1458_p3;
wire  signed [21:0] grp_fu_1449_p3;
wire   [21:0] rhs_V_4_fu_726_p3;
wire   [25:0] rhs_V_8_fu_752_p3;
wire   [24:0] rhs_V_9_fu_766_p3;
wire  signed [26:0] sext_ln728_9_fu_773_p1;
wire  signed [26:0] sext_ln728_8_fu_759_p1;
wire   [25:0] rhs_V_10_fu_783_p3;
wire   [26:0] ret_V_6_fu_777_p2;
wire  signed [26:0] sext_ln1192_2_fu_790_p1;
wire   [23:0] rhs_V_11_fu_800_p3;
wire   [26:0] add_ln1192_3_fu_794_p2;
wire  signed [26:0] sext_ln1192_3_fu_807_p1;
wire   [23:0] rhs_V_12_fu_817_p3;
wire   [26:0] sub_ln1192_3_fu_811_p2;
wire  signed [26:0] sext_ln1192_4_fu_824_p1;
wire   [26:0] add_ln1192_4_fu_828_p2;
wire   [26:0] rhs_V_13_fu_834_p3;
wire   [26:0] add_ln1192_5_fu_841_p2;
wire   [26:0] rhs_V_14_fu_853_p3;
wire   [10:0] shl_ln1118_6_fu_866_p3;
wire  signed [11:0] sext_ln1118_30_fu_873_p1;
wire  signed [11:0] sext_ln1118_7_fu_684_p1;
wire   [11:0] r_V_65_fu_877_p2;
wire   [26:0] sub_ln1192_4_fu_860_p2;
wire   [26:0] rhs_V_15_fu_883_p3;
wire   [26:0] sub_ln1192_5_fu_891_p2;
wire   [26:0] ret_V_7_fu_897_p2;
wire  signed [8:0] shl_ln1118_7_fu_926_p3;
wire  signed [15:0] grp_fu_1476_p3;
wire   [20:0] rhs_V_17_fu_940_p3;
wire  signed [21:0] grp_fu_1467_p3;
wire  signed [21:0] sext_ln1192_5_fu_947_p1;
wire  signed [15:0] grp_fu_1485_p3;
wire   [20:0] rhs_V_18_fu_956_p3;
(* use_dsp48 = "no" *) wire   [21:0] sub_ln1192_7_fu_951_p2;
wire  signed [21:0] sext_ln1192_6_fu_963_p1;
wire  signed [6:0] r_V_42_fu_979_p1;
wire  signed [11:0] r_V_42_fu_979_p2;
wire  signed [6:0] r_V_67_fu_989_p0;
wire  signed [6:0] r_V_67_fu_989_p1;
wire  signed [6:0] mul_ln728_11_fu_997_p0;
wire  signed [9:0] mul_ln728_11_fu_997_p1;
wire   [15:0] mul_ln728_11_fu_997_p2;
wire   [20:0] rhs_V_25_fu_1003_p3;
wire  signed [21:0] sext_ln1192_11_fu_1011_p1;
wire   [19:0] rhs_V_26_fu_1020_p3;
wire   [21:0] add_ln1192_12_fu_1015_p2;
wire  signed [21:0] sext_ln1192_12_fu_1027_p1;
wire   [19:0] rhs_V_27_fu_1037_p3;
wire   [21:0] add_ln1192_13_fu_1031_p2;
wire  signed [21:0] sext_ln1192_13_fu_1044_p1;
wire  signed [9:0] r_V_72_fu_1054_p3;
wire   [19:0] rhs_V_28_fu_1065_p3;
wire   [21:0] sub_ln1192_11_fu_1048_p2;
wire  signed [21:0] sext_ln1192_14_fu_1072_p1;
wire   [16:0] rhs_V_29_fu_1082_p3;
wire   [21:0] sub_ln1192_12_fu_1076_p2;
wire  signed [21:0] sext_ln1192_15_fu_1089_p1;
wire   [21:0] sub_ln1192_13_fu_1093_p2;
wire   [21:0] ret_V_14_fu_1099_p2;
wire   [25:0] lhs_V_fu_1115_p3;
wire   [23:0] rhs_V_31_fu_1126_p3;
wire  signed [26:0] sext_ln703_5_fu_1122_p1;
wire  signed [26:0] sext_ln728_20_fu_1133_p1;
wire  signed [10:0] sext_ln1118_11_fu_722_p1;
wire  signed [10:0] sext_ln700_fu_687_p1;
wire   [10:0] r_V_74_fu_1143_p2;
wire   [25:0] rhs_V_32_fu_1149_p3;
wire   [26:0] ret_V_18_fu_1137_p2;
wire  signed [26:0] sext_ln728_21_fu_1157_p1;
wire   [23:0] rhs_V_33_fu_1167_p3;
wire   [26:0] ret_V_19_fu_1161_p2;
wire  signed [26:0] sext_ln728_22_fu_1174_p1;
wire  signed [16:0] grp_fu_1500_p3;
wire   [26:0] ret_V_20_fu_1178_p2;
wire   [26:0] rhs_V_34_fu_1184_p3;
wire   [26:0] sub_ln1192_14_fu_1191_p2;
wire   [26:0] ret_V_21_fu_1197_p2;
wire   [20:0] rhs_V_5_fu_1216_p3;
wire  signed [21:0] sext_ln1192_fu_1223_p1;
wire  signed [6:0] r_V_61_fu_1238_p0;
wire  signed [8:0] r_V_61_fu_1238_p1;
wire   [15:0] r_V_61_fu_1238_p2;
wire   [20:0] rhs_V_6_fu_1244_p3;
wire   [21:0] add_ln1192_fu_1227_p2;
wire  signed [21:0] sext_ln1192_1_fu_1252_p1;
wire   [10:0] shl_ln1118_5_fu_1262_p3;
wire  signed [11:0] sext_ln1118_12_fu_1232_p1;
wire  signed [11:0] sext_ln1118_15_fu_1269_p1;
wire   [11:0] r_V_62_fu_1273_p2;
wire   [21:0] add_ln1192_1_fu_1256_p2;
wire   [21:0] rhs_V_7_fu_1279_p3;
wire   [21:0] sub_ln1192_1_fu_1287_p2;
wire   [21:0] ret_V_5_fu_1293_p2;
wire   [21:0] rhs_V_19_fu_1310_p3;
wire   [18:0] rhs_V_20_fu_1322_p3;
wire   [21:0] sub_ln1192_8_fu_1317_p2;
wire  signed [21:0] sext_ln1192_8_fu_1329_p1;
wire  signed [6:0] mul_ln1192_fu_1339_p1;
wire   [11:0] mul_ln1192_fu_1339_p2;
wire   [21:0] sub_ln1192_9_fu_1333_p2;
wire   [21:0] shl_ln_fu_1344_p3;
wire   [21:0] add_ln1192_8_fu_1352_p2;
wire   [21:0] ret_V_8_fu_1358_p2;
wire  signed [13:0] mul_ln728_4_fu_1401_p1;
wire  signed [18:0] sext_ln1118_25_fu_485_p1;
wire  signed [13:0] mul_ln728_5_fu_1407_p1;
wire  signed [6:0] grp_fu_1413_p0;
wire  signed [9:0] grp_fu_1413_p1;
wire  signed [9:0] grp_fu_1421_p0;
wire  signed [6:0] mul_ln728_12_fu_1437_p0;
wire  signed [18:0] sext_ln1118_42_fu_665_p1;
wire  signed [6:0] mul_ln728_13_fu_1443_p0;
wire   [21:0] grp_fu_1449_p2;
wire  signed [9:0] grp_fu_1458_p0;
wire   [21:0] grp_fu_1467_p2;
wire  signed [6:0] grp_fu_1476_p2;
wire  signed [15:0] sext_ln1118_35_fu_937_p1;
wire  signed [6:0] grp_fu_1485_p2;
wire  signed [6:0] mul_ln728_10_fu_1494_p0;
wire  signed [16:0] sext_ln728_14_fu_913_p1;
wire  signed [6:0] grp_fu_1500_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 x_V_preg = 112'd0;
#0 x_V_ap_vld_preg = 1'b0;
end

myproject_mul_mul_7s_14s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 20 ))
myproject_mul_mul_7s_14s_20_1_1_U1(
    .din0(tmp_2_fu_203_p4),
    .din1(r_V_44_fu_311_p2),
    .dout(mul_ln1192_2_fu_1375_p2)
);

myproject_mac_muladd_7s_15s_21s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 22 ))
myproject_mac_muladd_7s_15s_21s_22_1_1_U2(
    .din0(tmp_2_reg_1529),
    .din1(r_V_58_fu_392_p2),
    .din2(ret_V_1_fu_375_p2),
    .dout(grp_fu_1381_p3)
);

myproject_mul_mul_7s_16s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_mul_mul_7s_16s_21_1_1_U3(
    .din0(tmp_1_reg_1509),
    .din1(r_V_22_fu_426_p2),
    .dout(mul_ln728_1_fu_1389_p2)
);

myproject_mul_mul_7s_15s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 20 ))
myproject_mul_mul_7s_15s_20_1_1_U4(
    .din0(tmp_4_reg_1573),
    .din1(r_V_29_fu_451_p2),
    .dout(mul_ln728_2_fu_1395_p2)
);

myproject_mul_mul_7s_14s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 19 ))
myproject_mul_mul_7s_14s_19_1_1_U5(
    .din0(tmp_1_reg_1509),
    .din1(mul_ln728_4_fu_1401_p1),
    .dout(mul_ln728_4_fu_1401_p2)
);

myproject_mul_mul_7s_14s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 19 ))
myproject_mul_mul_7s_14s_19_1_1_U6(
    .din0(tmp_4_reg_1573),
    .din1(mul_ln728_5_fu_1407_p1),
    .dout(mul_ln728_5_fu_1407_p2)
);

myproject_am_addmul_7s_10s_7s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
myproject_am_addmul_7s_10s_7s_17_1_1_U7(
    .din0(grp_fu_1413_p0),
    .din1(grp_fu_1413_p1),
    .din2(tmp_1_reg_1509),
    .dout(grp_fu_1413_p3)
);

myproject_am_submul_10s_8s_7s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
myproject_am_submul_10s_8s_7s_17_1_1_U8(
    .din0(grp_fu_1421_p0),
    .din1(r_V_26_fu_436_p3),
    .din2(tmp_4_reg_1573),
    .dout(grp_fu_1421_p3)
);

myproject_mac_mulsub_7s_14s_20s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
myproject_mac_mulsub_7s_14s_20s_20_1_1_U9(
    .din0(p_Val2_18_reg_1552),
    .din1(mul_ln1118_reg_1597),
    .din2(mul_ln1192_2_reg_1602),
    .dout(grp_fu_1429_p3)
);

myproject_mul_mul_7s_14s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 19 ))
myproject_mul_mul_7s_14s_19_1_1_U10(
    .din0(mul_ln728_12_fu_1437_p0),
    .din1(r_V_51_fu_655_p2),
    .dout(mul_ln728_12_fu_1437_p2)
);

myproject_mul_mul_7s_14s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 19 ))
myproject_mul_mul_7s_14s_19_1_1_U11(
    .din0(mul_ln728_13_fu_1443_p0),
    .din1(r_V_53_fu_668_p2),
    .dout(mul_ln728_13_fu_1443_p2)
);

myproject_mac_mulsub_7s_14s_22ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
myproject_mac_mulsub_7s_14s_22ns_22_1_1_U12(
    .din0(tmp_2_reg_1529_pp0_iter1_reg),
    .din1(r_V_10_reg_1632),
    .din2(grp_fu_1449_p2),
    .dout(grp_fu_1449_p3)
);

myproject_am_addmul_10s_8s_7s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
myproject_am_addmul_10s_8s_7s_17_1_1_U13(
    .din0(grp_fu_1458_p0),
    .din1(r_V_4_reg_1617),
    .din2(tmp_2_reg_1529_pp0_iter1_reg),
    .dout(grp_fu_1458_p3)
);

myproject_mac_mul_sub_7s_15s_22ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
myproject_mac_mul_sub_7s_15s_22ns_22_1_1_U14(
    .din0(tmp_4_reg_1573_pp0_iter1_reg),
    .din1(r_V_38_reg_1682),
    .din2(grp_fu_1467_p2),
    .dout(grp_fu_1467_p3)
);

myproject_am_submul_9s_7s_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
myproject_am_submul_9s_7s_7s_16_1_1_U15(
    .din0(shl_ln1118_7_fu_926_p3),
    .din1(tmp_1_reg_1509_pp0_iter1_reg),
    .din2(grp_fu_1476_p2),
    .dout(grp_fu_1476_p3)
);

myproject_am_submul_9s_7s_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
myproject_am_submul_9s_7s_7s_16_1_1_U16(
    .din0(r_V_2_fu_741_p3),
    .din1(tmp_2_reg_1529_pp0_iter1_reg),
    .din2(grp_fu_1485_p2),
    .dout(grp_fu_1485_p3)
);

myproject_mul_mul_7s_12s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 17 ))
myproject_mul_mul_7s_12s_17_1_1_U17(
    .din0(mul_ln728_10_fu_1494_p0),
    .din1(r_V_42_fu_979_p2),
    .dout(mul_ln728_10_fu_1494_p2)
);

myproject_am_submul_10s_7s_7s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
myproject_am_submul_10s_7s_7s_17_1_1_U18(
    .din0(r_V_72_fu_1054_p3),
    .din1(tmp_5_reg_1584_pp0_iter1_reg),
    .din2(grp_fu_1500_p2),
    .dout(grp_fu_1500_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_V_ap_vld_preg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_V_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (x_V_ap_vld == 1'b1))) begin
            x_V_ap_vld_preg <= x_V_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_V_preg <= 112'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (x_V_ap_vld == 1'b1))) begin
            x_V_preg <= x_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1192_7_reg_1722 <= add_ln1192_7_fu_967_p2;
        mul_ln728_10_reg_1732 <= mul_ln728_10_fu_1494_p2;
        r_V_2_reg_1712[8 : 2] <= r_V_2_fu_741_p3[8 : 2];
        r_V_67_reg_1737 <= r_V_67_fu_989_p2;
        sext_ln1192_7_reg_1727 <= sext_ln1192_7_fu_973_p1;
        sub_ln1192_reg_1707 <= sub_ln1192_fu_733_p2;
        tmp_1_reg_1509_pp0_iter2_reg <= tmp_1_reg_1509_pp0_iter1_reg;
        tmp_2_reg_1529_pp0_iter2_reg <= tmp_2_reg_1529_pp0_iter1_reg;
        trunc_ln708_1_reg_1717 <= {{ret_V_7_fu_897_p2[26:20]}};
        trunc_ln708_3_reg_1742 <= {{ret_V_14_fu_1099_p2[21:15]}};
        trunc_ln708_4_reg_1747 <= {{ret_V_21_fu_1197_p2[26:20]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln1118_reg_1597 <= mul_ln1118_fu_305_p2;
        mul_ln1192_2_reg_1602 <= mul_ln1192_2_fu_1375_p2;
        mul_ln728_12_reg_1697 <= mul_ln728_12_fu_1437_p2;
        mul_ln728_13_reg_1702 <= mul_ln728_13_fu_1443_p2;
        mul_ln728_1_reg_1637 <= mul_ln728_1_fu_1389_p2;
        mul_ln728_2_reg_1642 <= mul_ln728_2_fu_1395_p2;
        mul_ln728_3_reg_1652 <= mul_ln728_3_fu_474_p2;
        mul_ln728_4_reg_1657 <= mul_ln728_4_fu_1401_p2;
        mul_ln728_5_reg_1662 <= mul_ln728_5_fu_1407_p2;
        p_Val2_18_reg_1552 <= {{x_V_in_sig[104:98]}};
        p_Val2_18_reg_1552_pp0_iter1_reg <= p_Val2_18_reg_1552;
        r_V_10_reg_1632 <= r_V_10_fu_405_p2;
        r_V_20_reg_1607[8 : 2] <= r_V_20_fu_343_p3[8 : 2];
        r_V_38_reg_1682[14 : 1] <= r_V_38_fu_515_p2[14 : 1];
        r_V_4_reg_1617[7 : 1] <= r_V_4_fu_381_p3[7 : 1];
        r_V_57_reg_1612 <= r_V_57_fu_354_p2;
        r_V_58_reg_1622[14 : 1] <= r_V_58_fu_392_p2[14 : 1];
        r_V_63_reg_1647 <= r_V_63_fu_464_p2;
        ret_V_13_reg_1687 <= ret_V_13_fu_613_p2;
        ret_V_17_reg_1692[20 : 5] <= ret_V_17_fu_649_p2[20 : 5];
        ret_V_reg_1547[19 : 5] <= ret_V_fu_265_p2[19 : 5];
        sext_ln1117_1_reg_1524 <= sext_ln1117_1_fu_199_p1;
        sext_ln1118_16_reg_1567 <= sext_ln1118_16_fu_281_p1;
        sext_ln1118_31_reg_1677 <= sext_ln1118_31_fu_509_p1;
        sext_ln1118_4_reg_1542 <= sext_ln1118_4_fu_243_p1;
        tmp_1_reg_1509 <= {{x_V_in_sig[111:105]}};
        tmp_1_reg_1509_pp0_iter1_reg <= tmp_1_reg_1509;
        tmp_2_reg_1529 <= {{x_V_in_sig[20:14]}};
        tmp_2_reg_1529_pp0_iter1_reg <= tmp_2_reg_1529;
        tmp_4_reg_1573 <= {{x_V_in_sig[34:28]}};
        tmp_4_reg_1573_pp0_iter1_reg <= tmp_4_reg_1573;
        tmp_5_reg_1584 <= {{x_V_in_sig[27:21]}};
        tmp_5_reg_1584_pp0_iter1_reg <= tmp_5_reg_1584;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln728_6_reg_1667 <= grp_fu_1413_p3;
        mul_ln728_7_reg_1672 <= grp_fu_1421_p3;
        ret_V_2_reg_1627 <= grp_fu_1381_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((x_V_ap_vld == 1'b1)) begin
        x_V_ap_vld_in_sig = x_V_ap_vld;
    end else begin
        x_V_ap_vld_in_sig = x_V_ap_vld_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_V_blk_n = x_V_ap_vld;
    end else begin
        x_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((x_V_ap_vld == 1'b1)) begin
        x_V_in_sig = x_V;
    end else begin
        x_V_in_sig = x_V_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        y_0_V_ap_vld = 1'b1;
    end else begin
        y_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        y_1_V_ap_vld = 1'b1;
    end else begin
        y_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        y_2_V_ap_vld = 1'b1;
    end else begin
        y_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        y_3_V_ap_vld = 1'b1;
    end else begin
        y_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        y_4_V_ap_vld = 1'b1;
    end else begin
        y_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1192_12_fu_1015_p2 = ($signed(ret_V_13_reg_1687) + $signed(sext_ln1192_11_fu_1011_p1));

assign add_ln1192_13_fu_1031_p2 = ($signed(add_ln1192_12_fu_1015_p2) + $signed(sext_ln1192_12_fu_1027_p1));

assign add_ln1192_1_fu_1256_p2 = ($signed(add_ln1192_fu_1227_p2) + $signed(sext_ln1192_1_fu_1252_p1));

assign add_ln1192_3_fu_794_p2 = ($signed(ret_V_6_fu_777_p2) + $signed(sext_ln1192_2_fu_790_p1));

assign add_ln1192_4_fu_828_p2 = ($signed(sub_ln1192_3_fu_811_p2) + $signed(sext_ln1192_4_fu_824_p1));

assign add_ln1192_5_fu_841_p2 = (add_ln1192_4_fu_828_p2 + rhs_V_13_fu_834_p3);

assign add_ln1192_7_fu_967_p2 = ($signed(sub_ln1192_7_fu_951_p2) + $signed(sext_ln1192_6_fu_963_p1));

assign add_ln1192_8_fu_1352_p2 = (sub_ln1192_9_fu_1333_p2 + shl_ln_fu_1344_p3);

assign add_ln1192_fu_1227_p2 = ($signed(sub_ln1192_reg_1707) + $signed(sext_ln1192_fu_1223_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_fu_1413_p0 = sext_ln1118_5_fu_337_p1;

assign grp_fu_1413_p1 = sext_ln1118_28_fu_502_p1;

assign grp_fu_1421_p0 = sext_ln1118_28_fu_502_p1;

assign grp_fu_1449_p2 = ($signed(ret_V_2_reg_1627) + $signed(sext_ln728_4_fu_703_p1));

assign grp_fu_1458_p0 = sext_ln1118_11_fu_722_p1;

assign grp_fu_1467_p2 = {{p_Val2_18_reg_1552_pp0_iter1_reg}, {15'd0}};

assign grp_fu_1476_p2 = sext_ln1118_35_fu_937_p1;

assign grp_fu_1485_p2 = sext_ln1118_35_fu_937_p1;

assign grp_fu_1500_p2 = sext_ln728_14_fu_913_p1;

assign lhs_V_fu_1115_p3 = {{ret_V_17_reg_1692}, {5'd0}};

assign mul_ln1118_fu_305_p0 = sext_ln1118_16_fu_281_p1;

assign mul_ln1118_fu_305_p1 = sext_ln1116_1_fu_239_p1;

assign mul_ln1118_fu_305_p2 = ($signed(mul_ln1118_fu_305_p0) * $signed(mul_ln1118_fu_305_p1));

assign mul_ln1192_fu_1339_p1 = sext_ln1192_7_reg_1727;

assign mul_ln1192_fu_1339_p2 = ($signed({{1'b0}, {12'd58}}) * $signed(mul_ln1192_fu_1339_p1));

assign mul_ln728_10_fu_1494_p0 = sext_ln728_14_fu_913_p1;

assign mul_ln728_11_fu_997_p0 = tmp_4_reg_1573_pp0_iter1_reg;

assign mul_ln728_11_fu_997_p1 = r_V_57_reg_1612;

assign mul_ln728_11_fu_997_p2 = ($signed(mul_ln728_11_fu_997_p0) * $signed(mul_ln728_11_fu_997_p1));

assign mul_ln728_12_fu_1437_p0 = sext_ln1118_42_fu_665_p1;

assign mul_ln728_13_fu_1443_p0 = sext_ln1118_42_fu_665_p1;

assign mul_ln728_3_fu_474_p0 = sext_ln1118_19_fu_416_p1;

assign mul_ln728_3_fu_474_p1 = r_V_63_fu_464_p2;

assign mul_ln728_3_fu_474_p2 = ($signed(mul_ln728_3_fu_474_p0) * $signed(mul_ln728_3_fu_474_p1));

assign mul_ln728_4_fu_1401_p1 = sext_ln1118_25_fu_485_p1;

assign mul_ln728_5_fu_1407_p1 = sext_ln1118_25_fu_485_p1;

assign p_Val2_18_fu_271_p4 = {{x_V_in_sig[104:98]}};

assign r_V_10_fu_405_p0 = sext_ln1117_fu_328_p1;

assign r_V_10_fu_405_p1 = sext_ln1118_4_reg_1542;

assign r_V_10_fu_405_p2 = ($signed(r_V_10_fu_405_p0) * $signed(r_V_10_fu_405_p1));

assign r_V_20_fu_343_p3 = {{p_Val2_18_reg_1552}, {2'd0}};

assign r_V_22_fu_426_p0 = sext_ln1118_19_fu_416_p1;

assign r_V_22_fu_426_p1 = r_V_20_fu_343_p3;

assign r_V_22_fu_426_p2 = ($signed(r_V_22_fu_426_p0) * $signed(r_V_22_fu_426_p1));

assign r_V_26_fu_436_p3 = {{p_Val2_18_reg_1552}, {1'd0}};

assign r_V_29_fu_451_p0 = p_Val2_18_reg_1552;

assign r_V_29_fu_451_p1 = sext_ln1116_6_fu_447_p1;

assign r_V_29_fu_451_p2 = ($signed(r_V_29_fu_451_p0) * $signed(r_V_29_fu_451_p1));

assign r_V_2_fu_741_p3 = {{tmp_2_reg_1529_pp0_iter1_reg}, {2'd0}};

assign r_V_38_fu_515_p0 = tmp_5_reg_1584;

assign r_V_38_fu_515_p1 = sext_ln1116_6_fu_447_p1;

assign r_V_38_fu_515_p2 = ($signed(r_V_38_fu_515_p0) * $signed(r_V_38_fu_515_p1));

assign r_V_42_fu_979_p1 = tmp_5_reg_1584_pp0_iter1_reg;

assign r_V_42_fu_979_p2 = ($signed({{1'b0}, {12'd11}}) * $signed(r_V_42_fu_979_p1));

assign r_V_44_fu_311_p0 = sext_ln1118_16_fu_281_p1;

assign r_V_44_fu_311_p1 = sext_ln1118_16_fu_281_p1;

assign r_V_44_fu_311_p2 = ($signed(r_V_44_fu_311_p0) * $signed(r_V_44_fu_311_p1));

assign r_V_45_fu_495_p3 = {{p_Val2_18_reg_1552}, {3'd0}};

assign r_V_4_fu_381_p3 = {{tmp_1_reg_1509}, {1'd0}};

assign r_V_51_fu_655_p0 = sext_ln1117_fu_328_p1;

assign r_V_51_fu_655_p1 = sext_ln1118_31_fu_509_p1;

assign r_V_51_fu_655_p2 = ($signed(r_V_51_fu_655_p0) * $signed(r_V_51_fu_655_p1));

assign r_V_53_fu_668_p0 = sext_ln1118_31_fu_509_p1;

assign r_V_53_fu_668_p1 = sext_ln1118_31_fu_509_p1;

assign r_V_53_fu_668_p2 = ($signed(r_V_53_fu_668_p0) * $signed(r_V_53_fu_668_p1));

assign r_V_55_fu_225_p0 = tmp_1_fu_189_p4;

assign r_V_55_fu_225_p1 = r_V_fu_213_p3;

assign r_V_55_fu_225_p2 = ($signed(r_V_55_fu_225_p0) * $signed(r_V_55_fu_225_p1));

assign r_V_56_fu_247_p0 = sext_ln1116_1_fu_239_p1;

assign r_V_56_fu_247_p1 = tmp_2_fu_203_p4;

assign r_V_56_fu_247_p2 = ($signed(r_V_56_fu_247_p0) * $signed(r_V_56_fu_247_p1));

assign r_V_57_fu_354_p2 = ($signed(sext_ln1118_8_fu_350_p1) - $signed(sext_ln1118_6_fu_340_p1));

assign r_V_58_fu_392_p0 = sext_ln1117_1_reg_1524;

assign r_V_58_fu_392_p1 = r_V_4_fu_381_p3;

assign r_V_58_fu_392_p2 = ($signed(r_V_58_fu_392_p0) * $signed(r_V_58_fu_392_p1));

assign r_V_61_fu_1238_p0 = tmp_2_reg_1529_pp0_iter2_reg;

assign r_V_61_fu_1238_p1 = r_V_2_reg_1712;

assign r_V_61_fu_1238_p2 = ($signed(r_V_61_fu_1238_p0) * $signed(r_V_61_fu_1238_p1));

assign r_V_62_fu_1273_p2 = ($signed(sext_ln1118_12_fu_1232_p1) + $signed(sext_ln1118_15_fu_1269_p1));

assign r_V_63_fu_464_p2 = ($signed(sext_ln1118_6_fu_340_p1) + $signed(sext_ln1118_8_fu_350_p1));

assign r_V_64_fu_480_p0 = sext_ln1117_fu_328_p1;

assign r_V_64_fu_480_p1 = sext_ln1118_16_reg_1567;

assign r_V_64_fu_480_p2 = ($signed(r_V_64_fu_480_p0) * $signed(r_V_64_fu_480_p1));

assign r_V_65_fu_877_p2 = ($signed(sext_ln1118_30_fu_873_p1) - $signed(sext_ln1118_7_fu_684_p1));

assign r_V_67_fu_989_p0 = sext_ln1118_31_reg_1677;

assign r_V_67_fu_989_p1 = tmp_4_reg_1573_pp0_iter1_reg;

assign r_V_67_fu_989_p2 = ($signed(r_V_67_fu_989_p0) * $signed(r_V_67_fu_989_p1));

assign r_V_68_fu_531_p0 = p_Val2_18_reg_1552;

assign r_V_68_fu_531_p1 = r_V_45_fu_495_p3;

assign r_V_68_fu_531_p2 = ($signed(r_V_68_fu_531_p0) * $signed(r_V_68_fu_531_p1));

assign r_V_69_fu_572_p0 = tmp_2_reg_1529;

assign r_V_69_fu_572_p1 = sext_ln1116_6_fu_447_p1;

assign r_V_69_fu_572_p2 = ($signed(r_V_69_fu_572_p0) * $signed(r_V_69_fu_572_p1));

assign r_V_70_fu_596_p0 = sext_ln1118_16_reg_1567;

assign r_V_70_fu_596_p1 = sext_ln1118_31_fu_509_p1;

assign r_V_70_fu_596_p2 = ($signed(r_V_70_fu_596_p0) * $signed(r_V_70_fu_596_p1));

assign r_V_71_fu_715_p3 = {{tmp_1_reg_1509_pp0_iter1_reg}, {3'd0}};

assign r_V_72_fu_1054_p3 = {{tmp_5_reg_1584_pp0_iter1_reg}, {3'd0}};

assign r_V_73_fu_631_p2 = ($signed(sext_ln1118_28_fu_502_p1) - $signed(sext_ln1118_5_fu_337_p1));

assign r_V_74_fu_1143_p2 = ($signed(sext_ln1118_11_fu_722_p1) - $signed(sext_ln700_fu_687_p1));

assign r_V_fu_213_p3 = {{trunc_ln1117_fu_185_p1}, {1'd0}};

assign ret_V_10_fu_548_p2 = ($signed(sext_ln703_3_fu_537_p1) - $signed(rhs_V_21_fu_540_p3));

assign ret_V_11_fu_566_p2 = ($signed(ret_V_10_fu_548_p2) + $signed(sext_ln728_16_fu_562_p1));

assign ret_V_12_fu_590_p2 = ($signed(ret_V_11_fu_566_p2) - $signed(sext_ln728_17_fu_586_p1));

assign ret_V_13_fu_613_p2 = ($signed(ret_V_12_fu_590_p2) + $signed(sext_ln728_18_fu_609_p1));

assign ret_V_14_fu_1099_p2 = ($signed(22'd3702784) + $signed(sub_ln1192_13_fu_1093_p2));

assign ret_V_15_fu_619_p2 = ($signed(19'd0) - $signed(rhs_V_22_fu_554_p3));

assign ret_V_16_fu_625_p2 = ($signed(ret_V_15_fu_619_p2) - $signed(rhs_V_24_fu_601_p3));

assign ret_V_17_fu_649_p2 = ($signed(sext_ln703_4_fu_637_p1) + $signed(rhs_V_30_fu_641_p3));

assign ret_V_18_fu_1137_p2 = ($signed(sext_ln703_5_fu_1122_p1) + $signed(sext_ln728_20_fu_1133_p1));

assign ret_V_19_fu_1161_p2 = ($signed(ret_V_18_fu_1137_p2) - $signed(sext_ln728_21_fu_1157_p1));

assign ret_V_1_fu_375_p2 = ($signed(sext_ln703_fu_360_p1) + $signed(sext_ln728_3_fu_371_p1));

assign ret_V_20_fu_1178_p2 = ($signed(ret_V_19_fu_1161_p2) + $signed(sext_ln728_22_fu_1174_p1));

assign ret_V_21_fu_1197_p2 = ($signed(27'd120586240) + $signed(sub_ln1192_14_fu_1191_p2));

assign ret_V_5_fu_1293_p2 = ($signed(22'd3473408) + $signed(sub_ln1192_1_fu_1287_p2));

assign ret_V_6_fu_777_p2 = ($signed(sext_ln728_9_fu_773_p1) - $signed(sext_ln728_8_fu_759_p1));

assign ret_V_7_fu_897_p2 = ($signed(27'd106954752) + $signed(sub_ln1192_5_fu_891_p2));

assign ret_V_8_fu_1358_p2 = ($signed(22'd3866624) + $signed(add_ln1192_8_fu_1352_p2));

assign ret_V_fu_265_p2 = ($signed(sext_ln728_2_fu_261_p1) - $signed(rhs_V_fu_231_p3));

assign rhs_V_10_fu_783_p3 = {{mul_ln728_3_reg_1652}, {10'd0}};

assign rhs_V_11_fu_800_p3 = {{mul_ln728_4_reg_1657}, {5'd0}};

assign rhs_V_12_fu_817_p3 = {{mul_ln728_5_reg_1662}, {5'd0}};

assign rhs_V_13_fu_834_p3 = {{mul_ln728_6_reg_1667}, {10'd0}};

assign rhs_V_14_fu_853_p3 = {{mul_ln728_7_reg_1672}, {10'd0}};

assign rhs_V_15_fu_883_p3 = {{r_V_65_fu_877_p2}, {15'd0}};

assign rhs_V_17_fu_940_p3 = {{grp_fu_1476_p3}, {5'd0}};

assign rhs_V_18_fu_956_p3 = {{grp_fu_1485_p3}, {5'd0}};

assign rhs_V_19_fu_1310_p3 = {{mul_ln728_10_reg_1732}, {5'd0}};

assign rhs_V_1_fu_253_p3 = {{r_V_56_fu_247_p2}, {5'd0}};

assign rhs_V_20_fu_1322_p3 = {{r_V_67_reg_1737}, {5'd0}};

assign rhs_V_21_fu_540_p3 = {{r_V_68_fu_531_p2}, {5'd0}};

assign rhs_V_22_fu_554_p3 = {{r_V_64_fu_480_p2}, {5'd0}};

assign rhs_V_23_fu_578_p3 = {{r_V_69_fu_572_p2}, {5'd0}};

assign rhs_V_24_fu_601_p3 = {{r_V_70_fu_596_p2}, {5'd0}};

assign rhs_V_25_fu_1003_p3 = {{mul_ln728_11_fu_997_p2}, {5'd0}};

assign rhs_V_26_fu_1020_p3 = {{r_V_63_reg_1647}, {10'd0}};

assign rhs_V_27_fu_1037_p3 = {{tmp_1_reg_1509_pp0_iter1_reg}, {13'd0}};

assign rhs_V_28_fu_1065_p3 = {{tmp_5_reg_1584_pp0_iter1_reg}, {13'd0}};

assign rhs_V_29_fu_1082_p3 = {{tmp_4_reg_1573_pp0_iter1_reg}, {10'd0}};

assign rhs_V_2_fu_363_p3 = {{r_V_57_fu_354_p2}, {10'd0}};

assign rhs_V_30_fu_641_p3 = {{r_V_73_fu_631_p2}, {10'd0}};

assign rhs_V_31_fu_1126_p3 = {{mul_ln728_12_reg_1697}, {5'd0}};

assign rhs_V_32_fu_1149_p3 = {{r_V_74_fu_1143_p2}, {15'd0}};

assign rhs_V_33_fu_1167_p3 = {{mul_ln728_13_reg_1702}, {5'd0}};

assign rhs_V_34_fu_1184_p3 = {{grp_fu_1500_p3}, {10'd0}};

assign rhs_V_3_fu_696_p3 = {{r_V_58_reg_1622}, {5'd0}};

assign rhs_V_4_fu_726_p3 = {{grp_fu_1458_p3}, {5'd0}};

assign rhs_V_5_fu_1216_p3 = {{tmp_1_reg_1509_pp0_iter2_reg}, {14'd0}};

assign rhs_V_6_fu_1244_p3 = {{r_V_61_fu_1238_p2}, {5'd0}};

assign rhs_V_7_fu_1279_p3 = {{r_V_62_fu_1273_p2}, {10'd0}};

assign rhs_V_8_fu_752_p3 = {{mul_ln728_1_reg_1637}, {5'd0}};

assign rhs_V_9_fu_766_p3 = {{mul_ln728_2_reg_1642}, {5'd0}};

assign rhs_V_fu_231_p3 = {{r_V_55_fu_225_p2}, {5'd0}};

assign sext_ln1116_1_fu_239_p1 = trunc_ln1117_fu_185_p1;

assign sext_ln1116_6_fu_447_p1 = r_V_26_fu_436_p3;

assign sext_ln1117_1_fu_199_p1 = tmp_1_fu_189_p4;

assign sext_ln1117_fu_328_p1 = tmp_1_reg_1509;

assign sext_ln1118_11_fu_722_p1 = $signed(r_V_71_fu_715_p3);

assign sext_ln1118_12_fu_1232_p1 = tmp_2_reg_1529_pp0_iter2_reg;

assign sext_ln1118_15_fu_1269_p1 = $signed(shl_ln1118_5_fu_1262_p3);

assign sext_ln1118_16_fu_281_p1 = p_Val2_18_fu_271_p4;

assign sext_ln1118_19_fu_416_p1 = p_Val2_18_reg_1552;

assign sext_ln1118_25_fu_485_p1 = r_V_64_fu_480_p2;

assign sext_ln1118_28_fu_502_p1 = r_V_45_fu_495_p3;

assign sext_ln1118_30_fu_873_p1 = $signed(shl_ln1118_6_fu_866_p3);

assign sext_ln1118_31_fu_509_p1 = tmp_5_reg_1584;

assign sext_ln1118_35_fu_937_p1 = tmp_5_reg_1584_pp0_iter1_reg;

assign sext_ln1118_42_fu_665_p1 = tmp_5_reg_1584;

assign sext_ln1118_4_fu_243_p1 = tmp_2_fu_203_p4;

assign sext_ln1118_5_fu_337_p1 = p_Val2_18_reg_1552;

assign sext_ln1118_6_fu_340_p1 = p_Val2_18_reg_1552;

assign sext_ln1118_7_fu_684_p1 = r_V_20_reg_1607;

assign sext_ln1118_8_fu_350_p1 = r_V_20_fu_343_p3;

assign sext_ln1192_11_fu_1011_p1 = $signed(rhs_V_25_fu_1003_p3);

assign sext_ln1192_12_fu_1027_p1 = $signed(rhs_V_26_fu_1020_p3);

assign sext_ln1192_13_fu_1044_p1 = $signed(rhs_V_27_fu_1037_p3);

assign sext_ln1192_14_fu_1072_p1 = $signed(rhs_V_28_fu_1065_p3);

assign sext_ln1192_15_fu_1089_p1 = $signed(rhs_V_29_fu_1082_p3);

assign sext_ln1192_1_fu_1252_p1 = $signed(rhs_V_6_fu_1244_p3);

assign sext_ln1192_2_fu_790_p1 = $signed(rhs_V_10_fu_783_p3);

assign sext_ln1192_3_fu_807_p1 = $signed(rhs_V_11_fu_800_p3);

assign sext_ln1192_4_fu_824_p1 = $signed(rhs_V_12_fu_817_p3);

assign sext_ln1192_5_fu_947_p1 = $signed(rhs_V_17_fu_940_p3);

assign sext_ln1192_6_fu_963_p1 = $signed(rhs_V_18_fu_956_p3);

assign sext_ln1192_7_fu_973_p1 = tmp_5_reg_1584_pp0_iter1_reg;

assign sext_ln1192_8_fu_1329_p1 = $signed(rhs_V_20_fu_1322_p3);

assign sext_ln1192_fu_1223_p1 = $signed(rhs_V_5_fu_1216_p3);

assign sext_ln700_fu_687_p1 = tmp_1_reg_1509_pp0_iter1_reg;

assign sext_ln703_3_fu_537_p1 = grp_fu_1429_p3;

assign sext_ln703_4_fu_637_p1 = $signed(ret_V_16_fu_625_p2);

assign sext_ln703_5_fu_1122_p1 = $signed(lhs_V_fu_1115_p3);

assign sext_ln703_fu_360_p1 = $signed(ret_V_reg_1547);

assign sext_ln728_14_fu_913_p1 = tmp_5_reg_1584_pp0_iter1_reg;

assign sext_ln728_16_fu_562_p1 = rhs_V_22_fu_554_p3;

assign sext_ln728_17_fu_586_p1 = $signed(rhs_V_23_fu_578_p3);

assign sext_ln728_18_fu_609_p1 = rhs_V_24_fu_601_p3;

assign sext_ln728_20_fu_1133_p1 = $signed(rhs_V_31_fu_1126_p3);

assign sext_ln728_21_fu_1157_p1 = $signed(rhs_V_32_fu_1149_p3);

assign sext_ln728_22_fu_1174_p1 = $signed(rhs_V_33_fu_1167_p3);

assign sext_ln728_2_fu_261_p1 = $signed(rhs_V_1_fu_253_p3);

assign sext_ln728_3_fu_371_p1 = $signed(rhs_V_2_fu_363_p3);

assign sext_ln728_4_fu_703_p1 = $signed(rhs_V_3_fu_696_p3);

assign sext_ln728_8_fu_759_p1 = $signed(rhs_V_8_fu_752_p3);

assign sext_ln728_9_fu_773_p1 = $signed(rhs_V_9_fu_766_p3);

assign shl_ln1118_5_fu_1262_p3 = {{tmp_2_reg_1529_pp0_iter2_reg}, {4'd0}};

assign shl_ln1118_6_fu_866_p3 = {{p_Val2_18_reg_1552_pp0_iter1_reg}, {4'd0}};

assign shl_ln1118_7_fu_926_p3 = {{tmp_1_reg_1509_pp0_iter1_reg}, {2'd0}};

assign shl_ln_fu_1344_p3 = {{mul_ln1192_fu_1339_p2}, {10'd0}};

assign sub_ln1192_11_fu_1048_p2 = ($signed(add_ln1192_13_fu_1031_p2) - $signed(sext_ln1192_13_fu_1044_p1));

assign sub_ln1192_12_fu_1076_p2 = ($signed(sub_ln1192_11_fu_1048_p2) - $signed(sext_ln1192_14_fu_1072_p1));

assign sub_ln1192_13_fu_1093_p2 = ($signed(sub_ln1192_12_fu_1076_p2) - $signed(sext_ln1192_15_fu_1089_p1));

assign sub_ln1192_14_fu_1191_p2 = (ret_V_20_fu_1178_p2 - rhs_V_34_fu_1184_p3);

assign sub_ln1192_1_fu_1287_p2 = (add_ln1192_1_fu_1256_p2 - rhs_V_7_fu_1279_p3);

assign sub_ln1192_3_fu_811_p2 = ($signed(add_ln1192_3_fu_794_p2) - $signed(sext_ln1192_3_fu_807_p1));

assign sub_ln1192_4_fu_860_p2 = (add_ln1192_5_fu_841_p2 - rhs_V_14_fu_853_p3);

assign sub_ln1192_5_fu_891_p2 = (sub_ln1192_4_fu_860_p2 - rhs_V_15_fu_883_p3);

assign sub_ln1192_7_fu_951_p2 = ($signed(grp_fu_1467_p3) - $signed(sext_ln1192_5_fu_947_p1));

assign sub_ln1192_8_fu_1317_p2 = (add_ln1192_7_reg_1722 - rhs_V_19_fu_1310_p3);

assign sub_ln1192_9_fu_1333_p2 = ($signed(sub_ln1192_8_fu_1317_p2) - $signed(sext_ln1192_8_fu_1329_p1));

assign sub_ln1192_fu_733_p2 = ($signed(grp_fu_1449_p3) - $signed(rhs_V_4_fu_726_p3));

assign tmp_1_fu_189_p4 = {{x_V_in_sig[111:105]}};

assign tmp_2_fu_203_p4 = {{x_V_in_sig[20:14]}};

assign trunc_ln1117_fu_185_p1 = x_V_in_sig[6:0];

assign y_0_V = {{ret_V_5_fu_1293_p2[21:15]}};

assign y_1_V = trunc_ln708_1_reg_1717;

assign y_2_V = {{ret_V_8_fu_1358_p2[21:15]}};

assign y_3_V = trunc_ln708_3_reg_1742;

assign y_4_V = trunc_ln708_4_reg_1747;

always @ (posedge ap_clk) begin
    ret_V_reg_1547[4:0] <= 5'b00000;
    r_V_20_reg_1607[1:0] <= 2'b00;
    r_V_4_reg_1617[0] <= 1'b0;
    r_V_58_reg_1622[0] <= 1'b0;
    r_V_38_reg_1682[0] <= 1'b0;
    ret_V_17_reg_1692[4:0] <= 5'b00000;
    r_V_2_reg_1712[1:0] <= 2'b00;
end

endmodule //myproject
