-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_V : IN STD_LOGIC_VECTOR (47 downto 0);
    x_V_ap_vld : IN STD_LOGIC;
    y_0_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    y_0_V_ap_vld : OUT STD_LOGIC;
    y_1_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    y_1_V_ap_vld : OUT STD_LOGIC;
    y_2_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    y_2_V_ap_vld : OUT STD_LOGIC;
    y_3_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    y_3_V_ap_vld : OUT STD_LOGIC;
    y_4_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    y_4_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.677625,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=50,HLS_SYN_LUT=365,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_180 : STD_LOGIC_VECTOR (8 downto 0) := "110000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal x_V_preg : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal x_V_in_sig : STD_LOGIC_VECTOR (47 downto 0);
    signal x_V_ap_vld_preg : STD_LOGIC := '0';
    signal x_V_ap_vld_in_sig : STD_LOGIC;
    signal x_V_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal tmp_1_fu_144_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_134_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_fu_172_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln1116_fu_168_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_V_fu_172_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_fu_172_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal rhs_V_fu_178_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_fu_186_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_1_fu_196_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln703_fu_192_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln728_fu_204_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal rhs_V_2_fu_214_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_1_fu_208_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1192_fu_222_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1192_fu_226_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_2_fu_232_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_6_fu_158_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_1_fu_253_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_1_fu_253_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln1116_1_fu_249_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_V_1_fu_253_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal rhs_V_10_fu_259_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal rhs_V_4_fu_271_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1192_1_fu_267_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1192_2_fu_279_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1192_1_fu_283_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln708_4_fu_289_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_306_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_2_fu_330_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln700_fu_316_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_V_2_fu_330_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_2_fu_330_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal rhs_V_5_fu_336_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln1192_2_fu_320_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1192_3_fu_344_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1118_fu_326_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_V_3_fu_354_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal rhs_V_6_fu_360_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln1192_3_fu_348_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1192_4_fu_368_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1192_fu_372_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_3_fu_378_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_4_fu_395_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_4_fu_395_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_4_fu_395_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal rhs_V_7_fu_401_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_8_fu_415_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_V_4_fu_409_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln728_1_fu_423_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_5_fu_427_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_9_fu_437_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln1192_5_fu_433_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1192_6_fu_445_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1192_4_fu_449_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_6_fu_455_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    x_V_ap_vld_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                x_V_ap_vld_preg <= ap_const_logic_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    x_V_ap_vld_preg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (x_V_ap_vld = ap_const_logic_1))) then 
                    x_V_ap_vld_preg <= x_V_ap_vld;
                end if; 
            end if;
        end if;
    end process;


    x_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                x_V_preg <= ap_const_lv48_0;
            else
                if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (x_V_ap_vld = ap_const_logic_1))) then 
                    x_V_preg <= x_V;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1192_fu_372_p2 <= std_logic_vector(unsigned(sub_ln1192_3_fu_348_p2) + unsigned(sext_ln1192_4_fu_368_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(ap_start, x_V_ap_vld_in_sig)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_6_fu_158_p4 <= x_V_in_sig(44 downto 42);
    r_V_1_fu_253_p0 <= sext_ln1116_fu_168_p1(3 - 1 downto 0);
    r_V_1_fu_253_p1 <= sext_ln1116_1_fu_249_p1(3 - 1 downto 0);
    r_V_1_fu_253_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_1_fu_253_p0) * signed(r_V_1_fu_253_p1))), 6));
    r_V_2_fu_330_p0 <= sext_ln700_fu_316_p1(3 - 1 downto 0);
    r_V_2_fu_330_p1 <= sext_ln700_fu_316_p1(3 - 1 downto 0);
    r_V_2_fu_330_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_2_fu_330_p0) * signed(r_V_2_fu_330_p1))), 6));
    r_V_3_fu_354_p2 <= std_logic_vector(unsigned(ap_const_lv4_0) - unsigned(sext_ln1118_fu_326_p1));
    r_V_4_fu_395_p0 <= sext_ln1116_1_fu_249_p1(3 - 1 downto 0);
    r_V_4_fu_395_p1 <= sext_ln1116_1_fu_249_p1(3 - 1 downto 0);
    r_V_4_fu_395_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_4_fu_395_p0) * signed(r_V_4_fu_395_p1))), 6));
    r_V_fu_172_p0 <= sext_ln1116_fu_168_p1(3 - 1 downto 0);
    r_V_fu_172_p1 <= tmp_1_fu_144_p4;
    r_V_fu_172_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_fu_172_p0) * signed(r_V_fu_172_p1))), 6));
    ret_V_1_fu_208_p2 <= std_logic_vector(signed(sext_ln703_fu_192_p1) + signed(sext_ln728_fu_204_p1));
    ret_V_2_fu_232_p2 <= std_logic_vector(unsigned(sub_ln1192_fu_226_p2) + unsigned(ap_const_lv9_140));
    ret_V_3_fu_378_p2 <= std_logic_vector(unsigned(add_ln1192_fu_372_p2) + unsigned(ap_const_lv9_180));
    ret_V_4_fu_409_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(rhs_V_7_fu_401_p3));
    ret_V_5_fu_427_p2 <= std_logic_vector(unsigned(ret_V_4_fu_409_p2) - unsigned(sext_ln728_1_fu_423_p1));
    ret_V_6_fu_455_p2 <= std_logic_vector(unsigned(sub_ln1192_4_fu_449_p2) + unsigned(ap_const_lv9_180));
    ret_V_fu_186_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(rhs_V_fu_178_p3));
    rhs_V_10_fu_259_p3 <= (r_V_1_fu_253_p2 & ap_const_lv4_0);
    rhs_V_1_fu_196_p3 <= (tmp_fu_134_p4 & ap_const_lv5_0);
    rhs_V_2_fu_214_p3 <= (tmp_1_fu_144_p4 & ap_const_lv5_0);
    rhs_V_4_fu_271_p3 <= (p_Val2_6_fu_158_p4 & ap_const_lv6_0);
    rhs_V_5_fu_336_p3 <= (r_V_2_fu_330_p2 & ap_const_lv2_0);
    rhs_V_6_fu_360_p3 <= (r_V_3_fu_354_p2 & ap_const_lv4_0);
    rhs_V_7_fu_401_p3 <= (r_V_4_fu_395_p2 & ap_const_lv2_0);
    rhs_V_8_fu_415_p3 <= (tmp_fu_134_p4 & ap_const_lv4_0);
    rhs_V_9_fu_437_p3 <= (tmp_3_fu_306_p4 & ap_const_lv4_0);
    rhs_V_fu_178_p3 <= (r_V_fu_172_p2 & ap_const_lv2_0);
        sext_ln1116_1_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_6_fu_158_p4),6));

        sext_ln1116_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_134_p4),6));

        sext_ln1118_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_306_p4),4));

        sext_ln1192_1_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_10_fu_259_p3),11));

        sext_ln1192_2_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_4_fu_271_p3),11));

        sext_ln1192_3_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_5_fu_336_p3),9));

        sext_ln1192_4_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_6_fu_360_p3),9));

        sext_ln1192_5_fu_433_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_5_fu_427_p2),9));

        sext_ln1192_6_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_9_fu_437_p3),9));

        sext_ln1192_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_2_fu_214_p3),9));

        sext_ln700_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_306_p4),6));

        sext_ln703_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_fu_186_p2),9));

        sext_ln728_1_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_8_fu_415_p3),8));

        sext_ln728_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_1_fu_196_p3),9));

    sub_ln1192_1_fu_283_p2 <= std_logic_vector(signed(sext_ln1192_1_fu_267_p1) - signed(sext_ln1192_2_fu_279_p1));
    sub_ln1192_2_fu_320_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(rhs_V_4_fu_271_p3));
    sub_ln1192_3_fu_348_p2 <= std_logic_vector(unsigned(sub_ln1192_2_fu_320_p2) - unsigned(sext_ln1192_3_fu_344_p1));
    sub_ln1192_4_fu_449_p2 <= std_logic_vector(signed(sext_ln1192_5_fu_433_p1) - signed(sext_ln1192_6_fu_445_p1));
    sub_ln1192_fu_226_p2 <= std_logic_vector(unsigned(ret_V_1_fu_208_p2) - unsigned(sext_ln1192_fu_222_p1));
    tmp_1_fu_144_p4 <= x_V_in_sig(8 downto 6);
    tmp_3_fu_306_p4 <= x_V_in_sig(11 downto 9);
    tmp_fu_134_p4 <= x_V_in_sig(47 downto 45);
    trunc_ln708_4_fu_289_p4 <= sub_ln1192_1_fu_283_p2(10 downto 8);

    x_V_ap_vld_in_sig_assign_proc : process(x_V_ap_vld, x_V_ap_vld_preg)
    begin
        if ((x_V_ap_vld = ap_const_logic_1)) then 
            x_V_ap_vld_in_sig <= x_V_ap_vld;
        else 
            x_V_ap_vld_in_sig <= x_V_ap_vld_preg;
        end if; 
    end process;


    x_V_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_V_blk_n <= x_V_ap_vld;
        else 
            x_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    x_V_in_sig_assign_proc : process(x_V, x_V_preg, x_V_ap_vld)
    begin
        if ((x_V_ap_vld = ap_const_logic_1)) then 
            x_V_in_sig <= x_V;
        else 
            x_V_in_sig <= x_V_preg;
        end if; 
    end process;

    y_0_V <= ret_V_2_fu_232_p2(8 downto 6);

    y_0_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_0_V_ap_vld <= ap_const_logic_1;
        else 
            y_0_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y_1_V <= (trunc_ln708_4_fu_289_p4 xor ap_const_lv3_4);

    y_1_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_1_V_ap_vld <= ap_const_logic_1;
        else 
            y_1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y_2_V <= ret_V_3_fu_378_p2(8 downto 6);

    y_2_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_2_V_ap_vld <= ap_const_logic_1;
        else 
            y_2_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y_3_V <= ret_V_6_fu_455_p2(8 downto 6);

    y_3_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_3_V_ap_vld <= ap_const_logic_1;
        else 
            y_3_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y_4_V <= ap_const_lv3_6;

    y_4_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, x_V_ap_vld_in_sig)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_V_ap_vld_in_sig = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_4_V_ap_vld <= ap_const_logic_1;
        else 
            y_4_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
