// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module operator_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        n_V,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [11:0] n_V;
output  [6:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] sin_lut_samples_V_address0;
reg    sin_lut_samples_V_ce0;
wire   [6:0] sin_lut_samples_V_q0;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln57_fu_125_p1;
wire  signed [12:0] lhs_V_fu_45_p1;
wire   [12:0] ret_V_fu_49_p2;
wire   [2:0] tmp_1_fu_63_p4;
wire   [0:0] tmp_3_fu_79_p3;
wire   [10:0] tmp_2_fu_87_p4;
wire  signed [11:0] sext_ln55_fu_97_p1;
wire   [11:0] add_ln55_fu_101_p2;
wire   [0:0] tmp_fu_55_p3;
wire   [0:0] icmp_ln56_fu_73_p2;
wire   [0:0] or_ln55_fu_111_p2;
wire  signed [12:0] sext_ln55_1_fu_107_p1;
wire   [12:0] select_ln55_fu_117_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

operator_s_sin_lut_samples_V #(
    .DataWidth( 7 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sin_lut_samples_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sin_lut_samples_V_address0),
    .ce0(sin_lut_samples_V_ce0),
    .q0(sin_lut_samples_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sin_lut_samples_V_ce0 = 1'b1;
    end else begin
        sin_lut_samples_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_fu_101_p2 = ($signed(sext_ln55_fu_97_p1) + $signed(12'd1023));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = sin_lut_samples_V_q0;

assign icmp_ln56_fu_73_p2 = ((tmp_1_fu_63_p4 != 3'd0) ? 1'b1 : 1'b0);

assign lhs_V_fu_45_p1 = $signed(n_V);

assign or_ln55_fu_111_p2 = (tmp_fu_55_p3 | icmp_ln56_fu_73_p2);

assign ret_V_fu_49_p2 = ($signed(lhs_V_fu_45_p1) + $signed(13'd512));

assign select_ln55_fu_117_p3 = ((or_ln55_fu_111_p2[0:0] === 1'b1) ? sext_ln55_1_fu_107_p1 : ret_V_fu_49_p2);

assign sext_ln55_1_fu_107_p1 = $signed(add_ln55_fu_101_p2);

assign sext_ln55_fu_97_p1 = $signed(tmp_2_fu_87_p4);

assign sin_lut_samples_V_address0 = zext_ln57_fu_125_p1;

assign tmp_1_fu_63_p4 = {{ret_V_fu_49_p2[12:10]}};

assign tmp_2_fu_87_p4 = {{{tmp_3_fu_79_p3}, {9'd0}}, {tmp_3_fu_79_p3}};

assign tmp_3_fu_79_p3 = ret_V_fu_49_p2[32'd12];

assign tmp_fu_55_p3 = ret_V_fu_49_p2[32'd12];

assign zext_ln57_fu_125_p1 = select_ln55_fu_117_p3;

endmodule //operator_s
