Backend: SymbolicExpression
ClockPeriod: 5
Compiler: vivado
HLSConfig:
  Model:
    Precision: ap_fixed<8,3>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
NSymbols: 16
OutputDir: my-hls-test-nov7-8-3
OutputPredictions: null
Part: xcvu9p-flga2577-2-e
ProjectName: myproject
Stamp: f638F604
