// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.271200,HLS_SYN_LAT=6,HLS_SYN_TPT=1,HLS_SYN_MEM=17,HLS_SYN_DSP=45,HLS_SYN_FF=1795,HLS_SYN_LUT=3477,HLS_VERSION=2020_1}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V_ap_vld,
        x_V,
        y_0_V,
        y_0_V_ap_vld,
        y_1_V,
        y_1_V_ap_vld,
        y_2_V,
        y_2_V_ap_vld,
        y_3_V,
        y_3_V_ap_vld,
        y_4_V,
        y_4_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   x_V_ap_vld;
input  [223:0] x_V;
output  [13:0] y_0_V;
output   y_0_V_ap_vld;
output  [13:0] y_1_V;
output   y_1_V_ap_vld;
output  [13:0] y_2_V;
output   y_2_V_ap_vld;
output  [13:0] y_3_V;
output   y_3_V_ap_vld;
output  [13:0] y_4_V;
output   y_4_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_0_V_ap_vld;
reg y_1_V_ap_vld;
reg y_2_V_ap_vld;
reg y_3_V_ap_vld;
reg y_4_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    x_V_ap_vld_in_sig;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_11001;
reg   [223:0] x_V_preg;
reg   [223:0] x_V_in_sig;
reg    x_V_ap_vld_preg;
reg    x_V_blk_n;
wire    ap_block_pp0_stage0;
wire  signed [13:0] p_Val2_s_fu_402_p4;
reg  signed [13:0] p_Val2_s_reg_1509;
reg  signed [13:0] p_Val2_s_reg_1509_pp0_iter1_reg;
reg   [13:0] p_Val2_s_reg_1509_pp0_iter2_reg;
wire  signed [13:0] p_Val2_2_fu_412_p4;
reg  signed [13:0] p_Val2_2_reg_1516;
wire  signed [13:0] p_Val2_1_fu_426_p4;
reg  signed [13:0] p_Val2_1_reg_1524;
reg   [13:0] p_Val2_1_reg_1524_pp0_iter1_reg;
wire  signed [21:0] sext_ln727_fu_436_p1;
reg  signed [21:0] sext_ln727_reg_1532;
reg  signed [13:0] p_Val2_4_reg_1537;
reg  signed [13:0] p_Val2_4_reg_1537_pp0_iter1_reg;
reg  signed [13:0] p_Val2_4_reg_1537_pp0_iter2_reg;
reg  signed [13:0] p_Val2_4_reg_1537_pp0_iter3_reg;
reg  signed [13:0] p_Val2_5_reg_1543;
reg  signed [13:0] p_Val2_5_reg_1543_pp0_iter1_reg;
wire  signed [21:0] sext_ln728_1_fu_460_p1;
reg  signed [21:0] sext_ln728_1_reg_1557;
reg  signed [21:0] sext_ln728_1_reg_1557_pp0_iter1_reg;
reg  signed [21:0] sext_ln728_1_reg_1557_pp0_iter2_reg;
wire  signed [21:0] mul_ln1192_6_fu_1323_p2;
reg  signed [21:0] mul_ln1192_6_reg_1563;
reg   [12:0] tmp_7_reg_1568;
reg   [13:0] trunc_ln708_7_reg_1573;
wire  signed [14:0] lhs_V_5_fu_493_p1;
reg  signed [14:0] lhs_V_5_reg_1578;
reg  signed [14:0] lhs_V_5_reg_1578_pp0_iter1_reg;
wire  signed [22:0] grp_fu_1330_p4;
reg  signed [22:0] ret_V_17_reg_1583;
wire  signed [27:0] r_V_12_fu_1340_p2;
reg  signed [27:0] r_V_12_reg_1588;
wire  signed [21:0] grp_fu_1346_p3;
reg  signed [21:0] ret_V_27_reg_1593;
reg   [13:0] trunc_ln_reg_1598;
wire  signed [27:0] r_V_4_fu_1363_p2;
reg  signed [27:0] r_V_4_reg_1603;
wire  signed [21:0] mul_ln1192_2_fu_1369_p2;
reg  signed [21:0] mul_ln1192_2_reg_1608;
reg   [13:0] trunc_ln708_4_reg_1613;
reg   [13:0] trunc_ln708_5_reg_1618;
wire  signed [45:0] mul_ln1118_fu_586_p2;
reg  signed [45:0] mul_ln1118_reg_1623;
wire   [13:0] add_ln703_fu_592_p2;
reg   [13:0] add_ln703_reg_1628;
reg   [13:0] trunc_ln708_s_reg_1633;
wire   [13:0] add_ln703_1_fu_635_p2;
reg   [13:0] add_ln703_1_reg_1638;
reg   [13:0] trunc_ln708_11_reg_1643;
wire   [43:0] mul_ln1118_5_fu_664_p2;
reg   [43:0] mul_ln1118_5_reg_1648;
reg   [13:0] trunc_ln708_13_reg_1653;
reg   [13:0] trunc_ln708_1_reg_1658;
reg   [13:0] trunc_ln708_2_reg_1663;
wire  signed [16:0] r_V_19_fu_728_p3;
reg  signed [16:0] r_V_19_reg_1668;
wire  signed [22:0] r_V_7_fu_1418_p2;
reg  signed [22:0] r_V_7_reg_1673;
wire   [19:0] add_ln1192_12_fu_793_p2;
reg   [19:0] add_ln1192_12_reg_1678;
wire  signed [20:0] mul_ln728_fu_1424_p2;
reg  signed [20:0] mul_ln728_reg_1683;
reg   [13:0] trunc_ln708_8_reg_1688;
wire   [14:0] ret_V_44_fu_817_p2;
reg   [14:0] ret_V_44_reg_1693;
reg   [12:0] trunc_ln708_10_reg_1698;
reg   [13:0] trunc_ln708_12_reg_1703;
wire   [13:0] add_ln703_2_fu_879_p2;
reg   [13:0] add_ln703_2_reg_1708;
wire   [32:0] ret_V_2_fu_907_p2;
reg   [32:0] ret_V_2_reg_1713;
wire  signed [17:0] grp_fu_1438_p3;
reg  signed [17:0] ret_V_4_reg_1718;
wire   [8:0] grp_operator_s_fu_297_ap_return;
reg   [8:0] p_Val2_s_24_reg_1723;
wire  signed [17:0] grp_fu_1446_p3;
reg  signed [17:0] ret_V_38_reg_1728;
reg  signed [17:0] ret_V_38_reg_1728_pp0_iter4_reg;
wire   [8:0] grp_operator_s_fu_311_ap_return;
reg  signed [8:0] p_6_reg_1733;
reg  signed [8:0] p_6_reg_1733_pp0_iter4_reg;
reg  signed [8:0] p_6_reg_1733_pp0_iter5_reg;
wire   [37:0] add_ln1192_17_fu_988_p2;
reg   [37:0] add_ln1192_17_reg_1738;
wire  signed [15:0] grp_fu_1460_p4;
reg  signed [15:0] ret_V_20_reg_1743;
wire  signed [23:0] grp_fu_1470_p3;
reg  signed [23:0] ret_V_45_reg_1748;
wire   [8:0] grp_operator_s_fu_332_ap_return;
reg   [8:0] p_Val2_27_reg_1753;
wire   [8:0] grp_operator_s_fu_339_ap_return;
reg   [8:0] p_2_reg_1758;
reg   [8:0] p_2_reg_1758_pp0_iter4_reg;
wire   [8:0] grp_operator_s_fu_346_ap_return;
reg   [8:0] p_Val2_38_reg_1763;
wire   [49:0] mul_ln700_fu_1023_p2;
reg   [49:0] mul_ln700_reg_1768;
wire   [14:0] add_ln1192_fu_1042_p2;
reg   [14:0] add_ln1192_reg_1773;
wire   [8:0] grp_operator_s_fu_360_ap_return;
reg   [8:0] p_Val2_10_reg_1778;
reg   [8:0] p_Val2_10_reg_1778_pp0_iter5_reg;
wire  signed [20:0] grp_fu_1478_p3;
reg  signed [20:0] r_V_5_reg_1783;
reg   [13:0] trunc_ln708_9_reg_1788;
reg   [13:0] trunc_ln708_9_reg_1788_pp0_iter5_reg;
reg   [13:0] trunc_ln708_6_reg_1793;
reg   [13:0] trunc_ln708_6_reg_1793_pp0_iter5_reg;
wire   [8:0] grp_operator_s_fu_381_ap_return;
reg   [8:0] p_Val2_32_reg_1798;
wire   [9:0] ret_V_49_fu_1153_p2;
reg   [9:0] ret_V_49_reg_1803;
wire   [8:0] grp_operator_s_fu_395_ap_return;
reg   [8:0] p_0_reg_1808;
reg   [8:0] p_0_reg_1808_pp0_iter5_reg;
wire   [53:0] mul_ln700_1_fu_1165_p2;
reg   [53:0] mul_ln700_1_reg_1813;
wire  signed [39:0] mul_ln1192_3_fu_1495_p2;
reg  signed [39:0] mul_ln1192_3_reg_1818;
wire  signed [30:0] grp_fu_1501_p3;
reg  signed [30:0] mul_ln1192_9_reg_1823;
reg    ap_block_pp0_stage0_subdone;
wire    grp_operator_s_fu_283_ap_start;
wire    grp_operator_s_fu_283_ap_done;
wire    grp_operator_s_fu_283_ap_idle;
wire    grp_operator_s_fu_283_ap_ready;
reg    grp_operator_s_fu_283_ap_ce;
wire   [8:0] grp_operator_s_fu_283_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call116;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call116;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call116;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call116;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call116;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call116;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call116;
reg    ap_block_pp0_stage0_11001_ignoreCallOp47;
wire    grp_operator_s_fu_290_ap_start;
wire    grp_operator_s_fu_290_ap_done;
wire    grp_operator_s_fu_290_ap_idle;
wire    grp_operator_s_fu_290_ap_ready;
reg    grp_operator_s_fu_290_ap_ce;
wire   [8:0] grp_operator_s_fu_290_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call30;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call30;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call30;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call30;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call30;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call30;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call30;
reg    ap_block_pp0_stage0_11001_ignoreCallOp69;
wire    grp_operator_s_fu_297_ap_start;
wire    grp_operator_s_fu_297_ap_done;
wire    grp_operator_s_fu_297_ap_idle;
wire    grp_operator_s_fu_297_ap_ready;
reg    grp_operator_s_fu_297_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call78;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call78;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call78;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call78;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call78;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call78;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call78;
reg    ap_block_pp0_stage0_11001_ignoreCallOp81;
wire    grp_operator_s_fu_304_ap_start;
wire    grp_operator_s_fu_304_ap_done;
wire    grp_operator_s_fu_304_ap_idle;
wire    grp_operator_s_fu_304_ap_ready;
reg    grp_operator_s_fu_304_ap_ce;
wire  signed [8:0] grp_operator_s_fu_304_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call91;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call91;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call91;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call91;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call91;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call91;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call91;
reg    ap_block_pp0_stage0_11001_ignoreCallOp85;
wire    grp_operator_s_fu_311_ap_start;
wire    grp_operator_s_fu_311_ap_done;
wire    grp_operator_s_fu_311_ap_idle;
wire    grp_operator_s_fu_311_ap_ready;
reg    grp_operator_s_fu_311_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call102;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call102;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call102;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call102;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call102;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call102;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call102;
reg    ap_block_pp0_stage0_11001_ignoreCallOp86;
wire    grp_operator_s_fu_318_ap_start;
wire    grp_operator_s_fu_318_ap_done;
wire    grp_operator_s_fu_318_ap_idle;
wire    grp_operator_s_fu_318_ap_ready;
reg    grp_operator_s_fu_318_ap_ce;
wire  signed [8:0] grp_operator_s_fu_318_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call159;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call159;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call159;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call159;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call159;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call159;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call159;
reg    ap_block_pp0_stage0_11001_ignoreCallOp103;
wire    grp_operator_s_fu_325_ap_start;
wire    grp_operator_s_fu_325_ap_done;
wire    grp_operator_s_fu_325_ap_idle;
wire    grp_operator_s_fu_325_ap_ready;
reg    grp_operator_s_fu_325_ap_ce;
wire  signed [8:0] grp_operator_s_fu_325_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call171;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call171;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call171;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call171;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call171;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call171;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call171;
reg    ap_block_pp0_stage0_11001_ignoreCallOp104;
wire    grp_operator_s_fu_332_ap_start;
wire    grp_operator_s_fu_332_ap_done;
wire    grp_operator_s_fu_332_ap_idle;
wire    grp_operator_s_fu_332_ap_ready;
reg    grp_operator_s_fu_332_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call185;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call185;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call185;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call185;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call185;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call185;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call185;
reg    ap_block_pp0_stage0_11001_ignoreCallOp107;
wire    grp_operator_s_fu_339_ap_start;
wire    grp_operator_s_fu_339_ap_done;
wire    grp_operator_s_fu_339_ap_idle;
wire    grp_operator_s_fu_339_ap_ready;
reg    grp_operator_s_fu_339_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call209;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call209;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call209;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call209;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call209;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call209;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call209;
reg    ap_block_pp0_stage0_11001_ignoreCallOp114;
wire    grp_operator_s_fu_346_ap_start;
wire    grp_operator_s_fu_346_ap_done;
wire    grp_operator_s_fu_346_ap_idle;
wire    grp_operator_s_fu_346_ap_ready;
reg    grp_operator_s_fu_346_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call227;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call227;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call227;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call227;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call227;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call227;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call227;
reg    ap_block_pp0_stage0_11001_ignoreCallOp118;
wire    grp_operator_s_fu_353_ap_start;
wire    grp_operator_s_fu_353_ap_done;
wire    grp_operator_s_fu_353_ap_idle;
wire    grp_operator_s_fu_353_ap_ready;
reg    grp_operator_s_fu_353_ap_ce;
wire   [8:0] grp_operator_s_fu_353_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call48;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call48;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call48;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call48;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call48;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call48;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call48;
reg    ap_block_pp0_stage0_11001_ignoreCallOp133;
wire    grp_operator_s_fu_360_ap_start;
wire    grp_operator_s_fu_360_ap_done;
wire    grp_operator_s_fu_360_ap_idle;
wire    grp_operator_s_fu_360_ap_ready;
reg    grp_operator_s_fu_360_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call62;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call62;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call62;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call62;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call62;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call62;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call62;
reg    ap_block_pp0_stage0_11001_ignoreCallOp134;
wire    grp_operator_s_fu_367_ap_start;
wire    grp_operator_s_fu_367_ap_done;
wire    grp_operator_s_fu_367_ap_idle;
wire    grp_operator_s_fu_367_ap_ready;
reg    grp_operator_s_fu_367_ap_ce;
wire  signed [8:0] grp_operator_s_fu_367_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call68;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call68;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call68;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call68;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call68;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call68;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call68;
reg    ap_block_pp0_stage0_11001_ignoreCallOp135;
wire    grp_operator_s_fu_374_ap_start;
wire    grp_operator_s_fu_374_ap_done;
wire    grp_operator_s_fu_374_ap_idle;
wire    grp_operator_s_fu_374_ap_ready;
reg    grp_operator_s_fu_374_ap_ce;
wire   [8:0] grp_operator_s_fu_374_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call149;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call149;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call149;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call149;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call149;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call149;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call149;
reg    ap_block_pp0_stage0_11001_ignoreCallOp158;
wire    grp_operator_s_fu_381_ap_start;
wire    grp_operator_s_fu_381_ap_done;
wire    grp_operator_s_fu_381_ap_idle;
wire    grp_operator_s_fu_381_ap_ready;
reg    grp_operator_s_fu_381_ap_ce;
wire   [13:0] grp_operator_s_fu_381_n_V;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call203;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call203;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call203;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call203;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call203;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call203;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call203;
reg    ap_block_pp0_stage0_11001_ignoreCallOp174;
wire    grp_operator_s_fu_388_ap_start;
wire    grp_operator_s_fu_388_ap_done;
wire    grp_operator_s_fu_388_ap_idle;
wire    grp_operator_s_fu_388_ap_ready;
reg    grp_operator_s_fu_388_ap_ce;
wire   [8:0] grp_operator_s_fu_388_ap_return;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call223;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call223;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call223;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call223;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call223;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call223;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call223;
reg    ap_block_pp0_stage0_11001_ignoreCallOp176;
wire    grp_operator_s_fu_395_ap_start;
wire    grp_operator_s_fu_395_ap_done;
wire    grp_operator_s_fu_395_ap_idle;
wire    grp_operator_s_fu_395_ap_ready;
reg    grp_operator_s_fu_395_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call238;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call238;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call238;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call238;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call238;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call238;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call238;
reg    ap_block_pp0_stage0_11001_ignoreCallOp178;
reg    grp_operator_s_fu_283_ap_start_reg;
reg    grp_operator_s_fu_290_ap_start_reg;
reg    grp_operator_s_fu_297_ap_start_reg;
reg    grp_operator_s_fu_304_ap_start_reg;
reg    grp_operator_s_fu_311_ap_start_reg;
reg    grp_operator_s_fu_318_ap_start_reg;
reg    grp_operator_s_fu_325_ap_start_reg;
reg    grp_operator_s_fu_332_ap_start_reg;
reg    grp_operator_s_fu_339_ap_start_reg;
reg    grp_operator_s_fu_346_ap_start_reg;
reg    grp_operator_s_fu_353_ap_start_reg;
reg    grp_operator_s_fu_360_ap_start_reg;
reg    grp_operator_s_fu_367_ap_start_reg;
reg    grp_operator_s_fu_374_ap_start_reg;
reg    grp_operator_s_fu_381_ap_start_reg;
reg    grp_operator_s_fu_388_ap_start_reg;
reg    grp_operator_s_fu_395_ap_start_reg;
reg    ap_block_pp0_stage0_01001;
(* use_dsp48 = "no" *) wire   [21:0] ret_V_40_fu_474_p2;
wire  signed [21:0] grp_fu_1354_p3;
wire   [21:0] lhs_V_3_fu_519_p3;
(* use_dsp48 = "no" *) wire   [21:0] add_ln1192_8_fu_526_p2;
wire   [21:0] rhs_V_1_fu_531_p3;
wire   [21:0] sub_ln1192_fu_538_p2;
wire   [21:0] ret_V_37_fu_544_p2;
wire   [21:0] trunc_ln1_fu_560_p3;
wire   [21:0] add_ln1192_7_fu_567_p2;
wire  signed [22:0] mul_ln1118_fu_586_p0;
wire  signed [45:0] sext_ln1118_11_fu_583_p1;
wire  signed [22:0] mul_ln1118_fu_586_p1;
wire  signed [21:0] mul_ln700_3_fu_1381_p2;
wire  signed [29:0] mul_ln700_2_fu_1374_p2;
wire   [29:0] shl_ln1_fu_600_p3;
wire  signed [21:0] mul_ln728_4_fu_1387_p2;
(* use_dsp48 = "no" *) wire   [29:0] add_ln700_fu_607_p2;
wire   [29:0] rhs_V_5_fu_612_p3;
wire   [29:0] ret_V_43_fu_619_p2;
wire   [21:0] lhs_V_1_fu_500_p3;
wire   [21:0] add_ln1192_30_fu_639_p2;
wire   [21:0] add_ln1192_28_fu_645_p2;
wire  signed [21:0] mul_ln1118_5_fu_664_p0;
wire  signed [43:0] sext_ln1118_16_fu_661_p1;
wire  signed [21:0] mul_ln1118_5_fu_664_p1;
wire  signed [21:0] grp_fu_1394_p3;
wire  signed [29:0] mul_ln1192_fu_1403_p2;
wire   [29:0] lhs_V_2_fu_685_p3;
(* use_dsp48 = "no" *) wire   [29:0] ret_V_33_fu_692_p2;
wire  signed [21:0] grp_fu_1410_p3;
(* use_dsp48 = "no" *) wire   [21:0] ret_V_35_fu_710_p2;
wire   [18:0] shl_ln_fu_742_p3;
wire  signed [19:0] sext_ln1118_5_fu_749_p1;
wire  signed [19:0] sext_ln1118_3_fu_735_p1;
wire   [13:0] tmp_9_fu_759_p3;
wire   [11:0] tmp_s_fu_771_p3;
wire  signed [14:0] sext_ln1118_6_fu_767_p1;
wire  signed [14:0] sext_ln1118_7_fu_779_p1;
wire   [14:0] r_V_21_fu_783_p2;
wire   [19:0] r_V_20_fu_753_p2;
wire  signed [19:0] sext_ln1118_8_fu_789_p1;
wire   [45:0] r_V_22_fu_799_p2;
wire  signed [14:0] rhs_V_6_fu_814_p1;
wire   [19:0] shl_ln1118_3_fu_822_p3;
wire   [15:0] shl_ln1118_4_fu_833_p3;
wire  signed [20:0] sext_ln1118_13_fu_829_p1;
wire  signed [20:0] sext_ln1118_14_fu_840_p1;
wire   [20:0] r_V_24_fu_844_p2;
wire  signed [43:0] r_V_27_fu_863_p1;
wire   [45:0] r_V_27_fu_863_p2;
wire  signed [29:0] grp_fu_1430_p2;
wire   [27:0] trunc_ln1193_fu_890_p1;
wire  signed [32:0] sext_ln1118_fu_887_p1;
wire   [32:0] p_shl_fu_893_p3;
wire   [32:0] sub_ln1193_1_fu_901_p2;
wire  signed [22:0] mul_ln1192_5_fu_930_p0;
wire  signed [19:0] mul_ln1192_5_fu_930_p1;
wire   [36:0] lhs_V_4_fu_936_p3;
wire  signed [37:0] sext_ln1192_11_fu_943_p1;
wire   [37:0] mul_ln1192_5_fu_930_p2;
wire  signed [21:0] mul_ln728_1_fu_1454_p2;
wire   [37:0] sub_ln1192_1_fu_947_p2;
wire   [37:0] rhs_V_2_fu_953_p3;
wire  signed [8:0] sext_ln1118_9_fu_966_p0;
wire  signed [8:0] mul_ln728_2_fu_970_p1;
wire  signed [17:0] sext_ln1118_9_fu_966_p1;
wire   [17:0] mul_ln728_2_fu_970_p2;
wire   [33:0] tmp_4_fu_976_p3;
wire   [37:0] add_ln1192_16_fu_960_p2;
wire  signed [37:0] rhs_V_3_fu_984_p1;
wire  signed [22:0] lhs_V_6_fu_1002_p3;
wire  signed [17:0] mul_ln700_fu_1023_p0;
wire  signed [32:0] mul_ln700_fu_1023_p1;
wire  signed [14:0] sext_ln1192_3_fu_1032_p1;
wire  signed [14:0] sext_ln1192_2_fu_1029_p1;
wire   [14:0] ret_V_34_fu_1036_p2;
wire  signed [9:0] sext_ln703_1_fu_1052_p1;
wire  signed [9:0] ret_V_11_fu_1055_p2;
wire  signed [8:0] mul_ln728_3_fu_1069_p1;
wire   [17:0] mul_ln728_3_fu_1069_p2;
wire   [33:0] tmp_5_fu_1075_p3;
wire  signed [37:0] rhs_V_4_fu_1083_p1;
wire   [37:0] add_ln1192_19_fu_1087_p2;
wire   [37:0] ret_V_42_fu_1092_p2;
wire   [16:0] tmp_1_fu_1108_p3;
wire  signed [23:0] sext_ln1192_18_fu_1115_p1;
(* use_dsp48 = "no" *) wire   [23:0] ret_V_46_fu_1119_p2;
wire  signed [23:0] ret_V_24_fu_1124_p2;
wire  signed [37:0] grp_fu_1486_p3;
wire  signed [9:0] sext_ln703_6_fu_1146_p1;
wire  signed [9:0] sext_ln703_7_fu_1150_p1;
wire  signed [14:0] mul_ln700_1_fu_1165_p0;
wire  signed [49:0] mul_ln700_1_fu_1165_p1;
(* use_dsp48 = "no" *) wire  signed [17:0] ret_V_13_fu_1171_p2;
wire  signed [9:0] sext_ln1253_fu_1183_p1;
wire  signed [8:0] r_V_26_fu_1195_p0;
wire  signed [17:0] sext_ln1116_3_fu_1192_p1;
wire  signed [8:0] r_V_26_fu_1195_p1;
wire  signed [17:0] r_V_26_fu_1195_p2;
wire   [9:0] r_V_25_fu_1186_p2;
wire  signed [17:0] tmp_6_fu_1205_p3;
wire  signed [10:0] sext_ln703_8_fu_1217_p1;
wire  signed [10:0] ret_V_30_fu_1220_p2;
wire   [48:0] tmp_3_fu_1230_p3;
wire  signed [53:0] rhs_V_fu_1237_p1;
wire   [53:0] ret_V_36_fu_1241_p2;
wire  signed [8:0] mul_ln1192_4_fu_1263_p0;
wire  signed [38:0] mul_ln1192_4_fu_1263_p1;
wire   [43:0] mul_ln1192_4_fu_1263_p2;
wire   [43:0] ret_V_39_fu_1269_p2;
wire   [11:0] tmp_fu_1275_p4;
wire  signed [8:0] mul_ln1192_10_fu_1296_p0;
wire  signed [29:0] mul_ln1192_10_fu_1296_p1;
wire   [36:0] mul_ln1192_10_fu_1296_p2;
wire   [36:0] ret_V_50_fu_1302_p2;
wire   [12:0] tmp_8_fu_1308_p4;
wire  signed [13:0] mul_ln1192_6_fu_1323_p0;
wire  signed [13:0] mul_ln1192_6_fu_1323_p1;
wire   [8:0] grp_fu_1330_p2;
wire   [17:0] grp_fu_1330_p3;
wire  signed [13:0] r_V_12_fu_1340_p0;
wire  signed [27:0] r_V_11_fu_489_p1;
wire  signed [13:0] r_V_12_fu_1340_p1;
wire   [8:0] grp_fu_1346_p0;
wire   [17:0] grp_fu_1346_p2;
wire  signed [8:0] grp_fu_1354_p0;
wire  signed [13:0] grp_fu_1354_p1;
wire  signed [21:0] sext_ln728_fu_497_p1;
wire  signed [13:0] r_V_4_fu_1363_p0;
wire  signed [27:0] r_V_3_fu_516_p1;
wire  signed [13:0] r_V_4_fu_1363_p1;
wire   [8:0] mul_ln1192_2_fu_1369_p0;
wire  signed [13:0] mul_ln1192_2_fu_1369_p1;
wire   [10:0] mul_ln700_2_fu_1374_p0;
wire   [10:0] mul_ln700_3_fu_1381_p0;
wire  signed [13:0] mul_ln700_3_fu_1381_p1;
wire   [11:0] mul_ln728_4_fu_1387_p0;
wire  signed [13:0] mul_ln728_4_fu_1387_p1;
wire  signed [13:0] grp_fu_1394_p0;
wire  signed [13:0] grp_fu_1394_p1;
wire  signed [16:0] grp_fu_1394_p2;
wire  signed [8:0] grp_fu_1410_p0;
wire   [8:0] r_V_7_fu_1418_p0;
wire  signed [7:0] mul_ln728_fu_1424_p0;
wire  signed [8:0] grp_fu_1430_p0;
wire  signed [8:0] grp_fu_1438_p0;
wire  signed [17:0] sext_ln1116_fu_913_p1;
wire  signed [8:0] grp_fu_1438_p1;
wire  signed [14:0] grp_fu_1438_p2;
wire   [8:0] mul_ln728_1_fu_1454_p0;
wire  signed [13:0] mul_ln728_1_fu_1454_p1;
wire   [6:0] grp_fu_1460_p2;
wire  signed [11:0] grp_fu_1460_p3;
wire  signed [8:0] grp_fu_1470_p0;
wire  signed [8:0] grp_fu_1470_p1;
wire  signed [9:0] grp_fu_1478_p0;
wire  signed [32:0] grp_fu_1486_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to5;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 x_V_preg = 224'd0;
#0 x_V_ap_vld_preg = 1'b0;
#0 grp_operator_s_fu_283_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_290_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_297_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_304_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_311_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_318_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_325_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_332_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_339_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_346_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_353_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_360_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_367_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_374_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_381_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_388_ap_start_reg = 1'b0;
#0 grp_operator_s_fu_395_ap_start_reg = 1'b0;
end

operator_s grp_operator_s_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_283_ap_start),
    .ap_done(grp_operator_s_fu_283_ap_done),
    .ap_idle(grp_operator_s_fu_283_ap_idle),
    .ap_ready(grp_operator_s_fu_283_ap_ready),
    .ap_ce(grp_operator_s_fu_283_ap_ce),
    .n_V(trunc_ln708_7_reg_1573),
    .ap_return(grp_operator_s_fu_283_ap_return)
);

operator_s grp_operator_s_fu_290(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_290_ap_start),
    .ap_done(grp_operator_s_fu_290_ap_done),
    .ap_idle(grp_operator_s_fu_290_ap_idle),
    .ap_ready(grp_operator_s_fu_290_ap_ready),
    .ap_ce(grp_operator_s_fu_290_ap_ce),
    .n_V(trunc_ln_reg_1598),
    .ap_return(grp_operator_s_fu_290_ap_return)
);

operator_s grp_operator_s_fu_297(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_297_ap_start),
    .ap_done(grp_operator_s_fu_297_ap_done),
    .ap_idle(grp_operator_s_fu_297_ap_idle),
    .ap_ready(grp_operator_s_fu_297_ap_ready),
    .ap_ce(grp_operator_s_fu_297_ap_ce),
    .n_V(trunc_ln708_4_reg_1613),
    .ap_return(grp_operator_s_fu_297_ap_return)
);

operator_s grp_operator_s_fu_304(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_304_ap_start),
    .ap_done(grp_operator_s_fu_304_ap_done),
    .ap_idle(grp_operator_s_fu_304_ap_idle),
    .ap_ready(grp_operator_s_fu_304_ap_ready),
    .ap_ce(grp_operator_s_fu_304_ap_ce),
    .n_V(trunc_ln708_5_reg_1618),
    .ap_return(grp_operator_s_fu_304_ap_return)
);

operator_s grp_operator_s_fu_311(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_311_ap_start),
    .ap_done(grp_operator_s_fu_311_ap_done),
    .ap_idle(grp_operator_s_fu_311_ap_idle),
    .ap_ready(grp_operator_s_fu_311_ap_ready),
    .ap_ce(grp_operator_s_fu_311_ap_ce),
    .n_V(p_Val2_1_reg_1524_pp0_iter1_reg),
    .ap_return(grp_operator_s_fu_311_ap_return)
);

operator_s grp_operator_s_fu_318(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_318_ap_start),
    .ap_done(grp_operator_s_fu_318_ap_done),
    .ap_idle(grp_operator_s_fu_318_ap_idle),
    .ap_ready(grp_operator_s_fu_318_ap_ready),
    .ap_ce(grp_operator_s_fu_318_ap_ce),
    .n_V(add_ln703_reg_1628),
    .ap_return(grp_operator_s_fu_318_ap_return)
);

operator_s grp_operator_s_fu_325(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_325_ap_start),
    .ap_done(grp_operator_s_fu_325_ap_done),
    .ap_idle(grp_operator_s_fu_325_ap_idle),
    .ap_ready(grp_operator_s_fu_325_ap_ready),
    .ap_ce(grp_operator_s_fu_325_ap_ce),
    .n_V(trunc_ln708_s_reg_1633),
    .ap_return(grp_operator_s_fu_325_ap_return)
);

operator_s grp_operator_s_fu_332(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_332_ap_start),
    .ap_done(grp_operator_s_fu_332_ap_done),
    .ap_idle(grp_operator_s_fu_332_ap_idle),
    .ap_ready(grp_operator_s_fu_332_ap_ready),
    .ap_ce(grp_operator_s_fu_332_ap_ce),
    .n_V(add_ln703_1_reg_1638),
    .ap_return(grp_operator_s_fu_332_ap_return)
);

operator_s grp_operator_s_fu_339(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_339_ap_start),
    .ap_done(grp_operator_s_fu_339_ap_done),
    .ap_idle(grp_operator_s_fu_339_ap_idle),
    .ap_ready(grp_operator_s_fu_339_ap_ready),
    .ap_ce(grp_operator_s_fu_339_ap_ce),
    .n_V(trunc_ln708_11_reg_1643),
    .ap_return(grp_operator_s_fu_339_ap_return)
);

operator_s grp_operator_s_fu_346(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_346_ap_start),
    .ap_done(grp_operator_s_fu_346_ap_done),
    .ap_idle(grp_operator_s_fu_346_ap_idle),
    .ap_ready(grp_operator_s_fu_346_ap_ready),
    .ap_ce(grp_operator_s_fu_346_ap_ce),
    .n_V(trunc_ln708_13_reg_1653),
    .ap_return(grp_operator_s_fu_346_ap_return)
);

operator_s grp_operator_s_fu_353(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_353_ap_start),
    .ap_done(grp_operator_s_fu_353_ap_done),
    .ap_idle(grp_operator_s_fu_353_ap_idle),
    .ap_ready(grp_operator_s_fu_353_ap_ready),
    .ap_ce(grp_operator_s_fu_353_ap_ce),
    .n_V(trunc_ln708_1_reg_1658),
    .ap_return(grp_operator_s_fu_353_ap_return)
);

operator_s grp_operator_s_fu_360(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_360_ap_start),
    .ap_done(grp_operator_s_fu_360_ap_done),
    .ap_idle(grp_operator_s_fu_360_ap_idle),
    .ap_ready(grp_operator_s_fu_360_ap_ready),
    .ap_ce(grp_operator_s_fu_360_ap_ce),
    .n_V(trunc_ln708_2_reg_1663),
    .ap_return(grp_operator_s_fu_360_ap_return)
);

operator_s grp_operator_s_fu_367(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_367_ap_start),
    .ap_done(grp_operator_s_fu_367_ap_done),
    .ap_idle(grp_operator_s_fu_367_ap_idle),
    .ap_ready(grp_operator_s_fu_367_ap_ready),
    .ap_ce(grp_operator_s_fu_367_ap_ce),
    .n_V(p_Val2_s_reg_1509_pp0_iter2_reg),
    .ap_return(grp_operator_s_fu_367_ap_return)
);

operator_s grp_operator_s_fu_374(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_374_ap_start),
    .ap_done(grp_operator_s_fu_374_ap_done),
    .ap_idle(grp_operator_s_fu_374_ap_idle),
    .ap_ready(grp_operator_s_fu_374_ap_ready),
    .ap_ce(grp_operator_s_fu_374_ap_ce),
    .n_V(trunc_ln708_8_reg_1688),
    .ap_return(grp_operator_s_fu_374_ap_return)
);

operator_s grp_operator_s_fu_381(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_381_ap_start),
    .ap_done(grp_operator_s_fu_381_ap_done),
    .ap_idle(grp_operator_s_fu_381_ap_idle),
    .ap_ready(grp_operator_s_fu_381_ap_ready),
    .ap_ce(grp_operator_s_fu_381_ap_ce),
    .n_V(grp_operator_s_fu_381_n_V),
    .ap_return(grp_operator_s_fu_381_ap_return)
);

operator_s grp_operator_s_fu_388(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_388_ap_start),
    .ap_done(grp_operator_s_fu_388_ap_done),
    .ap_idle(grp_operator_s_fu_388_ap_idle),
    .ap_ready(grp_operator_s_fu_388_ap_ready),
    .ap_ce(grp_operator_s_fu_388_ap_ce),
    .n_V(trunc_ln708_12_reg_1703),
    .ap_return(grp_operator_s_fu_388_ap_return)
);

operator_s grp_operator_s_fu_395(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_s_fu_395_ap_start),
    .ap_done(grp_operator_s_fu_395_ap_done),
    .ap_idle(grp_operator_s_fu_395_ap_idle),
    .ap_ready(grp_operator_s_fu_395_ap_ready),
    .ap_ce(grp_operator_s_fu_395_ap_ce),
    .n_V(add_ln703_2_reg_1708),
    .ap_return(grp_operator_s_fu_395_ap_return)
);

myproject_mul_mul_14s_14s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_14s_14s_22_1_1_U3(
    .din0(mul_ln1192_6_fu_1323_p0),
    .din1(mul_ln1192_6_fu_1323_p1),
    .dout(mul_ln1192_6_fu_1323_p2)
);

myproject_ama_submuladd_14s_14s_9ns_18ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 9 ),
    .din3_WIDTH( 18 ),
    .dout_WIDTH( 23 ))
myproject_ama_submuladd_14s_14s_9ns_18ns_23_1_1_U4(
    .din0(p_Val2_1_fu_426_p4),
    .din1(p_Val2_2_fu_412_p4),
    .din2(grp_fu_1330_p2),
    .din3(grp_fu_1330_p3),
    .dout(grp_fu_1330_p4)
);

myproject_mul_mul_14s_14s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
myproject_mul_mul_14s_14s_28_1_1_U5(
    .din0(r_V_12_fu_1340_p0),
    .din1(r_V_12_fu_1340_p1),
    .dout(r_V_12_fu_1340_p2)
);

myproject_mac_muladd_9ns_14s_18ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 22 ))
myproject_mac_muladd_9ns_14s_18ns_22_1_1_U6(
    .din0(grp_fu_1346_p0),
    .din1(p_Val2_1_fu_426_p4),
    .din2(grp_fu_1346_p2),
    .dout(grp_fu_1346_p3)
);

myproject_mac_muladd_9s_14s_22ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
myproject_mac_muladd_9s_14s_22ns_22_1_1_U7(
    .din0(grp_fu_1354_p0),
    .din1(grp_fu_1354_p1),
    .din2(lhs_V_1_fu_500_p3),
    .dout(grp_fu_1354_p3)
);

myproject_mul_mul_14s_14s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
myproject_mul_mul_14s_14s_28_1_1_U8(
    .din0(r_V_4_fu_1363_p0),
    .din1(r_V_4_fu_1363_p1),
    .dout(r_V_4_fu_1363_p2)
);

myproject_mul_mul_9ns_14s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_9ns_14s_22_1_1_U9(
    .din0(mul_ln1192_2_fu_1369_p0),
    .din1(mul_ln1192_2_fu_1369_p1),
    .dout(mul_ln1192_2_fu_1369_p2)
);

myproject_mul_mul_11ns_28s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 30 ))
myproject_mul_mul_11ns_28s_30_1_1_U10(
    .din0(mul_ln700_2_fu_1374_p0),
    .din1(r_V_12_reg_1588),
    .dout(mul_ln700_2_fu_1374_p2)
);

myproject_mul_mul_11ns_14s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_11ns_14s_22_1_1_U11(
    .din0(mul_ln700_3_fu_1381_p0),
    .din1(mul_ln700_3_fu_1381_p1),
    .dout(mul_ln700_3_fu_1381_p2)
);

myproject_mul_mul_12ns_14s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_12ns_14s_22_1_1_U12(
    .din0(mul_ln728_4_fu_1387_p0),
    .din1(mul_ln728_4_fu_1387_p1),
    .dout(mul_ln728_4_fu_1387_p2)
);

myproject_mac_muladd_14s_14s_17s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 22 ))
myproject_mac_muladd_14s_14s_17s_22_1_1_U13(
    .din0(grp_fu_1394_p0),
    .din1(grp_fu_1394_p1),
    .din2(grp_fu_1394_p2),
    .dout(grp_fu_1394_p3)
);

myproject_mul_mul_14s_28s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 30 ))
myproject_mul_mul_14s_28s_30_1_1_U14(
    .din0(p_Val2_s_reg_1509_pp0_iter1_reg),
    .din1(r_V_4_reg_1603),
    .dout(mul_ln1192_fu_1403_p2)
);

myproject_mac_muladd_9s_14s_22s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
myproject_mac_muladd_9s_14s_22s_22_1_1_U15(
    .din0(grp_fu_1410_p0),
    .din1(p_Val2_5_reg_1543_pp0_iter1_reg),
    .din2(mul_ln1192_2_reg_1608),
    .dout(grp_fu_1410_p3)
);

myproject_mul_mul_9ns_14s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_9ns_14s_23_1_1_U16(
    .din0(r_V_7_fu_1418_p0),
    .din1(p_Val2_5_reg_1543_pp0_iter1_reg),
    .dout(r_V_7_fu_1418_p2)
);

myproject_mul_mul_8s_14s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
myproject_mul_mul_8s_14s_21_1_1_U17(
    .din0(mul_ln728_fu_1424_p0),
    .din1(p_Val2_1_reg_1524_pp0_iter1_reg),
    .dout(mul_ln728_fu_1424_p2)
);

myproject_am_addmul_9s_14s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
myproject_am_addmul_9s_14s_30_1_1_U18(
    .din0(grp_fu_1430_p0),
    .din1(p_Val2_s_reg_1509_pp0_iter2_reg),
    .dout(grp_fu_1430_p2)
);

myproject_mac_muladd_9s_9s_15s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 18 ))
myproject_mac_muladd_9s_9s_15s_18_1_1_U19(
    .din0(grp_fu_1438_p0),
    .din1(grp_fu_1438_p1),
    .din2(grp_fu_1438_p2),
    .dout(grp_fu_1438_p3)
);

myproject_mac_muladd_17s_9s_17s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
myproject_mac_muladd_17s_9s_17s_18_1_1_U20(
    .din0(17'd77),
    .din1(grp_operator_s_fu_304_ap_return),
    .din2(r_V_19_reg_1668),
    .dout(grp_fu_1446_p3)
);

myproject_mul_mul_9ns_14s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_9ns_14s_22_1_1_U21(
    .din0(mul_ln728_1_fu_1454_p0),
    .din1(mul_ln728_1_fu_1454_p1),
    .dout(mul_ln728_1_fu_1454_p2)
);

myproject_ama_addmuladd_9s_9s_7ns_12s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 12 ),
    .dout_WIDTH( 16 ))
myproject_ama_addmuladd_9s_9s_7ns_12s_16_1_1_U22(
    .din0(grp_operator_s_fu_318_ap_return),
    .din1(grp_operator_s_fu_325_ap_return),
    .din2(grp_fu_1460_p2),
    .din3(grp_fu_1460_p3),
    .dout(grp_fu_1460_p4)
);

myproject_mac_muladd_9s_9s_23s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 23 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_9s_9s_23s_24_1_1_U23(
    .din0(grp_fu_1470_p0),
    .din1(grp_fu_1470_p1),
    .din2(lhs_V_6_fu_1002_p3),
    .dout(grp_fu_1470_p3)
);

myproject_am_addmul_10s_9s_10s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 21 ))
myproject_am_addmul_10s_9s_10s_21_1_1_U24(
    .din0(grp_fu_1478_p0),
    .din1(grp_operator_s_fu_367_ap_return),
    .din2(ret_V_11_fu_1055_p2),
    .dout(grp_fu_1478_p3)
);

myproject_mac_muladd_16s_24s_33s_38_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 38 ))
myproject_mac_muladd_16s_24s_33s_38_1_1_U25(
    .din0(ret_V_20_reg_1743),
    .din1(ret_V_24_fu_1124_p2),
    .din2(grp_fu_1486_p2),
    .dout(grp_fu_1486_p3)
);

myproject_mul_mul_21s_18s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 40 ))
myproject_mul_mul_21s_18s_40_1_1_U26(
    .din0(r_V_5_reg_1783),
    .din1(ret_V_13_fu_1171_p2),
    .dout(mul_ln1192_3_fu_1495_p2)
);

myproject_am_addmul_18s_18s_11s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 31 ))
myproject_am_addmul_18s_18s_11s_31_1_1_U27(
    .din0(r_V_26_fu_1195_p2),
    .din1(tmp_6_fu_1205_p3),
    .din2(ret_V_30_fu_1220_p2),
    .dout(grp_fu_1501_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_283_ap_ready == 1'b1)) begin
            grp_operator_s_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_290_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_290_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_290_ap_ready == 1'b1)) begin
            grp_operator_s_fu_290_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_297_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_297_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_297_ap_ready == 1'b1)) begin
            grp_operator_s_fu_297_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_304_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_304_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_304_ap_ready == 1'b1)) begin
            grp_operator_s_fu_304_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_311_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_311_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_311_ap_ready == 1'b1)) begin
            grp_operator_s_fu_311_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_318_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_318_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_318_ap_ready == 1'b1)) begin
            grp_operator_s_fu_318_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_325_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_325_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_325_ap_ready == 1'b1)) begin
            grp_operator_s_fu_325_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_332_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_332_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_332_ap_ready == 1'b1)) begin
            grp_operator_s_fu_332_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_339_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_339_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_339_ap_ready == 1'b1)) begin
            grp_operator_s_fu_339_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_346_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_operator_s_fu_346_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_346_ap_ready == 1'b1)) begin
            grp_operator_s_fu_346_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_353_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_353_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_353_ap_ready == 1'b1)) begin
            grp_operator_s_fu_353_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_360_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_360_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_360_ap_ready == 1'b1)) begin
            grp_operator_s_fu_360_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_367_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_367_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_367_ap_ready == 1'b1)) begin
            grp_operator_s_fu_367_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_374_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_374_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_374_ap_ready == 1'b1)) begin
            grp_operator_s_fu_374_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_381_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_381_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_381_ap_ready == 1'b1)) begin
            grp_operator_s_fu_381_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_388_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_388_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_388_ap_ready == 1'b1)) begin
            grp_operator_s_fu_388_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_s_fu_395_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            grp_operator_s_fu_395_ap_start_reg <= 1'b1;
        end else if ((grp_operator_s_fu_395_ap_ready == 1'b1)) begin
            grp_operator_s_fu_395_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_V_ap_vld_preg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_V_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (x_V_ap_vld == 1'b1))) begin
            x_V_ap_vld_preg <= x_V_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_V_preg <= 224'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (x_V_ap_vld == 1'b1))) begin
            x_V_preg <= x_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1192_12_reg_1678[19 : 3] <= add_ln1192_12_fu_793_p2[19 : 3];
        add_ln1192_17_reg_1738[37 : 3] <= add_ln1192_17_fu_988_p2[37 : 3];
        add_ln1192_reg_1773 <= add_ln1192_fu_1042_p2;
        add_ln703_2_reg_1708 <= add_ln703_2_fu_879_p2;
        mul_ln1192_3_reg_1818 <= mul_ln1192_3_fu_1495_p2;
        mul_ln700_1_reg_1813 <= mul_ln700_1_fu_1165_p2;
        mul_ln700_reg_1768 <= mul_ln700_fu_1023_p2;
        mul_ln728_reg_1683 <= mul_ln728_fu_1424_p2;
        p_0_reg_1808 <= grp_operator_s_fu_395_ap_return;
        p_0_reg_1808_pp0_iter5_reg <= p_0_reg_1808;
        p_2_reg_1758 <= grp_operator_s_fu_339_ap_return;
        p_2_reg_1758_pp0_iter4_reg <= p_2_reg_1758;
        p_6_reg_1733 <= grp_operator_s_fu_311_ap_return;
        p_6_reg_1733_pp0_iter4_reg <= p_6_reg_1733;
        p_6_reg_1733_pp0_iter5_reg <= p_6_reg_1733_pp0_iter4_reg;
        p_Val2_10_reg_1778 <= grp_operator_s_fu_360_ap_return;
        p_Val2_10_reg_1778_pp0_iter5_reg <= p_Val2_10_reg_1778;
        p_Val2_27_reg_1753 <= grp_operator_s_fu_332_ap_return;
        p_Val2_32_reg_1798 <= grp_operator_s_fu_381_ap_return;
        p_Val2_38_reg_1763 <= grp_operator_s_fu_346_ap_return;
        p_Val2_4_reg_1537_pp0_iter2_reg <= p_Val2_4_reg_1537_pp0_iter1_reg;
        p_Val2_4_reg_1537_pp0_iter3_reg <= p_Val2_4_reg_1537_pp0_iter2_reg;
        p_Val2_s_24_reg_1723 <= grp_operator_s_fu_297_ap_return;
        p_Val2_s_reg_1509_pp0_iter2_reg <= p_Val2_s_reg_1509_pp0_iter1_reg;
        r_V_19_reg_1668[16 : 3] <= r_V_19_fu_728_p3[16 : 3];
        r_V_7_reg_1673 <= r_V_7_fu_1418_p2;
        ret_V_2_reg_1713 <= ret_V_2_fu_907_p2;
        ret_V_38_reg_1728_pp0_iter4_reg <= ret_V_38_reg_1728;
        ret_V_44_reg_1693 <= ret_V_44_fu_817_p2;
        ret_V_49_reg_1803 <= ret_V_49_fu_1153_p2;
        sext_ln728_1_reg_1557_pp0_iter2_reg <= sext_ln728_1_reg_1557_pp0_iter1_reg;
        trunc_ln708_10_reg_1698 <= {{r_V_24_fu_844_p2[20:8]}};
        trunc_ln708_12_reg_1703 <= {{r_V_27_fu_863_p2[45:32]}};
        trunc_ln708_1_reg_1658 <= {{ret_V_33_fu_692_p2[29:16]}};
        trunc_ln708_2_reg_1663 <= {{ret_V_35_fu_710_p2[21:8]}};
        trunc_ln708_6_reg_1793 <= {{grp_fu_1486_p3[37:24]}};
        trunc_ln708_6_reg_1793_pp0_iter5_reg <= trunc_ln708_6_reg_1793;
        trunc_ln708_8_reg_1688 <= {{r_V_22_fu_799_p2[45:32]}};
        trunc_ln708_9_reg_1788 <= {{ret_V_42_fu_1092_p2[37:24]}};
        trunc_ln708_9_reg_1788_pp0_iter5_reg <= trunc_ln708_9_reg_1788;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln703_1_reg_1638 <= add_ln703_1_fu_635_p2;
        add_ln703_reg_1628 <= add_ln703_fu_592_p2;
        lhs_V_5_reg_1578 <= lhs_V_5_fu_493_p1;
        lhs_V_5_reg_1578_pp0_iter1_reg <= lhs_V_5_reg_1578;
        mul_ln1118_5_reg_1648 <= mul_ln1118_5_fu_664_p2;
        mul_ln1118_reg_1623 <= mul_ln1118_fu_586_p2;
        mul_ln1192_2_reg_1608 <= mul_ln1192_2_fu_1369_p2;
        mul_ln1192_6_reg_1563 <= mul_ln1192_6_fu_1323_p2;
        p_Val2_1_reg_1524 <= {{x_V_in_sig[209:196]}};
        p_Val2_1_reg_1524_pp0_iter1_reg <= p_Val2_1_reg_1524;
        p_Val2_2_reg_1516 <= {{x_V_in_sig[55:42]}};
        p_Val2_4_reg_1537 <= {{x_V_in_sig[69:56]}};
        p_Val2_4_reg_1537_pp0_iter1_reg <= p_Val2_4_reg_1537;
        p_Val2_5_reg_1543 <= {{x_V_in_sig[223:210]}};
        p_Val2_5_reg_1543_pp0_iter1_reg <= p_Val2_5_reg_1543;
        p_Val2_s_reg_1509 <= {{x_V_in_sig[41:28]}};
        p_Val2_s_reg_1509_pp0_iter1_reg <= p_Val2_s_reg_1509;
        r_V_12_reg_1588 <= r_V_12_fu_1340_p2;
        r_V_4_reg_1603 <= r_V_4_fu_1363_p2;
        sext_ln727_reg_1532 <= sext_ln727_fu_436_p1;
        sext_ln728_1_reg_1557 <= sext_ln728_1_fu_460_p1;
        sext_ln728_1_reg_1557_pp0_iter1_reg <= sext_ln728_1_reg_1557;
        tmp_7_reg_1568 <= {{x_V_in_sig[54:42]}};
        trunc_ln708_11_reg_1643 <= {{add_ln1192_28_fu_645_p2[21:8]}};
        trunc_ln708_13_reg_1653 <= {{grp_fu_1394_p3[21:8]}};
        trunc_ln708_4_reg_1613 <= {{ret_V_37_fu_544_p2[21:8]}};
        trunc_ln708_5_reg_1618 <= {{add_ln1192_7_fu_567_p2[21:8]}};
        trunc_ln708_7_reg_1573 <= {{ret_V_40_fu_474_p2[21:8]}};
        trunc_ln708_s_reg_1633 <= {{ret_V_43_fu_619_p2[29:16]}};
        trunc_ln_reg_1598 <= {{grp_fu_1354_p3[21:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        mul_ln1192_9_reg_1823 <= grp_fu_1501_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        r_V_5_reg_1783 <= grp_fu_1478_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_V_17_reg_1583 <= grp_fu_1330_p4;
        ret_V_27_reg_1593 <= grp_fu_1346_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ret_V_20_reg_1743 <= grp_fu_1460_p4;
        ret_V_38_reg_1728 <= grp_fu_1446_p3;
        ret_V_45_reg_1748 <= grp_fu_1470_p3;
        ret_V_4_reg_1718 <= grp_fu_1438_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to5 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp47) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_283_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_283_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp69) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_290_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_290_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp81) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_297_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_297_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp85) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_304_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_304_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp86) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_311_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_311_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp103) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_318_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_318_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp104) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_325_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_325_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp107) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_332_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_332_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp114) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_339_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_339_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp118) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_346_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_346_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp133) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_353_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_353_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp134) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_360_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_360_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp135) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_367_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_367_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp158) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_374_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_374_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp174) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_381_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_381_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp176) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_388_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_388_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp178) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_operator_s_fu_395_ap_ce = 1'b1;
    end else begin
        grp_operator_s_fu_395_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((x_V_ap_vld == 1'b1)) begin
        x_V_ap_vld_in_sig = x_V_ap_vld;
    end else begin
        x_V_ap_vld_in_sig = x_V_ap_vld_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_V_blk_n = x_V_ap_vld;
    end else begin
        x_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((x_V_ap_vld == 1'b1)) begin
        x_V_in_sig = x_V;
    end else begin
        x_V_in_sig = x_V_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        y_0_V_ap_vld = 1'b1;
    end else begin
        y_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        y_1_V_ap_vld = 1'b1;
    end else begin
        y_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        y_2_V_ap_vld = 1'b1;
    end else begin
        y_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        y_3_V_ap_vld = 1'b1;
    end else begin
        y_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        y_4_V_ap_vld = 1'b1;
    end else begin
        y_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1192_12_fu_793_p2 = ($signed(r_V_20_fu_753_p2) + $signed(sext_ln1118_8_fu_789_p1));

assign add_ln1192_16_fu_960_p2 = (sub_ln1192_1_fu_947_p2 + rhs_V_2_fu_953_p3);

assign add_ln1192_17_fu_988_p2 = ($signed(add_ln1192_16_fu_960_p2) + $signed(rhs_V_3_fu_984_p1));

assign add_ln1192_19_fu_1087_p2 = ($signed(add_ln1192_17_reg_1738) + $signed(rhs_V_4_fu_1083_p1));

assign add_ln1192_28_fu_645_p2 = (lhs_V_1_fu_500_p3 + add_ln1192_30_fu_639_p2);

assign add_ln1192_30_fu_639_p2 = ($signed(22'd4083200) + $signed(trunc_ln1_fu_560_p3));

assign add_ln1192_7_fu_567_p2 = ($signed(22'd4180736) + $signed(trunc_ln1_fu_560_p3));

assign add_ln1192_8_fu_526_p2 = ($signed(mul_ln1192_6_reg_1563) + $signed(lhs_V_3_fu_519_p3));

assign add_ln1192_fu_1042_p2 = (15'd1001 + ret_V_34_fu_1036_p2);

assign add_ln700_fu_607_p2 = ($signed(mul_ln700_2_fu_1374_p2) + $signed(shl_ln1_fu_600_p3));

assign add_ln703_1_fu_635_p2 = ($signed(p_Val2_5_reg_1543) + $signed(p_Val2_2_reg_1516));

assign add_ln703_2_fu_879_p2 = (14'd377 + p_Val2_1_reg_1524_pp0_iter1_reg);

assign add_ln703_fu_592_p2 = ($signed(14'd16205) + $signed(p_Val2_2_reg_1516));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp103 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp104 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp107 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp114 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp118 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp133 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp134 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp135 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp158 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp174 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp176 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp178 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp47 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp69 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp81 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp85 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp86 = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b1) & ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call102 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call116 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call149 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call159 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call171 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call185 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call203 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call209 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call223 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call227 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call238 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call30 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call48 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call62 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call68 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call78 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call91 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call102 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call116 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call149 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call159 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call171 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call185 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call203 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call209 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call223 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call227 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call238 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call30 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call62 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call78 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call91 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call102 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call116 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call149 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call159 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call171 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call185 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call203 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call209 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call223 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call227 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call238 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call30 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call62 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call78 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call91 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call102 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call116 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call149 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call159 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call171 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call185 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call203 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call209 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call223 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call227 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call238 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call30 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call62 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call78 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call91 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call102 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call116 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call149 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call159 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call171 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call185 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call203 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call209 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call223 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call227 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call238 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call30 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call62 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call78 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call91 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call102 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call116 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call149 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call159 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call171 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call185 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call203 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call209 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call223 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call227 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call238 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call30 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call62 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call78 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call91 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call102 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call116 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call149 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call159 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call171 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call185 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call203 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call209 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call223 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call227 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call238 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call30 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call62 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call78 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call91 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_fu_1330_p2 = 23'd163;

assign grp_fu_1330_p3 = 23'd65536;

assign grp_fu_1346_p0 = 22'd238;

assign grp_fu_1346_p2 = 22'd65536;

assign grp_fu_1354_p0 = 22'd4194145;

assign grp_fu_1354_p1 = sext_ln728_fu_497_p1;

assign grp_fu_1394_p0 = sext_ln728_fu_497_p1;

assign grp_fu_1394_p1 = sext_ln728_fu_497_p1;

assign grp_fu_1394_p2 = 22'd4160512;

assign grp_fu_1410_p0 = 22'd4194105;

assign grp_fu_1430_p0 = 15'd32532;

assign grp_fu_1438_p0 = sext_ln1116_fu_913_p1;

assign grp_fu_1438_p1 = sext_ln1116_fu_913_p1;

assign grp_fu_1438_p2 = 18'd253696;

assign grp_fu_1460_p2 = 16'd45;

assign grp_fu_1460_p3 = 16'd64256;

assign grp_fu_1470_p0 = sext_ln1118_9_fu_966_p1;

assign grp_fu_1470_p1 = sext_ln1118_9_fu_966_p1;

assign grp_fu_1478_p0 = 11'd1696;

assign grp_fu_1486_p2 = 38'd270801043456;

assign grp_operator_s_fu_283_ap_start = grp_operator_s_fu_283_ap_start_reg;

assign grp_operator_s_fu_290_ap_start = grp_operator_s_fu_290_ap_start_reg;

assign grp_operator_s_fu_297_ap_start = grp_operator_s_fu_297_ap_start_reg;

assign grp_operator_s_fu_304_ap_start = grp_operator_s_fu_304_ap_start_reg;

assign grp_operator_s_fu_311_ap_start = grp_operator_s_fu_311_ap_start_reg;

assign grp_operator_s_fu_318_ap_start = grp_operator_s_fu_318_ap_start_reg;

assign grp_operator_s_fu_325_ap_start = grp_operator_s_fu_325_ap_start_reg;

assign grp_operator_s_fu_332_ap_start = grp_operator_s_fu_332_ap_start_reg;

assign grp_operator_s_fu_339_ap_start = grp_operator_s_fu_339_ap_start_reg;

assign grp_operator_s_fu_346_ap_start = grp_operator_s_fu_346_ap_start_reg;

assign grp_operator_s_fu_353_ap_start = grp_operator_s_fu_353_ap_start_reg;

assign grp_operator_s_fu_360_ap_start = grp_operator_s_fu_360_ap_start_reg;

assign grp_operator_s_fu_367_ap_start = grp_operator_s_fu_367_ap_start_reg;

assign grp_operator_s_fu_374_ap_start = grp_operator_s_fu_374_ap_start_reg;

assign grp_operator_s_fu_381_ap_start = grp_operator_s_fu_381_ap_start_reg;

assign grp_operator_s_fu_381_n_V = $signed(trunc_ln708_10_reg_1698);

assign grp_operator_s_fu_388_ap_start = grp_operator_s_fu_388_ap_start_reg;

assign grp_operator_s_fu_395_ap_start = grp_operator_s_fu_395_ap_start_reg;

assign lhs_V_1_fu_500_p3 = {{p_Val2_1_reg_1524}, {8'd0}};

assign lhs_V_2_fu_685_p3 = {{p_Val2_5_reg_1543_pp0_iter1_reg}, {16'd0}};

assign lhs_V_3_fu_519_p3 = {{p_Val2_5_reg_1543}, {8'd0}};

assign lhs_V_4_fu_936_p3 = {{mul_ln728_reg_1683}, {16'd0}};

assign lhs_V_5_fu_493_p1 = p_Val2_1_fu_426_p4;

assign lhs_V_6_fu_1002_p3 = {{ret_V_44_reg_1693}, {8'd0}};

assign mul_ln1118_5_fu_664_p0 = sext_ln1118_16_fu_661_p1;

assign mul_ln1118_5_fu_664_p1 = sext_ln1118_16_fu_661_p1;

assign mul_ln1118_5_fu_664_p2 = ($signed(mul_ln1118_5_fu_664_p0) * $signed(mul_ln1118_5_fu_664_p1));

assign mul_ln1118_fu_586_p0 = sext_ln1118_11_fu_583_p1;

assign mul_ln1118_fu_586_p1 = sext_ln1118_11_fu_583_p1;

assign mul_ln1118_fu_586_p2 = ($signed(mul_ln1118_fu_586_p0) * $signed(mul_ln1118_fu_586_p1));

assign mul_ln1192_10_fu_1296_p0 = p_0_reg_1808_pp0_iter5_reg;

assign mul_ln1192_10_fu_1296_p1 = mul_ln1192_9_reg_1823;

assign mul_ln1192_10_fu_1296_p2 = ($signed(mul_ln1192_10_fu_1296_p0) * $signed(mul_ln1192_10_fu_1296_p1));

assign mul_ln1192_2_fu_1369_p0 = 22'd199;

assign mul_ln1192_2_fu_1369_p1 = sext_ln728_1_reg_1557;

assign mul_ln1192_4_fu_1263_p0 = p_6_reg_1733_pp0_iter5_reg;

assign mul_ln1192_4_fu_1263_p1 = mul_ln1192_3_reg_1818;

assign mul_ln1192_4_fu_1263_p2 = ($signed(mul_ln1192_4_fu_1263_p0) * $signed(mul_ln1192_4_fu_1263_p1));

assign mul_ln1192_5_fu_930_p0 = r_V_7_reg_1673;

assign mul_ln1192_5_fu_930_p1 = add_ln1192_12_reg_1678;

assign mul_ln1192_5_fu_930_p2 = ($signed(mul_ln1192_5_fu_930_p0) * $signed(mul_ln1192_5_fu_930_p1));

assign mul_ln1192_6_fu_1323_p0 = sext_ln728_1_fu_460_p1;

assign mul_ln1192_6_fu_1323_p1 = sext_ln728_1_fu_460_p1;

assign mul_ln700_1_fu_1165_p0 = add_ln1192_reg_1773;

assign mul_ln700_1_fu_1165_p1 = mul_ln700_reg_1768;

assign mul_ln700_1_fu_1165_p2 = ($signed(mul_ln700_1_fu_1165_p0) * $signed(mul_ln700_1_fu_1165_p1));

assign mul_ln700_2_fu_1374_p0 = 30'd840;

assign mul_ln700_3_fu_1381_p0 = 22'd840;

assign mul_ln700_3_fu_1381_p1 = sext_ln727_reg_1532;

assign mul_ln700_fu_1023_p0 = ret_V_4_reg_1718;

assign mul_ln700_fu_1023_p1 = ret_V_2_reg_1713;

assign mul_ln700_fu_1023_p2 = ($signed(mul_ln700_fu_1023_p0) * $signed(mul_ln700_fu_1023_p1));

assign mul_ln728_1_fu_1454_p0 = 22'd141;

assign mul_ln728_1_fu_1454_p1 = sext_ln728_1_reg_1557_pp0_iter2_reg;

assign mul_ln728_2_fu_970_p1 = sext_ln1118_9_fu_966_p1;

assign mul_ln728_2_fu_970_p2 = ($signed({{1'b0}, {18'd138}}) * $signed(mul_ln728_2_fu_970_p1));

assign mul_ln728_3_fu_1069_p1 = grp_operator_s_fu_374_ap_return;

assign mul_ln728_3_fu_1069_p2 = ($signed({{1'b0}, {18'd138}}) * $signed(mul_ln728_3_fu_1069_p1));

assign mul_ln728_4_fu_1387_p0 = 22'd1680;

assign mul_ln728_4_fu_1387_p1 = sext_ln728_fu_497_p1;

assign mul_ln728_fu_1424_p0 = 21'd2097082;

assign p_Val2_1_fu_426_p4 = {{x_V_in_sig[209:196]}};

assign p_Val2_2_fu_412_p4 = {{x_V_in_sig[55:42]}};

assign p_Val2_s_fu_402_p4 = {{x_V_in_sig[41:28]}};

assign p_shl_fu_893_p3 = {{trunc_ln1193_fu_890_p1}, {5'd0}};

assign r_V_11_fu_489_p1 = p_Val2_1_fu_426_p4;

assign r_V_12_fu_1340_p0 = r_V_11_fu_489_p1;

assign r_V_12_fu_1340_p1 = r_V_11_fu_489_p1;

assign r_V_19_fu_728_p3 = {{p_Val2_5_reg_1543_pp0_iter1_reg}, {3'd0}};

assign r_V_20_fu_753_p2 = ($signed(sext_ln1118_5_fu_749_p1) - $signed(sext_ln1118_3_fu_735_p1));

assign r_V_21_fu_783_p2 = ($signed(sext_ln1118_6_fu_767_p1) - $signed(sext_ln1118_7_fu_779_p1));

assign r_V_22_fu_799_p2 = ($signed({{1'b0}, {46'd627}}) * $signed(mul_ln1118_reg_1623));

assign r_V_24_fu_844_p2 = ($signed(sext_ln1118_13_fu_829_p1) - $signed(sext_ln1118_14_fu_840_p1));

assign r_V_25_fu_1186_p2 = ($signed(10'd0) - $signed(sext_ln1253_fu_1183_p1));

assign r_V_26_fu_1195_p0 = sext_ln1116_3_fu_1192_p1;

assign r_V_26_fu_1195_p1 = sext_ln1116_3_fu_1192_p1;

assign r_V_26_fu_1195_p2 = ($signed(r_V_26_fu_1195_p0) * $signed(r_V_26_fu_1195_p1));

assign r_V_27_fu_863_p1 = mul_ln1118_5_reg_1648;

assign r_V_27_fu_863_p2 = ($signed({{1'b0}, {46'd1175}}) * $signed(r_V_27_fu_863_p1));

assign r_V_3_fu_516_p1 = p_Val2_4_reg_1537;

assign r_V_4_fu_1363_p0 = r_V_3_fu_516_p1;

assign r_V_4_fu_1363_p1 = r_V_3_fu_516_p1;

assign r_V_7_fu_1418_p0 = 23'd137;

assign ret_V_11_fu_1055_p2 = ($signed(10'd787) + $signed(sext_ln703_1_fu_1052_p1));

assign ret_V_13_fu_1171_p2 = ($signed(18'd256768) + $signed(ret_V_38_reg_1728_pp0_iter4_reg));

assign ret_V_24_fu_1124_p2 = ($signed(24'd16533504) + $signed(ret_V_46_fu_1119_p2));

assign ret_V_2_fu_907_p2 = (33'd7274496 + sub_ln1193_1_fu_901_p2);

assign ret_V_30_fu_1220_p2 = ($signed(11'd58) + $signed(sext_ln703_8_fu_1217_p1));

assign ret_V_33_fu_692_p2 = ($signed(mul_ln1192_fu_1403_p2) + $signed(lhs_V_2_fu_685_p3));

assign ret_V_34_fu_1036_p2 = ($signed(sext_ln1192_3_fu_1032_p1) - $signed(sext_ln1192_2_fu_1029_p1));

assign ret_V_35_fu_710_p2 = ($signed(22'd50432) + $signed(grp_fu_1410_p3));

assign ret_V_36_fu_1241_p2 = ($signed(mul_ln700_1_reg_1813) - $signed(rhs_V_fu_1237_p1));

assign ret_V_37_fu_544_p2 = ($signed(22'd4092416) + $signed(sub_ln1192_fu_538_p2));

assign ret_V_39_fu_1269_p2 = ($signed(44'd16660178141184) + $signed(mul_ln1192_4_fu_1263_p2));

assign ret_V_40_fu_474_p2 = ($signed(22'd4121856) + $signed(mul_ln1192_6_fu_1323_p2));

assign ret_V_42_fu_1092_p2 = ($signed(38'd272059334656) + $signed(add_ln1192_19_fu_1087_p2));

assign ret_V_43_fu_619_p2 = (add_ln700_fu_607_p2 + rhs_V_5_fu_612_p3);

assign ret_V_44_fu_817_p2 = ($signed(lhs_V_5_reg_1578_pp0_iter1_reg) + $signed(rhs_V_6_fu_814_p1));

assign ret_V_46_fu_1119_p2 = ($signed(ret_V_45_reg_1748) + $signed(sext_ln1192_18_fu_1115_p1));

assign ret_V_49_fu_1153_p2 = ($signed(sext_ln703_6_fu_1146_p1) - $signed(sext_ln703_7_fu_1150_p1));

assign ret_V_50_fu_1302_p2 = ($signed(37'd133781520384) + $signed(mul_ln1192_10_fu_1296_p2));

assign rhs_V_1_fu_531_p3 = {{p_Val2_2_reg_1516}, {8'd0}};

assign rhs_V_2_fu_953_p3 = {{mul_ln728_1_fu_1454_p2}, {16'd0}};

assign rhs_V_3_fu_984_p1 = $signed(tmp_4_fu_976_p3);

assign rhs_V_4_fu_1083_p1 = $signed(tmp_5_fu_1075_p3);

assign rhs_V_5_fu_612_p3 = {{mul_ln728_4_fu_1387_p2}, {8'd0}};

assign rhs_V_6_fu_814_p1 = p_Val2_5_reg_1543_pp0_iter1_reg;

assign rhs_V_fu_1237_p1 = $signed(tmp_3_fu_1230_p3);

assign sext_ln1116_3_fu_1192_p1 = $signed(p_2_reg_1758_pp0_iter4_reg);

assign sext_ln1116_fu_913_p1 = $signed(grp_operator_s_fu_290_ap_return);

assign sext_ln1118_11_fu_583_p1 = ret_V_17_reg_1583;

assign sext_ln1118_13_fu_829_p1 = $signed(shl_ln1118_3_fu_822_p3);

assign sext_ln1118_14_fu_840_p1 = $signed(shl_ln1118_4_fu_833_p3);

assign sext_ln1118_16_fu_661_p1 = ret_V_27_reg_1593;

assign sext_ln1118_3_fu_735_p1 = r_V_19_fu_728_p3;

assign sext_ln1118_5_fu_749_p1 = $signed(shl_ln_fu_742_p3);

assign sext_ln1118_6_fu_767_p1 = $signed(tmp_9_fu_759_p3);

assign sext_ln1118_7_fu_779_p1 = $signed(tmp_s_fu_771_p3);

assign sext_ln1118_8_fu_789_p1 = $signed(r_V_21_fu_783_p2);

assign sext_ln1118_9_fu_966_p0 = grp_operator_s_fu_311_ap_return;

assign sext_ln1118_9_fu_966_p1 = sext_ln1118_9_fu_966_p0;

assign sext_ln1118_fu_887_p1 = grp_fu_1430_p2;

assign sext_ln1192_11_fu_943_p1 = $signed(lhs_V_4_fu_936_p3);

assign sext_ln1192_18_fu_1115_p1 = $signed(tmp_1_fu_1108_p3);

assign sext_ln1192_2_fu_1029_p1 = p_Val2_4_reg_1537_pp0_iter3_reg;

assign sext_ln1192_3_fu_1032_p1 = $signed(grp_operator_s_fu_353_ap_return);

assign sext_ln1253_fu_1183_p1 = $signed(p_Val2_32_reg_1798);

assign sext_ln703_1_fu_1052_p1 = $signed(p_Val2_s_24_reg_1723);

assign sext_ln703_6_fu_1146_p1 = $signed(grp_operator_s_fu_388_ap_return);

assign sext_ln703_7_fu_1150_p1 = $signed(p_Val2_38_reg_1763);

assign sext_ln703_8_fu_1217_p1 = $signed(ret_V_49_reg_1803);

assign sext_ln727_fu_436_p1 = p_Val2_1_fu_426_p4;

assign sext_ln728_1_fu_460_p1 = p_Val2_s_fu_402_p4;

assign sext_ln728_fu_497_p1 = p_Val2_2_reg_1516;

assign shl_ln1118_3_fu_822_p3 = {{p_Val2_5_reg_1543_pp0_iter1_reg}, {6'd0}};

assign shl_ln1118_4_fu_833_p3 = {{p_Val2_5_reg_1543_pp0_iter1_reg}, {2'd0}};

assign shl_ln1_fu_600_p3 = {{mul_ln700_3_fu_1381_p2}, {8'd0}};

assign shl_ln_fu_742_p3 = {{p_Val2_5_reg_1543_pp0_iter1_reg}, {5'd0}};

assign sub_ln1192_1_fu_947_p2 = ($signed(sext_ln1192_11_fu_943_p1) - $signed(mul_ln1192_5_fu_930_p2));

assign sub_ln1192_fu_538_p2 = (add_ln1192_8_fu_526_p2 - rhs_V_1_fu_531_p3);

assign sub_ln1193_1_fu_901_p2 = ($signed(sext_ln1118_fu_887_p1) - $signed(p_shl_fu_893_p3));

assign tmp_1_fu_1108_p3 = {{p_Val2_27_reg_1753}, {8'd0}};

assign tmp_3_fu_1230_p3 = {{p_Val2_10_reg_1778_pp0_iter5_reg}, {40'd0}};

assign tmp_4_fu_976_p3 = {{mul_ln728_2_fu_970_p2}, {16'd0}};

assign tmp_5_fu_1075_p3 = {{mul_ln728_3_fu_1069_p2}, {16'd0}};

assign tmp_6_fu_1205_p3 = {{r_V_25_fu_1186_p2}, {8'd0}};

assign tmp_8_fu_1308_p4 = {{ret_V_50_fu_1302_p2[36:24]}};

assign tmp_9_fu_759_p3 = {{grp_operator_s_fu_283_ap_return}, {5'd0}};

assign tmp_fu_1275_p4 = {{ret_V_39_fu_1269_p2[43:32]}};

assign tmp_s_fu_771_p3 = {{grp_operator_s_fu_283_ap_return}, {3'd0}};

assign trunc_ln1193_fu_890_p1 = grp_fu_1430_p2[27:0];

assign trunc_ln1_fu_560_p3 = {{tmp_7_reg_1568}, {9'd0}};

assign y_0_V = {{ret_V_36_fu_1241_p2[53:40]}};

assign y_1_V = $signed(tmp_fu_1275_p4);

assign y_2_V = trunc_ln708_9_reg_1788_pp0_iter5_reg;

assign y_3_V = trunc_ln708_6_reg_1793_pp0_iter5_reg;

assign y_4_V = $signed(tmp_8_fu_1308_p4);

always @ (posedge ap_clk) begin
    r_V_19_reg_1668[2:0] <= 3'b000;
    add_ln1192_12_reg_1678[2:0] <= 3'b000;
    add_ln1192_17_reg_1738[2:0] <= 3'b000;
end

endmodule //myproject
