// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cos_lut_ap_fixed_9_6_5_3_0_s (
        ap_clk,
        ap_rst,
        input_V,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [8:0] input_V;
output  [4:0] ap_return;
input   ap_ce;

reg[4:0] ap_return;

reg   [2:0] p_Val2_53_reg_632;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] p_Val2_53_reg_632_pp0_iter1_reg;
reg   [2:0] p_Val2_53_reg_632_pp0_iter2_reg;
reg   [2:0] p_Result_s_fu_149_p4;
reg   [2:0] p_Result_s_reg_648;
wire   [10:0] trunc_ln893_fu_173_p1;
reg   [10:0] trunc_ln893_reg_653;
wire   [31:0] sub_ln894_fu_177_p2;
reg   [31:0] sub_ln894_reg_658;
wire   [31:0] or_ln899_s_fu_285_p3;
reg   [31:0] or_ln899_s_reg_664;
wire   [0:0] icmp_ln908_fu_293_p2;
reg   [0:0] icmp_ln908_reg_669;
wire   [63:0] bitcast_ln729_fu_412_p1;
wire   [0:0] or_ln924_fu_442_p2;
reg   [0:0] or_ln924_reg_682;
wire    ap_block_pp0_stage0;
wire  signed [23:0] r_V_fu_624_p2;
wire   [31:0] p_Result_25_fu_158_p3;
reg   [31:0] l_fu_165_p3;
wire   [31:0] lsb_index_fu_187_p2;
wire   [30:0] tmp_10_fu_193_p4;
wire   [1:0] trunc_ln897_fu_209_p1;
wire   [1:0] sub_ln897_fu_213_p2;
wire   [2:0] zext_ln897_fu_219_p1;
wire   [2:0] lshr_ln897_fu_223_p2;
wire   [2:0] p_Result_16_fu_229_p2;
wire   [0:0] icmp_ln897_fu_203_p2;
wire   [0:0] icmp_ln897_2_fu_234_p2;
wire   [0:0] tmp_11_fu_246_p3;
wire   [2:0] trunc_ln894_fu_183_p1;
wire   [2:0] add_ln899_fu_260_p2;
wire   [0:0] p_Result_17_fu_266_p3;
wire   [0:0] xor_ln899_fu_254_p2;
wire   [0:0] and_ln899_fu_273_p2;
wire   [0:0] a_fu_240_p2;
wire   [0:0] or_ln899_fu_279_p2;
wire   [31:0] zext_ln907_2_fu_302_p1;
wire   [31:0] add_ln908_fu_305_p2;
wire   [31:0] lshr_ln908_fu_310_p2;
wire   [31:0] sub_ln908_fu_320_p2;
wire   [63:0] m_fu_299_p1;
wire   [63:0] zext_ln908_2_fu_325_p1;
wire   [63:0] zext_ln908_fu_316_p1;
wire   [63:0] shl_ln908_fu_329_p2;
wire   [63:0] zext_ln911_fu_342_p1;
wire   [63:0] m_12_fu_335_p3;
wire   [63:0] m_13_fu_345_p2;
wire   [62:0] m_s_fu_351_p4;
wire   [10:0] sub_ln915_fu_373_p2;
wire   [0:0] tmp_12_fu_365_p3;
wire   [10:0] add_ln915_fu_378_p2;
wire   [10:0] select_ln915_fu_384_p3;
wire   [63:0] m_22_fu_361_p1;
wire   [11:0] tmp_8_fu_392_p3;
wire   [63:0] p_Result_26_fu_400_p5;
wire   [51:0] trunc_ln6_fu_420_p4;
wire   [0:0] icmp_ln924_2_fu_436_p2;
wire   [0:0] icmp_ln924_fu_430_p2;
wire   [2:0] add_ln147_fu_448_p2;
wire   [1:0] tmp_9_fu_453_p4;
wire   [0:0] icmp_ln879_fu_469_p2;
wire   [0:0] icmp_ln879_2_fu_474_p2;
wire   [0:0] icmp_ln146_fu_485_p2;
wire   [0:0] icmp_ln146_1_fu_490_p2;
wire   [0:0] icmp_ln146_3_fu_506_p2;
wire   [0:0] icmp_ln147_fu_463_p2;
wire   [0:0] and_ln147_fu_511_p2;
wire   [0:0] icmp_ln146_2_fu_501_p2;
wire   [0:0] grp_fu_116_p2;
wire   [0:0] grp_fu_121_p2;
wire   [0:0] or_ln154_1_fu_528_p2;
wire   [0:0] and_ln154_1_fu_534_p2;
wire   [0:0] icmp_ln885_fu_523_p2;
wire   [0:0] grp_fu_126_p2;
wire   [0:0] grp_fu_131_p2;
wire   [0:0] or_ln155_fu_545_p2;
wire   [0:0] and_ln155_1_fu_551_p2;
wire   [0:0] and_ln154_fu_539_p2;
wire   [0:0] and_ln155_fu_556_p2;
wire   [0:0] and_ln147_1_fu_517_p2;
wire   [0:0] or_ln146_fu_495_p2;
wire   [0:0] or_ln148_fu_479_p2;
wire   [0:0] or_ln154_fu_570_p2;
wire   [3:0] select_ln154_fu_562_p3;
wire   [3:0] select_ln154_1_fu_576_p3;
wire   [3:0] select_ln154_3_fu_598_p3;
wire   [0:0] or_ln154_2_fu_584_p2;
wire   [0:0] or_ln154_3_fu_610_p2;
wire  signed [4:0] sext_ln154_fu_606_p1;
wire   [4:0] select_ln154_2_fu_590_p3;
wire   [14:0] r_V_fu_624_p0;
reg    grp_fu_116_ce;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_121_ce;
reg    grp_fu_126_ce;
reg    grp_fu_131_ce;
wire   [4:0] select_ln154_4_fu_616_p3;
reg    ap_ce_reg;
reg  signed [8:0] input_V_int_reg;
reg   [4:0] ap_return_int_reg;

myproject_dcmp_64ns_64ns_1_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_0_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_412_p1),
    .din1(64'd4593671619917905920),
    .ce(grp_fu_116_ce),
    .opcode(5'd1),
    .dout(grp_fu_116_p2)
);

myproject_dcmp_64ns_64ns_1_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_0_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_412_p1),
    .din1(64'd4606056518893174784),
    .ce(grp_fu_121_ce),
    .opcode(5'd1),
    .dout(grp_fu_121_p2)
);

myproject_dcmp_64ns_64ns_1_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_0_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_412_p1),
    .din1(64'd4600427019358961664),
    .ce(grp_fu_126_ce),
    .opcode(5'd1),
    .dout(grp_fu_126_p2)
);

myproject_dcmp_64ns_64ns_1_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_0_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_412_p1),
    .din1(64'd4603804719079489536),
    .ce(grp_fu_131_ce),
    .opcode(5'd1),
    .dout(grp_fu_131_p2)
);

myproject_mul_mul_15ns_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_15ns_9s_24_1_0_U13(
    .din0(r_V_fu_624_p0),
    .din1(input_V_int_reg),
    .dout(r_V_fu_624_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln154_4_fu_616_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln908_reg_669 <= icmp_ln908_fu_293_p2;
        or_ln899_s_reg_664[0] <= or_ln899_s_fu_285_p3[0];
        or_ln924_reg_682 <= or_ln924_fu_442_p2;
        p_Result_s_reg_648 <= p_Result_s_fu_149_p4;
        p_Val2_53_reg_632 <= {{r_V_fu_624_p2[18:16]}};
        p_Val2_53_reg_632_pp0_iter1_reg <= p_Val2_53_reg_632;
        p_Val2_53_reg_632_pp0_iter2_reg <= p_Val2_53_reg_632_pp0_iter1_reg;
        sub_ln894_reg_658 <= sub_ln894_fu_177_p2;
        trunc_ln893_reg_653 <= trunc_ln893_fu_173_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        input_V_int_reg <= input_V;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln154_4_fu_616_p3;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_116_ce = 1'b1;
    end else begin
        grp_fu_116_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_121_ce = 1'b1;
    end else begin
        grp_fu_121_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_126_ce = 1'b1;
    end else begin
        grp_fu_126_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_131_ce = 1'b1;
    end else begin
        grp_fu_131_ce = 1'b0;
    end
end

assign a_fu_240_p2 = (icmp_ln897_fu_203_p2 & icmp_ln897_2_fu_234_p2);

assign add_ln147_fu_448_p2 = ($signed(3'd5) + $signed(p_Val2_53_reg_632_pp0_iter2_reg));

assign add_ln899_fu_260_p2 = (3'd3 + trunc_ln894_fu_183_p1);

assign add_ln908_fu_305_p2 = ($signed(32'd4294967242) + $signed(sub_ln894_reg_658));

assign add_ln915_fu_378_p2 = (11'd1 + sub_ln915_fu_373_p2);

assign and_ln147_1_fu_517_p2 = (icmp_ln146_2_fu_501_p2 & and_ln147_fu_511_p2);

assign and_ln147_fu_511_p2 = (icmp_ln147_fu_463_p2 & icmp_ln146_3_fu_506_p2);

assign and_ln154_1_fu_534_p2 = (or_ln924_reg_682 & or_ln154_1_fu_528_p2);

assign and_ln154_fu_539_p2 = (icmp_ln885_fu_523_p2 & and_ln154_1_fu_534_p2);

assign and_ln155_1_fu_551_p2 = (or_ln924_reg_682 & or_ln155_fu_545_p2);

assign and_ln155_fu_556_p2 = (icmp_ln885_fu_523_p2 & and_ln155_1_fu_551_p2);

assign and_ln899_fu_273_p2 = (xor_ln899_fu_254_p2 & p_Result_17_fu_266_p3);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign bitcast_ln729_fu_412_p1 = p_Result_26_fu_400_p5;

assign icmp_ln146_1_fu_490_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln146_2_fu_501_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg != 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln146_3_fu_506_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg != 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln146_fu_485_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_463_p2 = ((tmp_9_fu_453_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_474_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_469_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln885_fu_523_p2 = ((p_Val2_53_reg_632_pp0_iter2_reg != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln897_2_fu_234_p2 = ((p_Result_16_fu_229_p2 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln897_fu_203_p2 = (($signed(tmp_10_fu_193_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln908_fu_293_p2 = (($signed(lsb_index_fu_187_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln924_2_fu_436_p2 = ((trunc_ln6_fu_420_p4 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln924_fu_430_p2 = ((select_ln915_fu_384_p3 != 11'd2047) ? 1'b1 : 1'b0);


always @ (p_Result_25_fu_158_p3) begin
    if (p_Result_25_fu_158_p3[0] == 1'b1) begin
        l_fu_165_p3 = 32'd0;
    end else if (p_Result_25_fu_158_p3[1] == 1'b1) begin
        l_fu_165_p3 = 32'd1;
    end else if (p_Result_25_fu_158_p3[2] == 1'b1) begin
        l_fu_165_p3 = 32'd2;
    end else if (p_Result_25_fu_158_p3[3] == 1'b1) begin
        l_fu_165_p3 = 32'd3;
    end else if (p_Result_25_fu_158_p3[4] == 1'b1) begin
        l_fu_165_p3 = 32'd4;
    end else if (p_Result_25_fu_158_p3[5] == 1'b1) begin
        l_fu_165_p3 = 32'd5;
    end else if (p_Result_25_fu_158_p3[6] == 1'b1) begin
        l_fu_165_p3 = 32'd6;
    end else if (p_Result_25_fu_158_p3[7] == 1'b1) begin
        l_fu_165_p3 = 32'd7;
    end else if (p_Result_25_fu_158_p3[8] == 1'b1) begin
        l_fu_165_p3 = 32'd8;
    end else if (p_Result_25_fu_158_p3[9] == 1'b1) begin
        l_fu_165_p3 = 32'd9;
    end else if (p_Result_25_fu_158_p3[10] == 1'b1) begin
        l_fu_165_p3 = 32'd10;
    end else if (p_Result_25_fu_158_p3[11] == 1'b1) begin
        l_fu_165_p3 = 32'd11;
    end else if (p_Result_25_fu_158_p3[12] == 1'b1) begin
        l_fu_165_p3 = 32'd12;
    end else if (p_Result_25_fu_158_p3[13] == 1'b1) begin
        l_fu_165_p3 = 32'd13;
    end else if (p_Result_25_fu_158_p3[14] == 1'b1) begin
        l_fu_165_p3 = 32'd14;
    end else if (p_Result_25_fu_158_p3[15] == 1'b1) begin
        l_fu_165_p3 = 32'd15;
    end else if (p_Result_25_fu_158_p3[16] == 1'b1) begin
        l_fu_165_p3 = 32'd16;
    end else if (p_Result_25_fu_158_p3[17] == 1'b1) begin
        l_fu_165_p3 = 32'd17;
    end else if (p_Result_25_fu_158_p3[18] == 1'b1) begin
        l_fu_165_p3 = 32'd18;
    end else if (p_Result_25_fu_158_p3[19] == 1'b1) begin
        l_fu_165_p3 = 32'd19;
    end else if (p_Result_25_fu_158_p3[20] == 1'b1) begin
        l_fu_165_p3 = 32'd20;
    end else if (p_Result_25_fu_158_p3[21] == 1'b1) begin
        l_fu_165_p3 = 32'd21;
    end else if (p_Result_25_fu_158_p3[22] == 1'b1) begin
        l_fu_165_p3 = 32'd22;
    end else if (p_Result_25_fu_158_p3[23] == 1'b1) begin
        l_fu_165_p3 = 32'd23;
    end else if (p_Result_25_fu_158_p3[24] == 1'b1) begin
        l_fu_165_p3 = 32'd24;
    end else if (p_Result_25_fu_158_p3[25] == 1'b1) begin
        l_fu_165_p3 = 32'd25;
    end else if (p_Result_25_fu_158_p3[26] == 1'b1) begin
        l_fu_165_p3 = 32'd26;
    end else if (p_Result_25_fu_158_p3[27] == 1'b1) begin
        l_fu_165_p3 = 32'd27;
    end else if (p_Result_25_fu_158_p3[28] == 1'b1) begin
        l_fu_165_p3 = 32'd28;
    end else if (p_Result_25_fu_158_p3[29] == 1'b1) begin
        l_fu_165_p3 = 32'd29;
    end else if (p_Result_25_fu_158_p3[30] == 1'b1) begin
        l_fu_165_p3 = 32'd30;
    end else if (p_Result_25_fu_158_p3[31] == 1'b1) begin
        l_fu_165_p3 = 32'd31;
    end else begin
        l_fu_165_p3 = 32'd32;
    end
end

assign lsb_index_fu_187_p2 = ($signed(32'd4294967243) + $signed(sub_ln894_fu_177_p2));

assign lshr_ln897_fu_223_p2 = 3'd7 >> zext_ln897_fu_219_p1;

assign lshr_ln908_fu_310_p2 = zext_ln907_2_fu_302_p1 >> add_ln908_fu_305_p2;

assign m_12_fu_335_p3 = ((icmp_ln908_reg_669[0:0] === 1'b1) ? zext_ln908_fu_316_p1 : shl_ln908_fu_329_p2);

assign m_13_fu_345_p2 = (zext_ln911_fu_342_p1 + m_12_fu_335_p3);

assign m_22_fu_361_p1 = m_s_fu_351_p4;

assign m_fu_299_p1 = p_Val2_53_reg_632_pp0_iter1_reg;

assign m_s_fu_351_p4 = {{m_13_fu_345_p2[63:1]}};

assign or_ln146_fu_495_p2 = (icmp_ln146_fu_485_p2 | icmp_ln146_1_fu_490_p2);

assign or_ln148_fu_479_p2 = (icmp_ln879_fu_469_p2 | icmp_ln879_2_fu_474_p2);

assign or_ln154_1_fu_528_p2 = (grp_fu_121_p2 | grp_fu_116_p2);

assign or_ln154_2_fu_584_p2 = (or_ln146_fu_495_p2 | and_ln147_1_fu_517_p2);

assign or_ln154_3_fu_610_p2 = (or_ln154_fu_570_p2 | or_ln154_2_fu_584_p2);

assign or_ln154_fu_570_p2 = (and_ln155_fu_556_p2 | and_ln154_fu_539_p2);

assign or_ln155_fu_545_p2 = (grp_fu_131_p2 | grp_fu_126_p2);

assign or_ln899_fu_279_p2 = (and_ln899_fu_273_p2 | a_fu_240_p2);

assign or_ln899_s_fu_285_p3 = {{31'd0}, {or_ln899_fu_279_p2}};

assign or_ln924_fu_442_p2 = (icmp_ln924_fu_430_p2 | icmp_ln924_2_fu_436_p2);

assign p_Result_16_fu_229_p2 = (p_Val2_53_reg_632 & lshr_ln897_fu_223_p2);

assign p_Result_17_fu_266_p3 = p_Val2_53_reg_632[add_ln899_fu_260_p2];

assign p_Result_25_fu_158_p3 = {{29'd536870911}, {p_Result_s_reg_648}};

assign p_Result_26_fu_400_p5 = {{tmp_8_fu_392_p3}, {m_22_fu_361_p1[51:0]}};

integer ap_tvar_int_0;

always @ (r_V_fu_624_p2) begin
    for (ap_tvar_int_0 = 3 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 18 - 16) begin
            p_Result_s_fu_149_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_149_p4[ap_tvar_int_0] = r_V_fu_624_p2[18 - ap_tvar_int_0];
        end
    end
end

assign r_V_fu_624_p0 = 24'd10430;

assign select_ln154_1_fu_576_p3 = ((and_ln147_1_fu_517_p2[0:0] === 1'b1) ? 4'd8 : 4'd0);

assign select_ln154_2_fu_590_p3 = ((or_ln148_fu_479_p2[0:0] === 1'b1) ? 5'd0 : 5'd8);

assign select_ln154_3_fu_598_p3 = ((or_ln154_fu_570_p2[0:0] === 1'b1) ? select_ln154_fu_562_p3 : select_ln154_1_fu_576_p3);

assign select_ln154_4_fu_616_p3 = ((or_ln154_3_fu_610_p2[0:0] === 1'b1) ? sext_ln154_fu_606_p1 : select_ln154_2_fu_590_p3);

assign select_ln154_fu_562_p3 = ((and_ln154_fu_539_p2[0:0] === 1'b1) ? 4'd5 : 4'd10);

assign select_ln915_fu_384_p3 = ((tmp_12_fu_365_p3[0:0] === 1'b1) ? add_ln915_fu_378_p2 : sub_ln915_fu_373_p2);

assign sext_ln154_fu_606_p1 = $signed(select_ln154_3_fu_598_p3);

assign shl_ln908_fu_329_p2 = m_fu_299_p1 << zext_ln908_2_fu_325_p1;

assign sub_ln894_fu_177_p2 = (32'd3 - l_fu_165_p3);

assign sub_ln897_fu_213_p2 = (2'd1 - trunc_ln897_fu_209_p1);

assign sub_ln908_fu_320_p2 = (32'd54 - sub_ln894_reg_658);

assign sub_ln915_fu_373_p2 = (11'd1022 - trunc_ln893_reg_653);

assign tmp_10_fu_193_p4 = {{lsb_index_fu_187_p2[31:1]}};

assign tmp_11_fu_246_p3 = lsb_index_fu_187_p2[32'd31];

assign tmp_12_fu_365_p3 = m_13_fu_345_p2[32'd54];

assign tmp_8_fu_392_p3 = {{1'd0}, {select_ln915_fu_384_p3}};

assign tmp_9_fu_453_p4 = {{add_ln147_fu_448_p2[2:1]}};

assign trunc_ln6_fu_420_p4 = {{m_13_fu_345_p2[52:1]}};

assign trunc_ln893_fu_173_p1 = l_fu_165_p3[10:0];

assign trunc_ln894_fu_183_p1 = sub_ln894_fu_177_p2[2:0];

assign trunc_ln897_fu_209_p1 = sub_ln894_fu_177_p2[1:0];

assign xor_ln899_fu_254_p2 = (tmp_11_fu_246_p3 ^ 1'd1);

assign zext_ln897_fu_219_p1 = sub_ln897_fu_213_p2;

assign zext_ln907_2_fu_302_p1 = p_Val2_53_reg_632_pp0_iter1_reg;

assign zext_ln908_2_fu_325_p1 = sub_ln908_fu_320_p2;

assign zext_ln908_fu_316_p1 = lshr_ln908_fu_310_p2;

assign zext_ln911_fu_342_p1 = or_ln899_s_reg_664;

always @ (posedge ap_clk) begin
    or_ln899_s_reg_664[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //cos_lut_ap_fixed_9_6_5_3_0_s
