// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _generic_sincos_14_6_s_HH_
#define _generic_sincos_14_6_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cordic_circ_apfixed_16_3_0_s.h"
#include "myproject_mul_mul_22ns_14ns_35_1_0.h"
#include "myproject_mac_mulsub_17ns_6ns_21ns_23_1_0.h"

namespace ap_rtl {

struct generic_sincos_14_6_s : public sc_module {
    // Port declarations 6
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<14> > in_V;
    sc_out< sc_lv<10> > ap_return_0;
    sc_out< sc_lv<10> > ap_return_1;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    generic_sincos_14_6_s(sc_module_name name);
    SC_HAS_PROCESS(generic_sincos_14_6_s);

    ~generic_sincos_14_6_s();

    sc_trace_file* mVcdFile;

    cordic_circ_apfixed_16_3_0_s* grp_cordic_circ_apfixed_16_3_0_s_fu_70;
    myproject_mul_mul_22ns_14ns_35_1_0<1,1,22,14,35>* myproject_mul_mul_22ns_14ns_35_1_0_U2;
    myproject_mac_mulsub_17ns_6ns_21ns_23_1_0<1,1,17,6,21,23>* myproject_mac_mulsub_17ns_6ns_21ns_23_1_0_U3;
    sc_signal< sc_lv<1> > sign0_V_fu_75_p2;
    sc_signal< sc_lv<1> > sign0_V_reg_381;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > sign0_V_reg_381_pp0_iter1_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_381_pp0_iter2_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_381_pp0_iter3_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_381_pp0_iter4_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_381_pp0_iter5_reg;
    sc_signal< sc_lv<1> > sign0_V_reg_381_pp0_iter6_reg;
    sc_signal< sc_lv<14> > p_Val2_s_fu_87_p3;
    sc_signal< sc_lv<14> > p_Val2_s_reg_386;
    sc_signal< sc_lv<6> > ret_V_reg_391;
    sc_signal< sc_lv<2> > k_V_reg_396;
    sc_signal< sc_lv<2> > k_V_reg_396_pp0_iter1_reg;
    sc_signal< sc_lv<2> > k_V_reg_396_pp0_iter2_reg;
    sc_signal< sc_lv<2> > k_V_reg_396_pp0_iter3_reg;
    sc_signal< sc_lv<2> > k_V_reg_396_pp0_iter4_reg;
    sc_signal< sc_lv<2> > k_V_reg_396_pp0_iter5_reg;
    sc_signal< sc_lv<2> > k_V_reg_396_pp0_iter6_reg;
    sc_signal< sc_lv<1> > icmp_ln879_fu_140_p2;
    sc_signal< sc_lv<1> > icmp_ln879_reg_404;
    sc_signal< sc_lv<1> > icmp_ln879_reg_404_pp0_iter2_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_404_pp0_iter3_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_404_pp0_iter4_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_404_pp0_iter5_reg;
    sc_signal< sc_lv<1> > icmp_ln879_reg_404_pp0_iter6_reg;
    sc_signal< sc_lv<15> > z_V_1_fu_189_p3;
    sc_signal< sc_lv<15> > z_V_1_reg_410;
    sc_signal< sc_lv<16> > x_V_reg_415;
    sc_signal< sc_lv<15> > trunc_ln266_fu_205_p1;
    sc_signal< sc_lv<15> > trunc_ln266_reg_420;
    sc_signal< sc_lv<10> > trunc_ln1_reg_425;
    sc_signal< sc_lv<15> > trunc_ln1253_fu_219_p1;
    sc_signal< sc_lv<15> > trunc_ln1253_reg_431;
    sc_signal< sc_lv<16> > grp_cordic_circ_apfixed_16_3_0_s_fu_70_ap_return_0;
    sc_signal< sc_lv<16> > grp_cordic_circ_apfixed_16_3_0_s_fu_70_ap_return_1;
    sc_signal< sc_logic > grp_cordic_circ_apfixed_16_3_0_s_fu_70_ap_ce;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call24;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call24;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call24;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call24;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call24;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call24;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6_ignore_call24;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7_ignore_call24;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp33;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<14> > inabs_V_fu_81_p2;
    sc_signal< sc_lv<35> > r_V_61_fu_363_p2;
    sc_signal< sc_lv<21> > lhs_V_fu_120_p3;
    sc_signal< sc_lv<23> > grp_fu_371_p3;
    sc_signal< sc_lv<15> > p_Val2_43_fu_131_p4;
    sc_signal< sc_lv<14> > trunc_ln708_s_fu_149_p4;
    sc_signal< sc_lv<16> > rhs_V_8_fu_145_p1;
    sc_signal< sc_lv<16> > ret_V_50_fu_162_p2;
    sc_signal< sc_lv<1> > icmp_ln251_fu_178_p2;
    sc_signal< sc_lv<1> > or_ln251_fu_183_p2;
    sc_signal< sc_lv<15> > trunc_ln708_12_fu_168_p4;
    sc_signal< sc_lv<15> > z_V_fu_158_p1;
    sc_signal< sc_lv<15> > r_V_63_fu_228_p2;
    sc_signal< sc_lv<15> > r_V_64_fu_248_p2;
    sc_signal< sc_lv<1> > icmp_ln879_1_fu_223_p2;
    sc_signal< sc_lv<10> > trunc_ln708_14_fu_253_p4;
    sc_signal< sc_lv<1> > xor_ln879_fu_270_p2;
    sc_signal< sc_lv<1> > and_ln879_fu_276_p2;
    sc_signal< sc_lv<10> > select_ln879_fu_263_p3;
    sc_signal< sc_lv<1> > or_ln879_fu_288_p2;
    sc_signal< sc_lv<1> > icmp_ln879_2_fu_243_p2;
    sc_signal< sc_lv<1> > xor_ln879_1_fu_293_p2;
    sc_signal< sc_lv<1> > and_ln879_1_fu_299_p2;
    sc_signal< sc_lv<10> > select_ln879_1_fu_281_p3;
    sc_signal< sc_lv<10> > trunc_ln708_13_fu_233_p4;
    sc_signal< sc_lv<10> > trunc_ln3_fu_313_p4;
    sc_signal< sc_lv<10> > select_ln879_3_fu_322_p3;
    sc_signal< sc_lv<10> > p_Val2_49_fu_305_p3;
    sc_signal< sc_lv<10> > sub_ln703_fu_338_p2;
    sc_signal< sc_lv<10> > p_Val2_50_fu_344_p3;
    sc_signal< sc_lv<10> > select_ln879_4_fu_330_p3;
    sc_signal< sc_lv<22> > r_V_61_fu_363_p0;
    sc_signal< sc_lv<14> > r_V_61_fu_363_p1;
    sc_signal< sc_lv<17> > grp_fu_371_p0;
    sc_signal< sc_lv<6> > grp_fu_371_p1;
    sc_signal< sc_lv<21> > grp_fu_371_p2;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<14> > in_V_int_reg;
    sc_signal< sc_lv<10> > ap_return_0_int_reg;
    sc_signal< sc_lv<10> > ap_return_1_int_reg;
    sc_signal< sc_lv<22> > grp_fu_371_p10;
    sc_signal< sc_lv<23> > grp_fu_371_p20;
    sc_signal< sc_lv<35> > r_V_61_fu_363_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<16> ap_const_lv16_6487;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<35> ap_const_lv35_145F30;
    static const sc_lv<22> ap_const_lv22_C90F;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_and_ln879_1_fu_299_p2();
    void thread_and_ln879_fu_276_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp33();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call24();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call24();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call24();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call24();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call24();
    void thread_ap_block_state6_pp0_stage0_iter5();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call24();
    void thread_ap_block_state7_pp0_stage0_iter6();
    void thread_ap_block_state7_pp0_stage0_iter6_ignore_call24();
    void thread_ap_block_state8_pp0_stage0_iter7();
    void thread_ap_block_state8_pp0_stage0_iter7_ignore_call24();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_grp_cordic_circ_apfixed_16_3_0_s_fu_70_ap_ce();
    void thread_grp_fu_371_p0();
    void thread_grp_fu_371_p1();
    void thread_grp_fu_371_p10();
    void thread_grp_fu_371_p2();
    void thread_grp_fu_371_p20();
    void thread_icmp_ln251_fu_178_p2();
    void thread_icmp_ln879_1_fu_223_p2();
    void thread_icmp_ln879_2_fu_243_p2();
    void thread_icmp_ln879_fu_140_p2();
    void thread_inabs_V_fu_81_p2();
    void thread_lhs_V_fu_120_p3();
    void thread_or_ln251_fu_183_p2();
    void thread_or_ln879_fu_288_p2();
    void thread_p_Val2_43_fu_131_p4();
    void thread_p_Val2_49_fu_305_p3();
    void thread_p_Val2_50_fu_344_p3();
    void thread_p_Val2_s_fu_87_p3();
    void thread_r_V_61_fu_363_p0();
    void thread_r_V_61_fu_363_p1();
    void thread_r_V_61_fu_363_p10();
    void thread_r_V_63_fu_228_p2();
    void thread_r_V_64_fu_248_p2();
    void thread_ret_V_50_fu_162_p2();
    void thread_rhs_V_8_fu_145_p1();
    void thread_select_ln879_1_fu_281_p3();
    void thread_select_ln879_3_fu_322_p3();
    void thread_select_ln879_4_fu_330_p3();
    void thread_select_ln879_fu_263_p3();
    void thread_sign0_V_fu_75_p2();
    void thread_sub_ln703_fu_338_p2();
    void thread_trunc_ln1253_fu_219_p1();
    void thread_trunc_ln266_fu_205_p1();
    void thread_trunc_ln3_fu_313_p4();
    void thread_trunc_ln708_12_fu_168_p4();
    void thread_trunc_ln708_13_fu_233_p4();
    void thread_trunc_ln708_14_fu_253_p4();
    void thread_trunc_ln708_s_fu_149_p4();
    void thread_xor_ln879_1_fu_293_p2();
    void thread_xor_ln879_fu_270_p2();
    void thread_z_V_1_fu_189_p3();
    void thread_z_V_fu_158_p1();
};

}

using namespace ap_rtl;

#endif
