// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cos_lut_ap_fixed_11_6_5_3_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        input_V,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [10:0] input_V;
output  [6:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] sincos1_1_address0;
reg    sincos1_1_ce0;
wire   [4:0] sincos1_1_q0;
wire   [8:0] sincos1_0_address0;
reg    sincos1_0_ce0;
wire   [5:0] sincos1_0_q0;
reg   [4:0] p_Val2_61_reg_768;
reg   [4:0] p_Val2_61_reg_768_pp0_iter1_reg;
reg   [1:0] luTdex1_V_reg_777;
reg   [1:0] luTdex1_V_reg_777_pp0_iter1_reg;
reg   [2:0] octant_V_reg_782;
reg   [2:0] octant_V_reg_782_pp0_iter1_reg;
reg   [2:0] octant_V_reg_782_pp0_iter2_reg;
reg   [0:0] tmp_10_reg_793;
reg   [0:0] tmp_10_reg_793_pp0_iter1_reg;
reg   [4:0] p_Result_s_fu_216_p4;
reg   [4:0] p_Result_s_reg_798;
wire   [10:0] trunc_ln893_fu_240_p1;
reg   [10:0] trunc_ln893_reg_803;
wire   [31:0] sub_ln894_fu_244_p2;
reg   [31:0] sub_ln894_reg_808;
wire   [31:0] or_ln899_s_fu_352_p3;
reg   [31:0] or_ln899_s_reg_814;
wire   [0:0] icmp_ln908_fu_360_p2;
reg   [0:0] icmp_ln908_reg_819;
wire   [63:0] bitcast_ln729_fu_505_p1;
wire   [0:0] or_ln924_fu_535_p2;
reg   [0:0] or_ln924_reg_842;
wire   [0:0] icmp_ln885_fu_541_p2;
reg   [0:0] icmp_ln885_reg_848;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln544_fu_386_p1;
wire  signed [25:0] r_V_fu_757_p2;
wire   [31:0] p_Result_27_fu_225_p3;
reg   [31:0] l_fu_232_p3;
wire   [31:0] lsb_index_fu_254_p2;
wire   [30:0] tmp_12_fu_260_p4;
wire   [2:0] trunc_ln897_fu_276_p1;
wire   [2:0] sub_ln897_fu_280_p2;
wire   [4:0] zext_ln897_fu_286_p1;
wire   [4:0] lshr_ln897_fu_290_p2;
wire   [4:0] p_Result_17_fu_296_p2;
wire   [0:0] icmp_ln897_fu_270_p2;
wire   [0:0] icmp_ln897_2_fu_301_p2;
wire   [0:0] tmp_13_fu_313_p3;
wire   [4:0] trunc_ln894_fu_250_p1;
wire   [4:0] add_ln899_fu_327_p2;
wire   [0:0] p_Result_18_fu_333_p3;
wire   [0:0] xor_ln899_fu_321_p2;
wire   [0:0] and_ln899_fu_340_p2;
wire   [0:0] a_fu_307_p2;
wire   [0:0] or_ln899_fu_346_p2;
wire   [8:0] p_Result_26_fu_366_p3;
wire   [8:0] sub_ln214_fu_373_p2;
wire   [8:0] luTdex_V_2_fu_379_p3;
wire   [31:0] zext_ln907_2_fu_395_p1;
wire   [31:0] add_ln908_fu_398_p2;
wire   [31:0] lshr_ln908_fu_403_p2;
wire   [31:0] sub_ln908_fu_413_p2;
wire   [63:0] m_fu_392_p1;
wire   [63:0] zext_ln908_2_fu_418_p1;
wire   [63:0] zext_ln908_fu_409_p1;
wire   [63:0] shl_ln908_fu_422_p2;
wire   [63:0] zext_ln911_fu_435_p1;
wire   [63:0] m_12_fu_428_p3;
wire   [63:0] m_13_fu_438_p2;
wire   [62:0] m_s_fu_444_p4;
wire   [10:0] sub_ln915_fu_466_p2;
wire   [0:0] tmp_14_fu_458_p3;
wire   [10:0] add_ln915_fu_471_p2;
wire   [10:0] select_ln915_fu_477_p3;
wire   [63:0] m_22_fu_454_p1;
wire   [11:0] tmp_8_fu_485_p3;
wire   [63:0] p_Result_28_fu_493_p5;
wire   [51:0] trunc_ln6_fu_513_p4;
wire   [0:0] icmp_ln924_2_fu_529_p2;
wire   [0:0] icmp_ln924_fu_523_p2;
wire   [2:0] add_ln147_fu_546_p2;
wire   [1:0] tmp_11_fu_551_p4;
wire   [5:0] sub_ln703_fu_575_p2;
wire   [5:0] zext_ln1265_fu_567_p1;
wire   [0:0] icmp_ln146_fu_591_p2;
wire   [0:0] icmp_ln146_1_fu_596_p2;
wire   [0:0] icmp_ln146_2_fu_607_p2;
wire   [0:0] icmp_ln146_3_fu_612_p2;
wire   [0:0] and_ln146_fu_617_p2;
wire   [0:0] icmp_ln147_fu_561_p2;
wire   [0:0] xor_ln147_fu_629_p2;
wire   [0:0] icmp_ln148_fu_635_p2;
wire   [0:0] icmp_ln148_1_fu_640_p2;
wire   [0:0] and_ln148_1_fu_651_p2;
wire   [0:0] and_ln148_fu_645_p2;
wire   [0:0] grp_fu_158_p2;
wire   [0:0] grp_fu_163_p2;
wire   [0:0] or_ln154_1_fu_663_p2;
wire   [0:0] and_ln154_1_fu_669_p2;
wire   [0:0] grp_fu_168_p2;
wire   [0:0] grp_fu_173_p2;
wire   [0:0] or_ln155_fu_679_p2;
wire   [0:0] and_ln155_1_fu_685_p2;
wire   [0:0] and_ln154_fu_674_p2;
wire   [0:0] and_ln155_fu_690_p2;
wire   [0:0] and_ln148_2_fu_657_p2;
wire   [6:0] zext_ln1265_1_fu_571_p1;
wire  signed [6:0] sext_ln703_fu_581_p1;
wire   [0:0] and_ln147_fu_623_p2;
wire   [0:0] or_ln146_fu_601_p2;
wire   [5:0] sub_ln703_1_fu_585_p2;
wire   [5:0] select_ln154_2_fu_723_p3;
wire   [0:0] or_ln154_fu_703_p2;
wire   [6:0] select_ln154_fu_695_p3;
wire   [6:0] select_ln154_1_fu_709_p3;
wire   [0:0] or_ln154_2_fu_717_p2;
wire   [0:0] or_ln154_3_fu_743_p2;
wire   [6:0] select_ln154_3_fu_735_p3;
wire  signed [6:0] sext_ln154_fu_731_p1;
wire   [14:0] r_V_fu_757_p0;
reg    grp_fu_158_ce;
reg    ap_block_pp0_stage0_00001;
reg    grp_fu_163_ce;
reg    grp_fu_168_ce;
reg    grp_fu_173_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

sin_lut_ap_fixed_11_6_5_3_0_s_sincos1_1 #(
    .DataWidth( 5 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
sincos1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sincos1_1_address0),
    .ce0(sincos1_1_ce0),
    .q0(sincos1_1_q0)
);

sin_lut_ap_fixed_11_6_5_3_0_s_sincos1_0 #(
    .DataWidth( 6 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
sincos1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sincos1_0_address0),
    .ce0(sincos1_0_ce0),
    .q0(sincos1_0_q0)
);

myproject_dcmp_64ns_64ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_505_p1),
    .din1(64'd4593671619917905920),
    .ce(grp_fu_158_ce),
    .opcode(5'd1),
    .dout(grp_fu_158_p2)
);

myproject_dcmp_64ns_64ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_505_p1),
    .din1(64'd4606056518893174784),
    .ce(grp_fu_163_ce),
    .opcode(5'd1),
    .dout(grp_fu_163_p2)
);

myproject_dcmp_64ns_64ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_505_p1),
    .din1(64'd4600427019358961664),
    .ce(grp_fu_168_ce),
    .opcode(5'd1),
    .dout(grp_fu_168_p2)
);

myproject_dcmp_64ns_64ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
myproject_dcmp_64ns_64ns_1_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln729_fu_505_p1),
    .din1(64'd4603804719079489536),
    .ce(grp_fu_173_ce),
    .opcode(5'd1),
    .dout(grp_fu_173_p2)
);

myproject_mul_mul_15ns_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_15ns_11s_26_1_1_U15(
    .din0(r_V_fu_757_p0),
    .din1(input_V),
    .dout(r_V_fu_757_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln885_reg_848 <= icmp_ln885_fu_541_p2;
        octant_V_reg_782_pp0_iter2_reg <= octant_V_reg_782_pp0_iter1_reg;
        or_ln924_reg_842 <= or_ln924_fu_535_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln908_reg_819 <= icmp_ln908_fu_360_p2;
        luTdex1_V_reg_777 <= {{r_V_fu_757_p2[17:16]}};
        luTdex1_V_reg_777_pp0_iter1_reg <= luTdex1_V_reg_777;
        octant_V_reg_782 <= {{r_V_fu_757_p2[20:18]}};
        octant_V_reg_782_pp0_iter1_reg <= octant_V_reg_782;
        or_ln899_s_reg_814[0] <= or_ln899_s_fu_352_p3[0];
        p_Result_s_reg_798 <= p_Result_s_fu_216_p4;
        p_Val2_61_reg_768 <= {{r_V_fu_757_p2[20:16]}};
        p_Val2_61_reg_768_pp0_iter1_reg <= p_Val2_61_reg_768;
        sub_ln894_reg_808 <= sub_ln894_fu_244_p2;
        tmp_10_reg_793 <= r_V_fu_757_p2[32'd18];
        tmp_10_reg_793_pp0_iter1_reg <= tmp_10_reg_793;
        trunc_ln893_reg_803 <= trunc_ln893_fu_240_p1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_158_ce = 1'b1;
    end else begin
        grp_fu_158_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_163_ce = 1'b1;
    end else begin
        grp_fu_163_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_168_ce = 1'b1;
    end else begin
        grp_fu_168_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_173_ce = 1'b1;
    end else begin
        grp_fu_173_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sincos1_0_ce0 = 1'b1;
    end else begin
        sincos1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sincos1_1_ce0 = 1'b1;
    end else begin
        sincos1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_307_p2 = (icmp_ln897_fu_270_p2 & icmp_ln897_2_fu_301_p2);

assign add_ln147_fu_546_p2 = ($signed(3'd5) + $signed(octant_V_reg_782_pp0_iter2_reg));

assign add_ln899_fu_327_p2 = (5'd11 + trunc_ln894_fu_250_p1);

assign add_ln908_fu_398_p2 = ($signed(32'd4294967242) + $signed(sub_ln894_reg_808));

assign add_ln915_fu_471_p2 = (11'd1 + sub_ln915_fu_466_p2);

assign and_ln146_fu_617_p2 = (icmp_ln146_3_fu_612_p2 & icmp_ln146_2_fu_607_p2);

assign and_ln147_fu_623_p2 = (icmp_ln147_fu_561_p2 & and_ln146_fu_617_p2);

assign and_ln148_1_fu_651_p2 = (icmp_ln148_fu_635_p2 & icmp_ln148_1_fu_640_p2);

assign and_ln148_2_fu_657_p2 = (and_ln148_fu_645_p2 & and_ln148_1_fu_651_p2);

assign and_ln148_fu_645_p2 = (xor_ln147_fu_629_p2 & and_ln146_fu_617_p2);

assign and_ln154_1_fu_669_p2 = (or_ln924_reg_842 & or_ln154_1_fu_663_p2);

assign and_ln154_fu_674_p2 = (icmp_ln885_reg_848 & and_ln154_1_fu_669_p2);

assign and_ln155_1_fu_685_p2 = (or_ln924_reg_842 & or_ln155_fu_679_p2);

assign and_ln155_fu_690_p2 = (icmp_ln885_reg_848 & and_ln155_1_fu_685_p2);

assign and_ln899_fu_340_p2 = (xor_ln899_fu_321_p2 & p_Result_18_fu_333_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((or_ln154_3_fu_743_p2[0:0] === 1'b1) ? select_ln154_3_fu_735_p3 : sext_ln154_fu_731_p1);

assign bitcast_ln729_fu_505_p1 = p_Result_28_fu_493_p5;

assign icmp_ln146_1_fu_596_p2 = ((octant_V_reg_782_pp0_iter2_reg == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln146_2_fu_607_p2 = ((octant_V_reg_782_pp0_iter2_reg != 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln146_3_fu_612_p2 = ((octant_V_reg_782_pp0_iter2_reg != 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln146_fu_591_p2 = ((octant_V_reg_782_pp0_iter2_reg == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_561_p2 = ((tmp_11_fu_551_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln148_1_fu_640_p2 = ((octant_V_reg_782_pp0_iter2_reg != 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_635_p2 = ((octant_V_reg_782_pp0_iter2_reg != 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln885_fu_541_p2 = ((p_Val2_61_reg_768_pp0_iter1_reg != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln897_2_fu_301_p2 = ((p_Result_17_fu_296_p2 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln897_fu_270_p2 = (($signed(tmp_12_fu_260_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln908_fu_360_p2 = (($signed(lsb_index_fu_254_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln924_2_fu_529_p2 = ((trunc_ln6_fu_513_p4 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln924_fu_523_p2 = ((select_ln915_fu_477_p3 != 11'd2047) ? 1'b1 : 1'b0);


always @ (p_Result_27_fu_225_p3) begin
    if (p_Result_27_fu_225_p3[0] == 1'b1) begin
        l_fu_232_p3 = 32'd0;
    end else if (p_Result_27_fu_225_p3[1] == 1'b1) begin
        l_fu_232_p3 = 32'd1;
    end else if (p_Result_27_fu_225_p3[2] == 1'b1) begin
        l_fu_232_p3 = 32'd2;
    end else if (p_Result_27_fu_225_p3[3] == 1'b1) begin
        l_fu_232_p3 = 32'd3;
    end else if (p_Result_27_fu_225_p3[4] == 1'b1) begin
        l_fu_232_p3 = 32'd4;
    end else if (p_Result_27_fu_225_p3[5] == 1'b1) begin
        l_fu_232_p3 = 32'd5;
    end else if (p_Result_27_fu_225_p3[6] == 1'b1) begin
        l_fu_232_p3 = 32'd6;
    end else if (p_Result_27_fu_225_p3[7] == 1'b1) begin
        l_fu_232_p3 = 32'd7;
    end else if (p_Result_27_fu_225_p3[8] == 1'b1) begin
        l_fu_232_p3 = 32'd8;
    end else if (p_Result_27_fu_225_p3[9] == 1'b1) begin
        l_fu_232_p3 = 32'd9;
    end else if (p_Result_27_fu_225_p3[10] == 1'b1) begin
        l_fu_232_p3 = 32'd10;
    end else if (p_Result_27_fu_225_p3[11] == 1'b1) begin
        l_fu_232_p3 = 32'd11;
    end else if (p_Result_27_fu_225_p3[12] == 1'b1) begin
        l_fu_232_p3 = 32'd12;
    end else if (p_Result_27_fu_225_p3[13] == 1'b1) begin
        l_fu_232_p3 = 32'd13;
    end else if (p_Result_27_fu_225_p3[14] == 1'b1) begin
        l_fu_232_p3 = 32'd14;
    end else if (p_Result_27_fu_225_p3[15] == 1'b1) begin
        l_fu_232_p3 = 32'd15;
    end else if (p_Result_27_fu_225_p3[16] == 1'b1) begin
        l_fu_232_p3 = 32'd16;
    end else if (p_Result_27_fu_225_p3[17] == 1'b1) begin
        l_fu_232_p3 = 32'd17;
    end else if (p_Result_27_fu_225_p3[18] == 1'b1) begin
        l_fu_232_p3 = 32'd18;
    end else if (p_Result_27_fu_225_p3[19] == 1'b1) begin
        l_fu_232_p3 = 32'd19;
    end else if (p_Result_27_fu_225_p3[20] == 1'b1) begin
        l_fu_232_p3 = 32'd20;
    end else if (p_Result_27_fu_225_p3[21] == 1'b1) begin
        l_fu_232_p3 = 32'd21;
    end else if (p_Result_27_fu_225_p3[22] == 1'b1) begin
        l_fu_232_p3 = 32'd22;
    end else if (p_Result_27_fu_225_p3[23] == 1'b1) begin
        l_fu_232_p3 = 32'd23;
    end else if (p_Result_27_fu_225_p3[24] == 1'b1) begin
        l_fu_232_p3 = 32'd24;
    end else if (p_Result_27_fu_225_p3[25] == 1'b1) begin
        l_fu_232_p3 = 32'd25;
    end else if (p_Result_27_fu_225_p3[26] == 1'b1) begin
        l_fu_232_p3 = 32'd26;
    end else if (p_Result_27_fu_225_p3[27] == 1'b1) begin
        l_fu_232_p3 = 32'd27;
    end else if (p_Result_27_fu_225_p3[28] == 1'b1) begin
        l_fu_232_p3 = 32'd28;
    end else if (p_Result_27_fu_225_p3[29] == 1'b1) begin
        l_fu_232_p3 = 32'd29;
    end else if (p_Result_27_fu_225_p3[30] == 1'b1) begin
        l_fu_232_p3 = 32'd30;
    end else if (p_Result_27_fu_225_p3[31] == 1'b1) begin
        l_fu_232_p3 = 32'd31;
    end else begin
        l_fu_232_p3 = 32'd32;
    end
end

assign lsb_index_fu_254_p2 = ($signed(32'd4294967243) + $signed(sub_ln894_fu_244_p2));

assign lshr_ln897_fu_290_p2 = 5'd31 >> zext_ln897_fu_286_p1;

assign lshr_ln908_fu_403_p2 = zext_ln907_2_fu_395_p1 >> add_ln908_fu_398_p2;

assign luTdex_V_2_fu_379_p3 = ((tmp_10_reg_793_pp0_iter1_reg[0:0] === 1'b1) ? sub_ln214_fu_373_p2 : p_Result_26_fu_366_p3);

assign m_12_fu_428_p3 = ((icmp_ln908_reg_819[0:0] === 1'b1) ? zext_ln908_fu_409_p1 : shl_ln908_fu_422_p2);

assign m_13_fu_438_p2 = (zext_ln911_fu_435_p1 + m_12_fu_428_p3);

assign m_22_fu_454_p1 = m_s_fu_444_p4;

assign m_fu_392_p1 = p_Val2_61_reg_768_pp0_iter1_reg;

assign m_s_fu_444_p4 = {{m_13_fu_438_p2[63:1]}};

assign or_ln146_fu_601_p2 = (icmp_ln146_fu_591_p2 | icmp_ln146_1_fu_596_p2);

assign or_ln154_1_fu_663_p2 = (grp_fu_163_p2 | grp_fu_158_p2);

assign or_ln154_2_fu_717_p2 = (and_ln148_2_fu_657_p2 | and_ln147_fu_623_p2);

assign or_ln154_3_fu_743_p2 = (or_ln154_fu_703_p2 | or_ln154_2_fu_717_p2);

assign or_ln154_fu_703_p2 = (and_ln155_fu_690_p2 | and_ln154_fu_674_p2);

assign or_ln155_fu_679_p2 = (grp_fu_173_p2 | grp_fu_168_p2);

assign or_ln899_fu_346_p2 = (and_ln899_fu_340_p2 | a_fu_307_p2);

assign or_ln899_s_fu_352_p3 = {{31'd0}, {or_ln899_fu_346_p2}};

assign or_ln924_fu_535_p2 = (icmp_ln924_fu_523_p2 | icmp_ln924_2_fu_529_p2);

assign p_Result_17_fu_296_p2 = (p_Val2_61_reg_768 & lshr_ln897_fu_290_p2);

assign p_Result_18_fu_333_p3 = p_Val2_61_reg_768[add_ln899_fu_327_p2];

assign p_Result_26_fu_366_p3 = {{luTdex1_V_reg_777_pp0_iter1_reg}, {7'd0}};

assign p_Result_27_fu_225_p3 = {{27'd134217727}, {p_Result_s_reg_798}};

assign p_Result_28_fu_493_p5 = {{tmp_8_fu_485_p3}, {m_22_fu_454_p1[51:0]}};

integer ap_tvar_int_0;

always @ (r_V_fu_757_p2) begin
    for (ap_tvar_int_0 = 5 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 20 - 16) begin
            p_Result_s_fu_216_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_216_p4[ap_tvar_int_0] = r_V_fu_757_p2[20 - ap_tvar_int_0];
        end
    end
end

assign r_V_fu_757_p0 = 26'd10430;

assign select_ln154_1_fu_709_p3 = ((and_ln148_2_fu_657_p2[0:0] === 1'b1) ? zext_ln1265_1_fu_571_p1 : sext_ln703_fu_581_p1);

assign select_ln154_2_fu_723_p3 = ((or_ln146_fu_601_p2[0:0] === 1'b1) ? zext_ln1265_fu_567_p1 : sub_ln703_1_fu_585_p2);

assign select_ln154_3_fu_735_p3 = ((or_ln154_fu_703_p2[0:0] === 1'b1) ? select_ln154_fu_695_p3 : select_ln154_1_fu_709_p3);

assign select_ln154_fu_695_p3 = ((and_ln154_fu_674_p2[0:0] === 1'b1) ? 7'd22 : 7'd105);

assign select_ln915_fu_477_p3 = ((tmp_14_fu_458_p3[0:0] === 1'b1) ? add_ln915_fu_471_p2 : sub_ln915_fu_466_p2);

assign sext_ln154_fu_731_p1 = $signed(select_ln154_2_fu_723_p3);

assign sext_ln703_fu_581_p1 = $signed(sub_ln703_fu_575_p2);

assign shl_ln908_fu_422_p2 = m_fu_392_p1 << zext_ln908_2_fu_418_p1;

assign sincos1_0_address0 = zext_ln544_fu_386_p1;

assign sincos1_1_address0 = zext_ln544_fu_386_p1;

assign sub_ln214_fu_373_p2 = (9'd0 - p_Result_26_fu_366_p3);

assign sub_ln703_1_fu_585_p2 = (6'd0 - zext_ln1265_fu_567_p1);

assign sub_ln703_fu_575_p2 = (6'd0 - sincos1_0_q0);

assign sub_ln894_fu_244_p2 = (32'd5 - l_fu_232_p3);

assign sub_ln897_fu_280_p2 = (3'd3 - trunc_ln897_fu_276_p1);

assign sub_ln908_fu_413_p2 = (32'd54 - sub_ln894_reg_808);

assign sub_ln915_fu_466_p2 = (11'd1022 - trunc_ln893_reg_803);

assign tmp_11_fu_551_p4 = {{add_ln147_fu_546_p2[2:1]}};

assign tmp_12_fu_260_p4 = {{lsb_index_fu_254_p2[31:1]}};

assign tmp_13_fu_313_p3 = lsb_index_fu_254_p2[32'd31];

assign tmp_14_fu_458_p3 = m_13_fu_438_p2[32'd54];

assign tmp_8_fu_485_p3 = {{1'd0}, {select_ln915_fu_477_p3}};

assign trunc_ln6_fu_513_p4 = {{m_13_fu_438_p2[52:1]}};

assign trunc_ln893_fu_240_p1 = l_fu_232_p3[10:0];

assign trunc_ln894_fu_250_p1 = sub_ln894_fu_244_p2[4:0];

assign trunc_ln897_fu_276_p1 = sub_ln894_fu_244_p2[2:0];

assign xor_ln147_fu_629_p2 = (icmp_ln147_fu_561_p2 ^ 1'd1);

assign xor_ln899_fu_321_p2 = (tmp_13_fu_313_p3 ^ 1'd1);

assign zext_ln1265_1_fu_571_p1 = sincos1_0_q0;

assign zext_ln1265_fu_567_p1 = sincos1_1_q0;

assign zext_ln544_fu_386_p1 = luTdex_V_2_fu_379_p3;

assign zext_ln897_fu_286_p1 = sub_ln897_fu_280_p2;

assign zext_ln907_2_fu_395_p1 = p_Val2_61_reg_768_pp0_iter1_reg;

assign zext_ln908_2_fu_418_p1 = sub_ln908_fu_413_p2;

assign zext_ln908_fu_409_p1 = lshr_ln908_fu_403_p2;

assign zext_ln911_fu_435_p1 = or_ln899_s_reg_814;

always @ (posedge ap_clk) begin
    or_ln899_s_reg_814[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //cos_lut_ap_fixed_11_6_5_3_0_s
