// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.743000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=98,HLS_SYN_LUT=404,HLS_VERSION=2020_1}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V,
        x_V_ap_vld,
        y_0_V,
        y_0_V_ap_vld,
        y_1_V,
        y_1_V_ap_vld,
        y_2_V,
        y_2_V_ap_vld,
        y_3_V,
        y_3_V_ap_vld,
        y_4_V,
        y_4_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [95:0] x_V;
input   x_V_ap_vld;
output  [5:0] y_0_V;
output   y_0_V_ap_vld;
output  [5:0] y_1_V;
output   y_1_V_ap_vld;
output  [5:0] y_2_V;
output   y_2_V_ap_vld;
output  [5:0] y_3_V;
output   y_3_V_ap_vld;
output  [5:0] y_4_V;
output   y_4_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_0_V_ap_vld;
reg y_1_V_ap_vld;
reg y_2_V_ap_vld;
reg y_3_V_ap_vld;
reg y_4_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [95:0] x_V_preg;
reg   [95:0] x_V_in_sig;
reg    x_V_ap_vld_preg;
reg    x_V_ap_vld_in_sig;
reg    x_V_blk_n;
reg    ap_block_state1;
wire  signed [5:0] tmp_fu_146_p4;
wire  signed [5:0] tmp_1_fu_156_p4;
wire  signed [5:0] mul_ln1192_fu_184_p0;
wire  signed [9:0] sext_ln1118_fu_176_p1;
wire  signed [5:0] mul_ln1192_fu_184_p1;
wire   [9:0] mul_ln1192_fu_184_p2;
wire   [10:0] rhs_V_fu_198_p3;
wire  signed [11:0] sext_ln1192_fu_206_p1;
wire   [11:0] shl_ln_fu_190_p3;
wire   [10:0] rhs_V_1_fu_216_p3;
wire   [11:0] sub_ln1192_fu_210_p2;
wire  signed [11:0] sext_ln1192_1_fu_224_p1;
wire   [11:0] sub_ln1192_1_fu_228_p2;
wire   [11:0] ret_V_fu_234_p2;
wire  signed [5:0] p_Val2_2_fu_166_p4;
wire  signed [5:0] mul_ln1192_1_fu_255_p0;
wire  signed [5:0] mul_ln1192_1_fu_255_p1;
wire  signed [9:0] sext_ln1118_2_fu_251_p1;
wire   [9:0] mul_ln1192_1_fu_255_p2;
wire  signed [11:0] rhs_V_2_fu_269_p3;
wire   [13:0] shl_ln1192_1_fu_261_p3;
wire  signed [13:0] sext_ln1192_2_fu_277_p1;
wire   [13:0] sub_ln1192_2_fu_281_p2;
wire   [13:0] ret_V_1_fu_287_p2;
wire  signed [5:0] tmp_3_fu_304_p4;
wire  signed [5:0] mul_ln1192_2_fu_328_p0;
wire  signed [9:0] sext_ln1118_3_fu_324_p1;
wire  signed [5:0] mul_ln1192_2_fu_328_p1;
wire   [9:0] mul_ln1192_2_fu_328_p2;
wire   [11:0] sub_ln1192_3_fu_314_p2;
wire   [11:0] shl_ln1192_2_fu_334_p3;
wire   [4:0] tmp_6_fu_348_p4;
wire   [7:0] shl_ln1192_3_fu_358_p3;
wire  signed [7:0] sext_ln1192_3_fu_320_p1;
wire   [7:0] sub_ln1192_5_fu_366_p2;
wire   [11:0] shl_ln1192_4_fu_372_p3;
wire   [11:0] sub_ln1192_4_fu_342_p2;
wire   [11:0] add_ln1192_fu_380_p2;
wire   [11:0] ret_V_2_fu_386_p2;
wire  signed [5:0] mul_ln1192_3_fu_403_p0;
wire  signed [5:0] mul_ln1192_3_fu_403_p1;
wire   [9:0] mul_ln1192_3_fu_403_p2;
wire   [11:0] shl_ln1192_5_fu_409_p3;
wire   [9:0] rhs_V_3_fu_423_p3;
wire   [11:0] sub_ln1192_6_fu_417_p2;
wire  signed [11:0] sext_ln1192_4_fu_431_p1;
wire   [9:0] rhs_V_4_fu_441_p3;
wire   [11:0] sub_ln1192_7_fu_435_p2;
wire  signed [11:0] sext_ln1192_5_fu_449_p1;
wire   [11:0] sub_ln1192_8_fu_453_p2;
wire   [11:0] ret_V_3_fu_459_p2;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 x_V_preg = 96'd0;
#0 x_V_ap_vld_preg = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_V_ap_vld_preg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            x_V_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (x_V_ap_vld == 1'b1))) begin
            x_V_ap_vld_preg <= x_V_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_V_preg <= 96'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (x_V_ap_vld == 1'b1))) begin
            x_V_preg <= x_V;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((x_V_ap_vld == 1'b1)) begin
        x_V_ap_vld_in_sig = x_V_ap_vld;
    end else begin
        x_V_ap_vld_in_sig = x_V_ap_vld_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_V_blk_n = x_V_ap_vld;
    end else begin
        x_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((x_V_ap_vld == 1'b1)) begin
        x_V_in_sig = x_V;
    end else begin
        x_V_in_sig = x_V_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_0_V_ap_vld = 1'b1;
    end else begin
        y_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_1_V_ap_vld = 1'b1;
    end else begin
        y_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_2_V_ap_vld = 1'b1;
    end else begin
        y_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_3_V_ap_vld = 1'b1;
    end else begin
        y_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_4_V_ap_vld = 1'b1;
    end else begin
        y_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1192_fu_380_p2 = (shl_ln1192_4_fu_372_p3 + sub_ln1192_4_fu_342_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (x_V_ap_vld_in_sig == 1'b0));
end

assign mul_ln1192_1_fu_255_p0 = sext_ln1118_fu_176_p1;

assign mul_ln1192_1_fu_255_p1 = sext_ln1118_2_fu_251_p1;

assign mul_ln1192_1_fu_255_p2 = ($signed(mul_ln1192_1_fu_255_p0) * $signed(mul_ln1192_1_fu_255_p1));

assign mul_ln1192_2_fu_328_p0 = sext_ln1118_3_fu_324_p1;

assign mul_ln1192_2_fu_328_p1 = sext_ln1118_3_fu_324_p1;

assign mul_ln1192_2_fu_328_p2 = ($signed(mul_ln1192_2_fu_328_p0) * $signed(mul_ln1192_2_fu_328_p1));

assign mul_ln1192_3_fu_403_p0 = sext_ln1118_2_fu_251_p1;

assign mul_ln1192_3_fu_403_p1 = sext_ln1118_2_fu_251_p1;

assign mul_ln1192_3_fu_403_p2 = ($signed(mul_ln1192_3_fu_403_p0) * $signed(mul_ln1192_3_fu_403_p1));

assign mul_ln1192_fu_184_p0 = sext_ln1118_fu_176_p1;

assign mul_ln1192_fu_184_p1 = tmp_1_fu_156_p4;

assign mul_ln1192_fu_184_p2 = ($signed(mul_ln1192_fu_184_p0) * $signed(mul_ln1192_fu_184_p1));

assign p_Val2_2_fu_166_p4 = {{x_V_in_sig[89:84]}};

assign ret_V_1_fu_287_p2 = ($signed(sub_ln1192_2_fu_281_p2) + $signed(14'd15360));

assign ret_V_2_fu_386_p2 = ($signed(add_ln1192_fu_380_p2) + $signed(12'd3968));

assign ret_V_3_fu_459_p2 = ($signed(sub_ln1192_8_fu_453_p2) + $signed(12'd3968));

assign ret_V_fu_234_p2 = ($signed(sub_ln1192_1_fu_228_p2) + $signed(12'd3904));

assign rhs_V_1_fu_216_p3 = {{tmp_1_fu_156_p4}, {5'd0}};

assign rhs_V_2_fu_269_p3 = {{p_Val2_2_fu_166_p4}, {6'd0}};

assign rhs_V_3_fu_423_p3 = {{tmp_fu_146_p4}, {4'd0}};

assign rhs_V_4_fu_441_p3 = {{tmp_3_fu_304_p4}, {4'd0}};

assign rhs_V_fu_198_p3 = {{tmp_fu_146_p4}, {5'd0}};

assign sext_ln1118_2_fu_251_p1 = p_Val2_2_fu_166_p4;

assign sext_ln1118_3_fu_324_p1 = tmp_3_fu_304_p4;

assign sext_ln1118_fu_176_p1 = tmp_fu_146_p4;

assign sext_ln1192_1_fu_224_p1 = $signed(rhs_V_1_fu_216_p3);

assign sext_ln1192_2_fu_277_p1 = rhs_V_2_fu_269_p3;

assign sext_ln1192_3_fu_320_p1 = tmp_3_fu_304_p4;

assign sext_ln1192_4_fu_431_p1 = $signed(rhs_V_3_fu_423_p3);

assign sext_ln1192_5_fu_449_p1 = $signed(rhs_V_4_fu_441_p3);

assign sext_ln1192_fu_206_p1 = $signed(rhs_V_fu_198_p3);

assign shl_ln1192_1_fu_261_p3 = {{mul_ln1192_1_fu_255_p2}, {4'd0}};

assign shl_ln1192_2_fu_334_p3 = {{mul_ln1192_2_fu_328_p2}, {2'd0}};

assign shl_ln1192_3_fu_358_p3 = {{tmp_6_fu_348_p4}, {3'd0}};

assign shl_ln1192_4_fu_372_p3 = {{sub_ln1192_5_fu_366_p2}, {4'd0}};

assign shl_ln1192_5_fu_409_p3 = {{mul_ln1192_3_fu_403_p2}, {2'd0}};

assign shl_ln_fu_190_p3 = {{mul_ln1192_fu_184_p2}, {2'd0}};

assign sub_ln1192_1_fu_228_p2 = ($signed(sub_ln1192_fu_210_p2) - $signed(sext_ln1192_1_fu_224_p1));

assign sub_ln1192_2_fu_281_p2 = ($signed(shl_ln1192_1_fu_261_p3) - $signed(sext_ln1192_2_fu_277_p1));

assign sub_ln1192_3_fu_314_p2 = ($signed(12'd0) - $signed(rhs_V_2_fu_269_p3));

assign sub_ln1192_4_fu_342_p2 = (sub_ln1192_3_fu_314_p2 - shl_ln1192_2_fu_334_p3);

assign sub_ln1192_5_fu_366_p2 = ($signed(shl_ln1192_3_fu_358_p3) - $signed(sext_ln1192_3_fu_320_p1));

assign sub_ln1192_6_fu_417_p2 = (12'd0 - shl_ln1192_5_fu_409_p3);

assign sub_ln1192_7_fu_435_p2 = ($signed(sub_ln1192_6_fu_417_p2) - $signed(sext_ln1192_4_fu_431_p1));

assign sub_ln1192_8_fu_453_p2 = ($signed(sub_ln1192_7_fu_435_p2) - $signed(sext_ln1192_5_fu_449_p1));

assign sub_ln1192_fu_210_p2 = ($signed(sext_ln1192_fu_206_p1) - $signed(shl_ln_fu_190_p3));

assign tmp_1_fu_156_p4 = {{x_V_in_sig[17:12]}};

assign tmp_3_fu_304_p4 = {{x_V_in_sig[23:18]}};

assign tmp_6_fu_348_p4 = {{x_V_in_sig[22:18]}};

assign tmp_fu_146_p4 = {{x_V_in_sig[95:90]}};

assign y_0_V = {{ret_V_fu_234_p2[11:6]}};

assign y_1_V = {{ret_V_1_fu_287_p2[13:8]}};

assign y_2_V = {{ret_V_2_fu_386_p2[11:6]}};

assign y_3_V = {{ret_V_3_fu_459_p2[11:6]}};

assign y_4_V = 6'd62;

endmodule //myproject
