Backend: SymbolicExpression
ClockPeriod: 5
Compiler: vivado
HLSConfig:
  Model:
    Precision: ap_fixed<6,2>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
NSymbols: 16
OutputDir: my-hls-test-nov7-6-2
OutputPredictions: null
Part: xcvu9p-flga2577-2-e
ProjectName: myproject
Stamp: e11aF662
